ollama: fix to use new tar.zst compression

diff --git a/apps/Ollama GUI/install-64 b/apps/Ollama GUI/install-64
--- a/apps/Ollama GUI/install-64
+++ b/apps/Ollama GUI/install-64
@@ -19,9 +19,12 @@ else
   
   status "Installing ollama to /usr/local"
   sudo install -o0 -g0 -m755 -d /usr/local/bin
-  sudo install -o0 -g0 -m755 -d "/usr/local"
+  sudo install -o0 -g0 -m755 -d /usr/local
   status "Downloading Linux arm64 bundle"
-  wget -qO- "https://ollama.com/download/ollama-linux-arm64.tgz" | sudo tar -xzf - -C "/usr/local"
+  wget -O- https://github.com/ollama/ollama/releases/latest/download/ollama-linux-arm64.tar.zst | sudo tar --zstd -xf - -C "/usr/local"
+  if [ ${PIPESTATUS[0]}${PIPESTATUS[1]} != 00 ];then
+    error "failed to download and extract ollama!"
+  fi
   
   sudo touch "$version_checker_file"
 fi
@@ -105,7 +108,7 @@ sudo xdg-icon-resource forceupdate --mode system
 if [ -z "$(ollama list | tail -n +2)" ];then
   #skip if insufficient RAM
   if [ "$(awk '/MemTotal/ {print $2}' /proc/meminfo)" -gt $((1024000*7)) ];then
-    #skip if insufficient dick space
+    #skip if insufficient disk space
     if [ $(df --output=avail / | tail -1) -ge $((8*1024*1024)) ]; then
       status "Downloading 2 LLMs: phi3:mini and codellama:7b"
       ollama pull phi3:mini || (sleep 20; ollama pull phi3:mini) || warning "failed to download phi3:mini."
