MuseScore: update to 4.3.0
release name changed to "MuseScore Studio"

diff --git a/apps/MuseScore/install b/apps/MuseScore/install
--- a/apps/MuseScore/install
+++ b/apps/MuseScore/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-version=4.2.1.240230938-experimental
+version=4.3.0.241231432
 
 if [ $arch == 32 ];then
   url_arch=armv7l
@@ -17,7 +17,7 @@ fi
 
 enable_module fuse || exit 1
 
-wget -O "/tmp/MuseScore.AppImage" "https://github.com/musescore/MuseScore/releases/download/v${version%.*}/MuseScore-${version}-${url_arch}.AppImage" || exit 1
+wget -O "/tmp/MuseScore.AppImage" "https://github.com/musescore/MuseScore/releases/download/v${version%.*}/MuseScore-Studio-${version}-${url_arch}.AppImage" || exit 1
 
 chmod +x "/tmp/MuseScore.AppImage"
 
@@ -29,6 +29,8 @@ sudo /tmp/MuseScore.AppImage install || error "MuseScore.AppImage failed to run 
 sudo rm -f /usr/local/bin/mscore
 sudo ln -s /usr/local/bin/MuseScore.AppImage /usr/local/bin/mscore
 
-#change menu button label to 'MuseScore 4'
-sudo sed -i 's/^Name=.*/Name=MuseScore 4/g' /usr/local/share/applications/org.musescore.MuseScore4portable.desktop
-true #in case sed fails
+#remove "Portable" from menu button
+sudo sed -i 's/ Portable$//g' /usr/local/share/applications/org.musescore.MuseScore4portable.desktop
+# update timestamp of top level icon directory to signal icon cache to be refreshed
+sudo touch /usr/local/share/icons
+true #in case touch fails
