Mac OS Theme: uninstall: add warning if script nonexistant

diff --git a/apps/Mac OS Theme/uninstall b/apps/Mac OS Theme/uninstall
--- a/apps/Mac OS Theme/uninstall
+++ b/apps/Mac OS Theme/uninstall
@@ -9,7 +9,10 @@ function error {
 
 #Running uninstall script
 if [ -f ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh ];then
-  sudo chmod +x ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh
-  ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh
+  chmod +x ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh
+  ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh || error "The script ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh exited with failure!"
+else
+  echo "WARNING: could not find script ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh"
 fi
 
+exit 0
