use pipestatus

diff --git a/apps/Pi Power Tools/install b/apps/Pi Power Tools/install
--- a/apps/Pi Power Tools/install
+++ b/apps/Pi Power Tools/install
@@ -1,5 +1,9 @@
 #!/bin/bash
 # Get dependencies
 install_packages yad systemd-container xserver-xephyr expect || exit 1
-script=$(wget -O - https://raw.githubusercontent.com/Botspot/Pi-Power-Tools/master/update) || error "Failed to download Pi Power Tools update script!"
-bash <<< "$script" || error "Pi Power Tools updater script failed!"
+wget -O - https://raw.githubusercontent.com/Botspot/Pi-Power-Tools/master/update | bash
+if [ "${PIPESTATUS[0]}" != 0 ];then
+  error "PPT script download failed"
+elif [ "${PIPESTATUS[1]}" != 0 ];then
+  error "PPT script execution failed"
+fi
