Rewrite the More RAM app

diff --git a/apps/More RAM/install b/apps/More RAM/install
--- a/apps/More RAM/install
+++ b/apps/More RAM/install
@@ -1,13 +1,65 @@
 #!/bin/bash
 
-#variables to know if zram failed or if swap failed
-swap_failed=0
-zram_failed=0
+#This script enables ZRAM and attempts to optimize its effectiveness on Raspberry Pi computers.
+#Useful links:
+#https://haydenjames.io/linux-performance-almost-always-add-swap-part2-zram
+#https://linuxreviews.org/Zram
+#https://linuxize.com/post/how-to-change-the-swappiness-value-in-linux
 
-if sudo modprobe zram ;then
-  status "Creating zram script: /usr/bin/zram.sh"
-  #original zram script from novaspirit: https://github.com/novaspirit/rpi_zram
-  echo '#!/bin/bash
+#original zram script from novaspirit: https://github.com/novaspirit/rpi_zram
+
+set_value() { #Add the $1 line to the $2 config file. (setting=value format) This function changes the setting if it's already there.
+  local file="$2"
+  [ -z "$file" ] && error "set_value: path to config-file must be specified."
+  [ ! -f "$file" ] && error "Config file '$file' does not exist!"
+  local setting="$1"
+  
+  #This function assumes a setting=value format. Remove the number value to be able to change it.
+  local setting_without_value="$(echo "$setting" | awk -F= '{print $1}')"
+  
+  #edit the config file with the new value
+  sudo sed -i "s/^${setting_without_value}=.*/${setting}/g" "$file"
+  
+  #ensure sed actually did something; if not, add setting to end of file
+  if ! grep -qxF "$setting" "$file" ;then
+    echo "$setting" | sudo tee -a "$file" >/dev/null
+  fi
+}
+
+set_sysctl_value() { #Change a setting for sysctl. Displays value, changes config file, and sets the value immediately.
+  set_value "$1" /etc/sysctl.conf
+  echo "  - $1"
+  sudo sysctl "$1" >/dev/null
+}
+
+#disable dphys-swapfile service if running
+if [ -f /usr/sbin/dphys-swapfile ] && systemctl is-active --quiet dphys-swapfile.service;then
+  status "Disabling swap"
+  #swapoff and remove swapfile
+  sudo /usr/sbin/dphys-swapfile uninstall
+  
+  #prevent dphys-swapfile from running on boot
+  sudo systemctl disable dphys-swapfile.service #see /lib/systemd/system/dphys-swapfile.service
+fi
+
+status -n "Checking system for compatibility... "
+if [ "$(ps --no-headers -o comm 1)" != systemd ];then
+  error "\nUser error: Incompatible because your system was not booted with systemd."
+elif ! command -v zramctl >/dev/null ;then
+  error "\nUser error: Incompatible because the 'zramctl' command is missing on your system."
+elif ! command -v swapon >/dev/null ;then
+  error "\nUser error: Incompatible because the 'swapon' command is missing on your system."
+elif ! command -v swapoff >/dev/null ;then
+  error "\nUser error: Incompatible because the 'swapoff' command is missing on your system."
+elif ! command -v modprobe >/dev/null ;then
+  error "\nUser error: Incompatible because the 'modprobe' command is missing on your system."
+elif ! sudo modprobe zram &>/dev/null ;then
+  error "\nUser error: Incompatible because the 'zram' kernel module is missing on your system."
+fi
+status_green "Done"
+
+status "Creating zram script: /usr/bin/zram.sh"
+echo '#!/bin/bash
 
 export LANG=C
 
@@ -16,122 +68,105 @@ if [ $(id -u) -ne 0 ]; then
   exit 1
 fi
 
-cores=$(nproc --all)
-
-# disable zram
-core=0
-while [ $core -lt $cores ]; do
-  if [[ -b /dev/zram$core ]]; then
-    swapoff /dev/zram$core &>/dev/null
-  fi
-  let core=core+1
-done
-if [[ -n $(lsmod | grep zram) ]]; then
-  rmmod zram
+# Load zram module
+if ! modprobe zram ;then
+  echo "Failed to load zram kernel module"
+  exit 1
 fi
+
+# disable all zram devices
+IFS=$'\''\n'\''
+for device_number in $(find /dev/ -name zram* -type b | tr -cd "0123456789\n") ;do
+  #if zram device is a swap device, disable it
+  swapoff /dev/zram${device_number} 2>/dev/null
+  
+  #if zram device is mounted, unmount it
+  umount /dev/zram${device_number} 2>/dev/null
+  
+  #remove device
+  echo $device_number >/sys/class/zram-control/hot_remove
+done
+
+rm -rf /zram
+
+#exit script now if "exit" flag passed
 if [[ $1 == stop ]]; then
   exit 0
 fi
 
-# enable zram
-modprobe zram num_devices=$cores
+#create new zram drive - for swap
+drive_num=$(cat /sys/class/zram-control/hot_add)
 
-echo lz4 > /sys/block/zram0/comp_algorithm
+# use zstd compression if available - best option according to https://linuxreviews.org/Comparison_of_Compression_Algorithms#zram_block_drive_compression
+if cat /sys/block/zram${drive_num}/comp_algorithm | grep -q zstd ;then
+  algorithm=zstd
+else
+  algorithm=lz4
+fi
+echo $algorithm > /sys/block/zram${drive_num}/comp_algorithm
 
 totalmem=$(free | grep -e "^Mem:" | awk '\''{print $2}'\'')
-mem=$(( ($totalmem / $cores)* 1024 ))
 
-core=0
-while [ $core -lt $cores ]; do
-  echo $mem > /sys/block/zram$core/disksize
-  mkswap /dev/zram$core
-  swapon -p 5 /dev/zram$core
-  let core=core+1
-done' | sudo tee /usr/bin/zram.sh >/dev/null
-  
-  sudo chmod +x /usr/bin/zram.sh
-  
-  status "Making it run on startup"
-  if ! grep -qxF '/usr/bin/zram.sh &' /etc/rc.local ;then
-    sudo sed -i 's+^exit 0$+/usr/bin/zram.sh \&\nexit 0+g' /etc/rc.local
-  fi
-  
-  status -n "Running it now."
-  echo " Output:"
-  sudo /usr/bin/zram.sh
-else
-  warning "Not enabling ZRAM because your system kernel does not support it."
-  zram_failed=1
-fi
+#create zram disk 4 times larger than usable RAM - compression ratio for zstd can approach 5:1 according to https://linuxreviews.org/Zram
+echo $((totalmem * 1024 * 4)) > /sys/block/zram${drive_num}/disksize
 
-#Skip swapfile setup if available free space is less than 2GB
-if [ "$(df -a / -B 1 --output=avail | tail -1 | tr -d ' ')" -lt $((2*1024*1024*1024)) ];then
-  swap_failed=1
-  warning "Not enabling a 1GB swap file because your SD card has less than 2GB of free space."
-fi
+#make the swap device (by default this will be /dev/zram0)
+mkswap /dev/zram${drive_num}
+swapon /dev/zram${drive_num} -d -p 1
 
-if [ $swap_failed == 0 ] && ! package_installed dphys-swapfile ;then
-  echo
-  (install_packages dphys-swapfile)
-  #if dphys-swapfile could not be installed, skip everything swap-related
-  if [ $? != 0 ];then
-    swap_failed=1
-    warning "Not enabling a swap file because the dphys-swapfile package could not be installed."
-  fi
-fi
 
-if [ $swap_failed == 0 ];then
-  echo
-  status "Setting up a 1GB swapfile"
-  
-  echo "  - Turning off swap"
-  sudo systemctl stop dphys-swapfile.service #see /lib/systemd/system/dphys-swapfile.service
-  #systemctl will run this command:
-  #sudo /usr/sbin/dphys-swapfile swapoff
-  
-  echo "  - Changing CONF_SWAPSIZE to 1GB"
-  sudo sed -i 's/^CONF_SWAPSIZE=.*/CONF_SWAPSIZE=1024/g' /etc/dphys-swapfile
-  #ensure sed actually did something; if not, add line to end of file
-  if ! grep -qxF 'CONF_SWAPSIZE=1024' /etc/dphys-swapfile ;then
-    echo 'CONF_SWAPSIZE=1024' | sudo tee -a /etc/dphys-swapfile >/dev/null
-  fi
-  
-  #change swappiness if not already 50. See: https://linuxize.com/post/how-to-change-the-swappiness-value-in-linux
-  if [ -e /usr/sbin/sysctl ];then
-    echo "  - Changing swappiness value to 50"
-    #change value temporarily for this boot
-    sudo sysctl vm.swappiness=50 >/dev/null
-    #change value for subsequent boots
-    sudo sed -i 's/^vm.swappiness=.*/vm.swappiness=50/g' /etc/sysctl.conf
-    
-    #ensure sed actually did something; if not, add line to end of file
-    if ! grep -qxF 'vm.swappiness=50' /etc/sysctl.conf ;then
-      echo 'vm.swappiness=50' | sudo tee -a /etc/sysctl.conf >/dev/null
-    fi
-  fi
-  
-  echo "  - Turning swap back on"
-  sudo systemctl unmask dphys-swapfile.service
-  errors="$(sudo systemctl enable dphys-swapfile.service 2>&1)" || echo "Failed to run dphys-swapfile.service"
-  sudo /usr/sbin/dphys-swapfile swapon
-fi
+
+#create second zram drive: for temporary user-storage at /zram
+drive_num=$(cat /sys/class/zram-control/hot_add)
+
+# set compression algorithm
+echo $algorithm > /sys/block/zram${drive_num}/comp_algorithm
+
+#set the size of drive to be 4 times the available RAM
+echo $((totalmem * 1024 * 4)) > /sys/block/zram${drive_num}/disksize
+
+#create a partition and mount it
+mkfs.ext4 /dev/zram${drive_num} >/dev/null
+mkdir -p /zram
+mount /dev/zram${drive_num} /zram' | sudo tee /usr/bin/zram.sh >/dev/null
+
+sudo chmod +x /usr/bin/zram.sh
+
+status "Making it run on startup"
+echo '  - Creating zram-swap.service'
+echo '[Unit]
+Description=Configures zram swap device
+After=local-fs.target
+
+[Service]
+Type=oneshot
+ExecStart=/usr/bin/zram.sh
+ExecStop=/usr/bin/zram.sh stop
+RemainAfterExit=yes
+
+[Install]
+WantedBy = multi-user.target' | sudo tee /etc/systemd/system/zram-swap.service >/dev/null
+echo '  - Reloading Systemd unit files'
+sudo systemctl daemon-reload
+echo '  - Enabling zram-swap.service to run on boot'
+sudo systemctl enable zram-swap.service
+
+status -n "Running it now."
+echo " Output:"
+sudo /usr/bin/zram.sh || exit 1
+
+status "Changing kernel parameters for better performance:"
+#change kernel values as recommended by: https://haydenjames.io/linux-performance-almost-always-add-swap-part2-zram
+set_sysctl_value vm.swappiness=100
+set_sysctl_value vm.vfs_cache_pressure=500
+set_sysctl_value vm.dirty_background_ratio=1
+set_sysctl_value vm.dirty_ratio=50
 
 echo
-if [ $swap_failed == 0 ] && [ $zram_failed == 0 ];then
-  status_green "Swap and ZRAM should now be set up. Consider rebooting your device."
-
-elif [ $swap_failed == 1 ] && [ $zram_failed == 0 ];then
-  status_green "ZRAM should now be set up. Consider rebooting your device."
-
-elif [ $swap_failed == 0 ] && [ $zram_failed == 1 ];then
-  status_green "Swap should now be set up. Consider rebooting your device."
-
-elif [ $swap_failed == 1 ] && [ $zram_failed == 1 ];then
-  error "User error: Unable to setup both Swap and ZRAM! You are probably using an unsupported device."
-fi
+status_green "ZRAM should now be set up. Consider rebooting your device."
 
 status "Below is a summary:"
-swapon -s
-status "You can see this at any time by running 'swapon -s'"
+zramctl
+status "You can see this at any time by running 'zramctl'"
 sleep 1
 
