More performance improvements to More RAM
vm.page-cluster=0 should especially improve performance a lot

diff --git a/apps/More RAM/install b/apps/More RAM/install
--- a/apps/More RAM/install
+++ b/apps/More RAM/install
@@ -103,6 +103,11 @@ sudo tee /usr/bin/zram.sh >/dev/null << "EOF"
 export LANG=C
 export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
 
+error() { #red text and exit 1
+  echo -e "\e[91m$1\e[0m" 1>&2
+  exit 1
+}
+
 if [ "$1" == --help ] || [ "$1" == -h ];then
   echo -e "This is a script made by Botspot to increase usable RAM by setting up ZRAM.
 ZRAM uses compression to fit more memory in your available RAM.
@@ -125,8 +130,7 @@ elif [ "$1" == flush ];then
   #find which zram swap is the most used, and clear that one
   flush_zram="$(cat /proc/swaps | tail +2 | grep '^/dev/zram' | awk '{print $4" "$1}' | sort -n | tail -1 | awk '{print $2}' | sed 's+^/dev/++g')"
   if [ -z "$flush_zram" ];then
-    echo "No zram devices found, cannot flush"
-    exit 1
+    error "No zram devices found, cannot flush"
   fi
   echo -n "Flushing $flush_zram... "
   swapoff /dev/${flush_zram}
@@ -137,8 +141,7 @@ elif [ "$1" == flush ];then
 fi
 
 if [ $(id -u) -ne 0 ]; then
-  echo "zram.sh must be run as root user"
-  exit 1
+  error "zram.sh must be run as root user"
 fi
 
 #avoid creating /zram storage if storage-off flag passed
@@ -157,8 +160,7 @@ fi
 # Load zram module
 if ! lsmod | awk "{print $1}" | grep -qxF zram ;then
   if ! modprobe zram ;then
-    echo "Failed to load zram kernel module"
-    exit 1
+    error "Failed to load zram kernel module"
   fi
 fi
 
@@ -168,12 +170,18 @@ IFS=$'\n'
 for device_number in $(find /dev/ -name zram* -type b | tr -cd "0123456789\n") ;do
   #if zram device is a swap device, disable it
   swapoff /dev/zram${device_number} 2>/dev/null
+  if [ $? == 137 ];then
+    error "Cannot disable ZRAM because doing so would overflow your RAM. Try closing some programs, then run this script again."
+  fi
   
   #if zram device is mounted, unmount it
   umount /dev/zram${device_number} 2>/dev/null
   
   #remove device
-  echo $device_number >/sys/class/zram-control/hot_remove
+  echo $device_number > /sys/class/zram-control/hot_remove
+  if [ $? != 0 ];then
+	error "Cannot disable ZRAM because doing so would overflow your RAM. Try closing some programs, then run this script again."
+  fi
 done
 echo Done
 
@@ -294,10 +302,19 @@ if [ "$(awk '/MemTotal/ {print $2}' /proc/meminfo)" -lt $((2*1024*1024)) ];then
   echo 'vm.swappiness=100
 vm.vfs_cache_pressure=500
 vm.dirty_background_ratio=1
-vm.dirty_ratio=50' | sudo tee /etc/sysctl.d/zram.conf >/dev/null
+vm.dirty_ratio=50
+vm.page-cluster=0
+vm.watermark_boost_factor=0
+vm.watermark_scale_factor=125' | sudo tee /etc/sysctl.d/zram.conf >/dev/null
 else
-  #otherwise only maximize swappiness
-  echo 'vm.swappiness=100' | sudo tee /etc/sysctl.d/zram.conf >/dev/null
+  #otherwise set the values that make good use of zram while keeping file caching
+  echo 'vm.swappiness=100
+vm.page-cluster=0
+vm.watermark_boost_factor=0
+vm.watermark_scale_factor=125' | sudo tee /etc/sysctl.d/zram.conf >/dev/null
+  #vm.page-cluster=3 by default, or 32kb memory pages on 4k pagesize kernels. Good for physical swap but wasteful for zram.
+  #vm.page-cluster=0 uses memory pages the same size as the kernel pagesize, so 4kb on pi4 and 16kb on pi5 kernel. Smaller is better for zram.
+  #see https://wiki.archlinux.org/title/Zram#Optimizing_swap_on_zram
 fi
 #adopt these values now and print them
 sudo sysctl -p /etc/sysctl.d/zram.conf
