make whatsapp launcher use chromium to close #3038

diff --git a/apps/WhatsApp/install b/apps/WhatsApp/install
--- a/apps/WhatsApp/install
+++ b/apps/WhatsApp/install
@@ -6,7 +6,7 @@ sudo mkdir -p /usr/local/bin /usr/local/share/applications /usr/local/share/icon
 echo "Creating launcher and menu button..."
 echo '#!/bin/bash
 
-chromium-browser --user-data-dir="$HOME/.config/webapps/WhatsApp" --app=https://web.whatsapp.com --class=whatsapp' | sudo tee /usr/local/bin/whatsapp >/dev/null || error "Failed to create whatsapp launcher!"
+chromium --user-data-dir="$HOME/.config/webapps/WhatsApp" --app=https://web.whatsapp.com --class=whatsapp' | sudo tee /usr/local/bin/whatsapp >/dev/null || error "Failed to create whatsapp launcher!"
 
 sudo chmod +x /usr/local/bin/whatsapp || error "Failed to set whatsapp launcher permissions!"
 
