fix syntax errors and use $HOME

diff --git a/apps/PiGro/install b/apps/PiGro/install
--- a/apps/PiGro/install
+++ b/apps/PiGro/install
@@ -1,44 +1,28 @@
 #!/bin/bash
-rm -rf ~/PiGro-Aid- || error "Failed to first remove ~/PiGro-Aid- folder!"
-git_clone https://github.com/actionschnitzel/PiGro-Aid- || error "Failed to clone repository!"
+
 # Get dependencies
 install_packages xterm python3-pil python3-pil.imagetk python3-pip mpg123 lolcat || exit 1
-cd PiGro-Aid- || error "Failed to enter directory!"
-
+# Get Python dependencies
 pip3 install playsound psutil distro py-notifier
 
+rm -rf ~/PiGro-Aid- || error "Failed to first remove ~/PiGro-Aid- folder!"
+git_clone https://github.com/actionschnitzel/PiGro-Aid- || error "Failed to clone repository!"
 
+cd PiGro-Aid- || error "Failed to enter directory!"
 chmod +x start.sh
-DIRECTORY="$(readlink -f "$(dirname "$0")")"
-if [ -z "$DIRECTORY" ] || [ "$DIRECTORY" == "$HOME" ] || [ "$DIRECTORY" == bash ];then
-  DIRECTORY="$HOME/PiGro-Aid-"
-  
 
-fi
 echo "[Desktop Entry]
 Version=2.1
-Exec=${DIRECTORY}/start.sh
+Exec=$HOME/PiGro-Aid-/start.sh
 Name=PiGro
 GenericName=PiGro
 Encoding=UTF-8
 Terminal=false
 Type=Application
 Categories=System
-Icon=${DIRECTORY}/images/icons/logo.png
-Path=${DIRECTORY}/" > ~/Desktop/pigro.desktop
+Icon=$HOME/PiGro-Aid-/images/icons/logo.png
+Path=$HOME/PiGro-Aid-/" > ~/Desktop/pigro.desktop
 
-sudo chmod +x ~/Desktop/pigro.desktop
-
-fi
-echo "[Desktop Entry]
-Version=2.1
-Exec=${DIRECTORY}/start.sh
-Name=PiGro
-GenericName=PiGro
-Encoding=UTF-8
-Terminal=false
-Type=Application
-Categories=System
-Icon=${DIRECTORY}/images/icons/logo.png
-Path=${DIRECTORY}/" > ~/.local/share/applications/pigro.desktop
+chmod +x ~/Desktop/pigro.desktop
+cp ~/Desktop/pigro.desktop ~/.local/share/applications/pigro.desktop
 
