Deskreen: add terminal-command back so description's "to run" is true

diff --git a/apps/Deskreen/install-32 b/apps/Deskreen/install-32
--- a/apps/Deskreen/install-32
+++ b/apps/Deskreen/install-32
@@ -6,14 +6,17 @@ rm -f ~/Deskreen-1.0.1-armv7l.AppImage.zip || error 'Failed to remove $HOME/.Des
 
 chmod +x ~/Deskreen-1.0.1-armv7l.AppImage || error "Failed to mark the appimage as executable"
 
+echo "#!/bin/bash
+sudo modprobe fuse
+$HOME/.Deskreen/Deskreen-1.0.1-armv7l.AppImage --no-sandbox" | sudo tee /usr/local/bin/deskreen >/dev/null || error 'Failed to create /usr/local/bin/deskreen!'
+
 echo "[Desktop Entry]
 Name=Deskreen
 Comment=Deskreen allows you to use any device on your local network as a secondary screen, through a web browser.
 GenericName=Screen sharing app
-Exec=bash -c 'sudo modprobe fuse; ~/Deskreen-1.0.1-armv7l.AppImage --no-sandbox'
+Exec=deskreen
 Icon=$(dirname "$0")/icon-64.png
 StartupNotify=true
 Terminal=false
 Type=Application
 Categories=Utility;" > ~/.local/share/applications/deskreen.desktop || error 'Failed to create menu shortcut!'
-
