move speedtest to single install script and update version to 1.1.1

diff --git a/apps/SpeedTest-CLI/install b/apps/SpeedTest-CLI/install
--- a/apps/SpeedTest-CLI/install
+++ b/apps/SpeedTest-CLI/install
@@ -1,12 +1,18 @@
 #!/bin/bash
+
+version=1.1.1
+case "$arch" in
+    "64") tar_arch="aarch64" ;;
+    "32") tar_arch="armhf" ;;
+    *) error "arch variable is not set, can not continue" ;;
+esac
+
 cd ~
 mkdir speedtest
-wget https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-aarch64-linux.tgz -O ~/speedtest.tgz || error 'Failed to download!'
+wget https://install.speedtest.net/app/cli/ookla-speedtest-${version}-linux-${tar_arch}.tgz -O ~/speedtest.tgz || error 'Failed to download!'
 cd speedtest
 tar -xvzf ~/speedtest.tgz || error "failed to extract files!"
-cd $HOME
 rm ~/speedtest.tgz
-
 printf "Creating shortcut..."
 echo "[Desktop Entry]
 Type=Application
@@ -19,8 +25,9 @@ Path=$HOME/speedtest
 Terminal=true
 StartupNotify=false" > ~/.local/share/applications/speedtest.desktop || error "failed to create menu shortcut!"
 echo "done"
-printf "creating /usr/local/bin/speedtest so you can launch from terminal..."
+echo -n "creating /usr/local/bin/speedtest so you can launch from terminal..."
 echo "#!/bin/bash
 $HOME/speedtest/speedtest \"\$@\"" | sudo tee /usr/local/bin/speedtest >/dev/null
 sudo chmod +x /usr/local/bin/speedtest
 echo "done"
+
