Sublime Text: switch to `add_external_repo` and `rm_external_repo`

diff --git a/apps/Sublime Text/install-64 b/apps/Sublime Text/install-64
--- a/apps/Sublime Text/install-64
+++ b/apps/Sublime Text/install-64
@@ -1,12 +1,14 @@
 #!/bin/bash
 
-status "Adding GPG key..."
-wget -qO- https://download.sublimetext.com/sublimehq-pub.gpg | sudo tee /etc/apt/trusted.gpg.d/sublimehq.asc || error "Failed to add GPG key for sublime-text repository!"
-echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
+#remove deprecated files
+sudo rm -f /etc/apt/trusted.gpg.d/sublimehq.asc /etc/apt/sources.list.d/sublime-text.list
 
-(install_packages sublime-text)
-if [ $? != 0 ];then
-  #if install_packages fails, remove repository
-  sudo rm -f /etc/apt/sources.list.d/sublime-text.list
-  exit 1
+add_external_repo "sublimehq" "https://download.sublimetext.com/ apt/stable/" "https://download.sublimetext.com/sublimehq-pub.gpg" || exit 1
+
+apt_update
+if [ $? != 0 ]; then
+  rm_external_repo "sublimehq"
+  error "Failed to perform apt update after adding sublimehq repository."
 fi
+
+install_packages sublime-text || exit 1
