fix Sublime Text arm64 installation script
As we know that `apt-key` is deprecated, it doesn't work on Raspberry Pi OS arm64.
The changes I made was manually tested by me so I can tell that they work.
Installing the package `gpg` is not required as it already comes default with a fresh installation of Raspberry Pi OS arm64, I tried to install it anyways for better support.

diff --git a/apps/Sublime Text/install-64 b/apps/Sublime Text/install-64
--- a/apps/Sublime Text/install-64
+++ b/apps/Sublime Text/install-64
@@ -1,6 +1,10 @@
 #!/bin/bash
-echo "Adding GPG key..."
-wget -qO- https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - || error "Failed to add GPG key for sublime-text repository!"
+
+## Install dependencies
+install_packages wget gpg || error "Failed to install dependencies"
+
+status "Adding GPG key..."
+gpg --keyserver keyserver.ubuntu.com --recv-keys F57D4F59BD3DF454 || error "Failed to add GPG key for sublime-text repository!"
 echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
 
 (install_packages sublime-text)
