fixed Discord install-64 script

diff --git a/apps/Discord/install-64 b/apps/Discord/install-64
--- a/apps/Discord/install-64
+++ b/apps/Discord/install-64
@@ -7,13 +7,17 @@ function error {
   exit 1
 }
 
-gio trash ~/discord-electron > /dev/null
-rm -f ~/.local/share/applications/discord.desktop > /dev/null
+function download() {
+  curl -s https://api.github.com/repos/SpacingBat3/electron-discord-webapp/releases/latest \
+  | grep "browser_download_url.*arm64.deb" \
+  | cut -d : -f 2,3 \
+  | tr -d \" \
+  | wget -qi -
+}
 
-echo "Downloading latest arm64 release..."
-curl -s https://api.github.com/repos/SpacingBat3/electron-discord-webapp/releases/latest \
-| grep "browser_download_url.*arm64.deb" \
-| cut -d : -f 2,3 \
-| tr -d \" \
-| wget -qi -
+gio trash ~/discord-electron 2> /dev/null
+rm -f ~/.local/share/applications/discord.desktop 2> /dev/null
+
+echo "downloading discord-electron..."
+download || error "Failed to download latest release!"
 sudo apt -f -y install ./electron-discord-webapp*arm64.deb
