close Discord before installing, add option to brand it

diff --git a/apps/Discord/install-32 b/apps/Discord/install-32
--- a/apps/Discord/install-32
+++ b/apps/Discord/install-32
@@ -9,11 +9,20 @@ function error {
 
 version='1.6.1'
 
+killall webcord &>/dev/null && echo "Closing Discord first..."
+
 echo "Downloading Webcord..."
-rm -f ~/webcord_${version}_armhf.deb
-wget https://github.com/SpacingBat3/WebCord/releases/download/v${version}/webcord_${version}_armhf.deb
+rm -f ~/webcord.deb
+wget -O ~/webcord.deb https://github.com/SpacingBat3/WebCord/releases/download/v${version}/webcord_${version}_armhf.deb
 
 echo "Installing Webcord..."
-"${DIRECTORY}/pkg-install" "$HOME/webcord_${version}_armhf.deb" "$(dirname "$0")" || error "Failed to install webcord deb!"
+"${DIRECTORY}/pkg-install" "$HOME/webcord.deb" "$(dirname "$0")" || error "Failed to install webcord deb!"
+rm -f ~/webcord.deb
 
-rm -f ~/webcord_${version}_armhf.deb
+#change this to true to brand Webcord as Discord
+if false;then
+  sudo sed -i 's/Name=.*/Name=Discord/g' /usr/share/applications/webcord.desktop
+
+  sudo cp -f $(dirname "$0")/icon-64.png /usr/share/pixmaps/webcord.png
+  sudo cp -f $(dirname "$0")/icon-64.png /usr/lib/webcord/resources/app.png
+fi
