Discord: use pkg-install

diff --git a/apps/Discord/install-32 b/apps/Discord/install-32
--- a/apps/Discord/install-32
+++ b/apps/Discord/install-32
@@ -9,15 +9,11 @@ function error {
 
 version='1.6.1'
 
-#remove electron-discord-webapp if it still exists
-if command -v webcord >/dev/null ;then
-  sudo apt purge webcord || error "failed to first uninstall electron-discord-webapp!"
-fi
-
 echo "Downloading Webcord..."
-
 rm -f ~/webcord_${version}_armhf.deb
 wget https://github.com/SpacingBat3/WebCord/releases/download/v${version}/webcord_${version}_armhf.deb
-sudo apt -fy install ~/webcord_${version}_armhf.deb || error "Failed to install webcord deb!"
+
+echo "Installing Webcord..."
+"${DIRECTORY}/pkg-install" "$HOME/webcord_${version}_armhf.deb" "$(dirname "$0")" || error "Failed to install webcord deb!"
 
 rm -f ~/webcord_${version}_armhf.deb
