Make Discord always stay up to date

diff --git a/apps/Discord/install-32 b/apps/Discord/install-32
--- a/apps/Discord/install-32
+++ b/apps/Discord/install-32
@@ -12,11 +12,17 @@ gio trash ~/discord-electron
 mkdir ~/discord-electron
 cd ~/discord-electron || error "Failed to enter discord-electron folder!"
 
-#Download from github
-wget https://github.com/SpacingBat3/electron-discord-webapp/releases/download/v0.1.4/electron-discord-webapp-0.1.4-armv7l.tar.gz || error 'Failed to download archive!'
+tagname="$(curl --silent "https://api.github.com/repos/SpacingBat3/electron-discord-webapp/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | tr -d 'v')"
 
-tar -xf electron-discord-webapp-0.1.4-armv7l.tar.gz --strip 1 || error 'Failed to extract archive!'
-rm -f electron-discord-webapp-0.1.4-armv7l.tar.gz
+if [ -z "$tagname" ];then
+  tagname='0.1.5'
+fi
+
+#Download from github
+wget https://github.com/SpacingBat3/electron-discord-webapp/releases/download/v${tagname}/electron-discord-webapp-${tagname}-armv7l.tar.gz || error 'Failed to download archive!'
+
+tar -xf electron-discord-webapp-${tagname}-armv7l.tar.gz --strip 1 || error 'Failed to extract archive!'
+rm -f electron-discord-webapp-${tagname}-armv7l.tar.gz
 
 cd $HOME
 
