Discord app update to spacingbat's webcord to close #541

diff --git a/apps/Discord/install-64 b/apps/Discord/install-64
--- a/apps/Discord/install-64
+++ b/apps/Discord/install-64
@@ -7,21 +7,17 @@ function error {
   exit 1
 }
 
-function download() {
-  curl -s https://api.github.com/repos/SpacingBat3/electron-discord-webapp/releases/latest \
-  | grep "browser_download_url.*arm64.deb" \
-  | cut -d : -f 2,3 \
-  | tr -d \" \
-  | wget -qi -
-}
+version='1.3.0'
 
-gio trash ~/discord-electron 2> /dev/null
-rm -f ~/.local/share/applications/discord.desktop 2> /dev/null
+#remove electron-discord-webapp if it still exists
+if command -v electron-discord-webapp >/dev/null ;then
+  sudo apt purge electron-discord-webapp || error "failed to first uninstall electron-discord-webapp!"
+fi
 
-echo "downloading discord-electron..."
-cd $HOME
-#download || error "Failed to download latest release!"
-wget https://github.com/SpacingBat3/electron-discord-webapp/releases/download/v1.2.1/electron-discord-webapp_1.2.1_arm64.deb
-sudo dpkg -i electron-discord-webapp*arm64.deb || error "Failed to install discord-electron!"
-sudo apt -f install
-rm -f electron-discord-webapp*arm64.deb
+echo "Downloading Webcord..."
+
+rm -f ~/webcord_${version}_arm64.deb
+wget https://github.com/SpacingBat3/electron-discord-webapp/releases/download/v${version}/webcord_${version}_arm64.deb
+sudo apt -fy install ~/webcord_${version}_arm64.deb || error "Failed to install webcord deb!"
+
+rm -f ~/webcord_${version}_arm64.deb
