Add `/usr/local/bin/oomox-gui` to launch oomox with `oomox-gui`

diff --git a/apps/Oomox Theme Designer/install b/apps/Oomox Theme Designer/install
--- a/apps/Oomox Theme Designer/install
+++ b/apps/Oomox Theme Designer/install
@@ -1,15 +1,22 @@
 #!/bin/bash
 
-"${DIRECTORY}/pkg-install" "python3-gi python3-gi-cairo libglib2.0-bin libgdk-pixbuf2.0-dev libxml2-utils x11-xserver-utils gir1.2-gtk-3.0 gir1.2-glib-2.0 gir1.2-pango-1.0 gir1.2-gdkpixbuf-2.0 gtk2-engines gtk2-engines-murrine gtk2-engines-pixbuf bash bc sed grep parallel sassc libsass1 imagemagick optipng librsvg2-bin inkscape python3-pillow python3-pystache python3-yaml make automake libgtk-3-dev breeze-icon-theme" "$(dirname "$0")" || error "Failed to install dependencies!"
+"${DIRECTORY}/pkg-install" "python3 python3-gi python3-gi-cairo libglib2.0-bin libgdk-pixbuf2.0-dev libxml2-utils x11-xserver-utils gir1.2-gtk-3.0 gir1.2-glib-2.0 gir1.2-pango-1.0 gir1.2-gdkpixbuf-2.0 gtk2-engines gtk2-engines-murrine gtk2-engines-pixbuf bash bc sed grep parallel sassc libsass1 imagemagick optipng librsvg2-bin inkscape python3-pillow python3-pystache python3-yaml make automake libgtk-3-dev breeze-icon-theme" "$(dirname "$0")" || error "Failed to install dependencies!"
 
-git_clone https://github.com/themix-project/oomox.git --recursive
+cd $HOME
+rm -rf oomox
+status "Cloning oomox repository...\nThis will take some time as --recursive flag is passed."
+git_clone https://github.com/themix-project/oomox.git --recursive || error "Failed to clone oomox repository!"
+echo "#!/bin/bash
+cd $HOME/oomox &&
+exec python3 -m oomox_gui '$@'" > /usr/local/bin/oomox-gui
 
+#create menu shortcut
 echo "[Desktop Entry]
 Type=Application
 Name=Oomox Theme Designer
 Comment=A tool to customize icons, xrdb and GTK themes. 
 Icon=$(dirname "$0")/icon-64.png
-Exec=$HOME/oomox/gui.sh
+Exec=oomox-gui
 StartupNotify=true
 Categories=Graphics;
 Keywords=color;gtk;highlight;theme;widget;numix;
