Update uninstall

diff --git a/apps/Quartz Browser/uninstall b/apps/Quartz Browser/uninstall
--- a/apps/Quartz Browser/uninstall
+++ b/apps/Quartz Browser/uninstall
@@ -7,15 +7,15 @@ function error {
   exit 1
 }
 
-source $DIRECTORY/api
+source "$DIRECTORY/api"
 
 if [ $arch == '32' ];then
-	# Removes menu shortcut
-	( rm -f $HOME/.local/share/applications/quartz-browser.desktop || sudo rm -f $HOME/.local/share/applications/quartz-browser.desktop ) &> /dev/null || error "Failed to remove menu shortcut!"
-	# Removes AppImage
-	( rm -f /usr/local/bin/Quartz_Browser.AppImage || sudo rm -f /usr/local/bin/Quartz_Browser.AppImage ) &> /dev/null || error "Failed to remove Quartz Browser!"
+  # Removes menu shortcut
+  rm -f $HOME/.local/share/applications/quartz-browser.desktop || error "Failed to remove menu shortcut!"
+  # Removes AppImage
+  rm -f ~/.local/share/Quartz_Browser.AppImage || error "Failed to remove Quartz Browser!"
 elif [ $arch == '64' ];then
-	( pip3 uninstall quartz-browser -y || sudo pip3 uninstall quartz-browser -y ) || error "Failed to uninstall Quartz Browser!"
-	rm -rf $HOME/quartz-browser-qt5 &> /dev/null || sudo rm -rf $HOME/quartz-browser-qt5 
-	"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 0
+  ( pip3 uninstall quartz-browser -y || sudo pip3 uninstall quartz-browser -y ) || error "Failed to uninstall Quartz Browser!"
+  rm -rf $HOME/quartz-browser-qt5 &> /dev/null || sudo rm -rf $HOME/quartz-browser-qt5 
+  "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 0
 fi
