fix errors

diff --git a/apps/Renoise (Demo)/install-64 b/apps/Renoise (Demo)/install-64
--- a/apps/Renoise (Demo)/install-64
+++ b/apps/Renoise (Demo)/install-64
@@ -8,8 +8,14 @@ cd Renoise_3_4_1_Demo_Linux_arm64 || error "Failed to cd into 'Renoise_3_4_1_Dem
 status_green "Done!"
 status "Installing Renoise..."
 chmod +x install.sh || error "Failed to set 'install.sh' as execuable!"
-sudo ./install.sh || error "Failed to install Renoise with 'install.sh'!"
-status_green "Done!"
+sudo ./install.sh
+if [ "$?" == "1" ]; then
+  status_green "Done!"  
+elif [ "$?" == "0" ]; then
+  error "Failed to install Renoise with 'install.sh'"
+else
+  warning "Unknown status code... Renoise may or may not have installed successfully."
+fi
 status "Cleaning up..."
 cd ../
 rm -rf Renoise_3_4_1_Demo_Linux_arm64 renoise-arm64.tar.gz
