Revert "Make url getting more future-proof"
This reverts commit 6b806702e830c8abc314a63b45e89aeaac1ee087.

diff --git a/apps/Renoise (Demo)/install-64 b/apps/Renoise (Demo)/install-64
--- a/apps/Renoise (Demo)/install-64
+++ b/apps/Renoise (Demo)/install-64
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-version="3_4_1"
-
 cd /tmp
-wget -O renoise-arm64.tar.gz "https://files.renoise.com/demo/Renoise_${version}_Demo_Linux_arm64.tar.gz" || exit 1
+wget -O renoise-arm64.tar.gz "https://files.renoise.com/demo/Renoise_3_4_1_Demo_Linux_arm64.tar.gz" || exit 1
 status "Extracting Renoise..."
 tar -xf renoise-arm64.tar.gz || error "Failed to extract Renoise!"
-cd Renoise_${version}_Demo_Linux_arm64 || error "Failed to cd into 'Renoise_${version}_Demo_Linux_arm64'!"
+cd Renoise_3_4_1_Demo_Linux_arm64 || error "Failed to cd into 'Renoise_3_4_1_Demo_Linux_arm64'!"
 status_green "Done!"
 status "Installing Renoise..."
 chmod +x install.sh || error "Failed to set 'install.sh' as execuable!"
@@ -20,5 +18,5 @@ else
 fi
 status "Cleaning up..."
 cd ../
-rm -rf Renoise_${version}_Demo_Linux_arm64 renoise-arm64.tar.gz
+rm -rf Renoise_3_4_1_Demo_Linux_arm64 renoise-arm64.tar.gz
 status_green "Done!"
