Simplify uninstall, and correct errors

diff --git a/apps/Renoise (Demo)/uninstall b/apps/Renoise (Demo)/uninstall
--- a/apps/Renoise (Demo)/uninstall
+++ b/apps/Renoise (Demo)/uninstall
@@ -1,8 +1,13 @@
 #!/bin/bash
 
 cd /tmp
-wget -O renoise-armhf.tar.gz "https://files.renoise.com/demo/Renoise_3_4_1_Demo_Linux_armhf.tar.gz" || exit 1
-status "Extracting Renoise..."
-tar -xf renoise-armhf.tar.gz || error "Failed to extract Renoise!"
-cd Renoise_3_4_1_Demo_Linux_armhf || error "Failed to cd into 'Renoise_3_4_1_Demo_Linux_armhf'!"
-sudo ./uninstall.sh || error "Failed to unistall Renoise with 'uninstall.sh'!"
+wget "https://raw.githubusercontent.com/Crilum/stuff/main/install.sh" || error "Failed to download 'install.sh'!"
+chmod +x install.sh || error "Failed to make 'install.sh' executable!"
+sudo ./install.sh -u
+if [ "$?" == "1" ]; then
+  status "Uninstall finished!"
+elif [ "$?" == "0" ]; then
+  error "Failed to uninstall Renoise with 'install.sh -u'"
+else
+  warning "Unknown status code... Renoise may or may not have uninstalled successfully."
+fi
