Add retry button, subterminal, summary window to manage daemon (#2708)

diff --git a/api b/api
--- a/api
+++ b/api
@@ -1081,51 +1081,24 @@ terminal_manage() { # wrapper for the original terminal_manage function to termi
   terminal_manage_multi "$action $app"
 }
 
-terminal_manage_multi() { #function to install/uninstall/update/refresh multiple apps (or filelists) - uses a terminal and refreshes the app list
-  queue="$1" #one or multiple actions and app names (or filelists of the format 'filelist:path/to/file:path/to/another/file')
+terminal_manage_multi() { #function to install/uninstall/update/refresh apps or refresh-file files, one per line - refreshes the gui app list if applicable
+  local queue="$1" #one action per line, in the format "$action $app" or "update-file $file"
   
   #To prevent multiple simultaneous manage instances, use the 'daemon' mode. This will create a queue of actions that are executed concurrently.
-  #The first daemon instance is the 'master' process. Subsequent processes will add the action to the queue and then exit.
+  #The first daemon instance is the 'master' process, which opens a terminal. Subsequent processes will add the action to the queue and then exit.
   #All output is generated by the 'master' daemon process. Subsequent processes shouldn't open a terminal, because the master one is already open.
   if [ -f "${DIRECTORY}/data/manage-daemon/pid" ] && process_exists $(cat "${DIRECTORY}/data/manage-daemon/pid") ;then
-    #The 'master' daemon is already running. Avoid launching a second terminal.
+    #daemon already running, send queue to it and exit
     "${DIRECTORY}/manage" daemon "$queue"
     
   else
-    #in a terminal, first get the api functions, display the pi-apps logo, run the manage script, and refresh the app list if the $pipe variable is set
-    "${DIRECTORY}/etc/terminal-run" '
-      DIRECTORY="'"$DIRECTORY"'"
-      export geometry2="'"$geometry2"'"
-      source "${DIRECTORY}/api"
-      generate_logo
-      
-      refresh_list() { #Refresh the current list of apps in the event of a change
-        if [ ! -z "'"$pipe"'" ] && [ -p "'"$pipe"'" ];then
-          echo -e "\f" > "'"$pipe"'"
-          "${DIRECTORY}/preload" "$(cat "${DIRECTORY}/data/settings/App List Style")" "'"$prefix"'" > "'"$pipe"'" 2>/dev/null
-        fi
-      }
-      
-      "${DIRECTORY}/manage" daemon "'"$queue"'"
-      
-      #refresh app list
-      refresh_list
-      
-      for i in {30..1} ;do
-        echo -en "You can close this window now. Auto-closing in $i seconds.\e[0K\r"
-        sleep 1
-      done
-      ' "Terminal Output"
+    #this function is running the daemon, so once it exits refresh the pi-apps list
+    "${DIRECTORY}/manage" daemon "$queue"
     
-    # Check if terminal-run failed to launch. GUI users don't see any terminal output if it fails (since there is no terminal open) so we need to prompt them with a GUI window
-    if [ "$?" != 0 ]; then
-      echo -e "Unable to open a terminal.\nDebug output below.\n$(DEBUG=1 "${DIRECTORY}/etc/terminal-run" 2>&1)" | yad --center --window-icon="${DIRECTORY}/icons/logo.png" \
-      --width=700 --height=300 --text-info --title="Error occured when calling terminal-run" \
-      --image="${DIRECTORY}/icons/error.png" --image-on-top --fontname=12 \
-      --button='OK'
-      if echo "$queue" | grep -q "^update filelist:" ;then #list of files separated by :
-        updatable_apps='' updatable_files="$(echo "$queue" | grep "^update filelist:" | sed 's/^update filelist://g' | tr ':' '\n')" no_status=true update_now_cli
-      fi
+    #refresh app list
+    if [ ! -z "$pipe" ] && [ -p "$pipe" ];then
+      echo -e '\f' > "$pipe"
+      "${DIRECTORY}/preload" "$(cat "${DIRECTORY}/data/settings/App List Style")" "$prefix" > "$pipe" 2>/dev/null
     fi
   fi
 }
@@ -1598,6 +1571,9 @@ will_reinstall() { #return 0 if $1 app will be reinstalled during an update, oth
   if [ "$(app_status "$app")" != 'installed' ];then
     return 1
   fi
+  #it seems that the above code was added for speed alone https://github.com/Botspot/pi-apps/commit/d8bfc3f5fc9b42060bfbd68a11b24f66246d61bc
+  #commenting it out allows retrying failed app update where uninstall succeeds but install fails
+  #edit: uncommented it again because all uninstalled app refreshes were now being installed
   
   #detect which installation script exists - both for local install and for update directory
   local local_scriptname="$(script_name_cpu "$app")"
@@ -2919,16 +2895,19 @@ send_error_report() { #non-interactively send a Pi-Apps error log file to the Bo
   
 }
 
-diagnose_apps() { #Given a list of apps that failed to install/uninstall, loop through each error log, diagnose it, and provide a "Send report" button if applicable.
-  local failed_apps="$1"
+diagnose_apps() { #Given a list of action;app that failed to install/uninstall, loop through each error log, diagnose it, and provide a "Send report" button if applicable.
+  local failure_list="$1"
   local IFS=$'\n'
   
-  local num_lines="$(grep . <<<"$failed_apps" | wc -l)"
-  local i=1 #counter to track which failed_app in the list is current
-  local app
+  local num_lines="$(grep . <<<"$failure_list" | wc -l)"
+  local i=1 #counter to track which line in the list is current
+  local line
   local button
   
-  for app in $failed_apps ;do
+  for line in $failure_list ;do
+    local action="$(echo "$line" | awk -F';' '{print $1}')"
+    local app="$(echo "$line" | awk -F';' '{print $2}')"
+    
     local logfile="$(get_logfile "$app")"
     #given the app's logfile, categorize the error and set the error_type variable
     local diagnosis="$(log_diagnose "$logfile" "allowwrite")"
@@ -2958,7 +2937,7 @@ diagnose_apps() { #Given a list of apps that failed to install/uninstall, loop t
       text+=$'\n'"Error report cannot be sent because your system is unsupported."
     else
       #if all of the above checks evaluate to FALSE, then display the "Send report" button.
-      local send_button=(--button='Send report'!"${DIRECTORY}/icons/send-error-report.png":2)
+      local send_button=(--button='Send report'!"${DIRECTORY}/icons/send-error-report.png"!"Send this log file to Pi-Apps developers for review":2)
     fi
     
     #display support links, depending on if this was a package-app or a script-app
@@ -2981,7 +2960,7 @@ diagnose_apps() { #Given a list of apps that failed to install/uninstall, loop t
       error_caption="$(echo "$unsupported_message" | sed "s/\x1b\[[0-9;]*[a-zA-Z]//g")"$'\n'$'\n'"$error_caption"
     fi
     
-    #this dialog may be one in a series of failed_app dialogs. Name the window-close button accordingly.
+    #this dialog may be one in a series of diagnosis dialogs. Name the window-close button accordingly.
     if [ $i -lt $num_lines ];then
       local close_button=(--button="Next error!${DIRECTORY}/icons/forward.png":1)
     else
@@ -2993,12 +2972,16 @@ diagnose_apps() { #Given a list of apps that failed to install/uninstall, loop t
       --text="$text" --wrap --fontname=12 \
       --button='View log'!"${DIRECTORY}/icons/log-file.png"!"Review the output from when <b>$app</b> tried to $action.":"bash -c 'view_file "\""$logfile"\""'" \
       "${send_button[@]}" \
-      "${close_button[@]}"
+      --button="Retry!${DIRECTORY}/icons/refresh.png"!"Try $(echo "${action}ing" | sed 's/updateing/updating/g') $app again.":3 \
+      "${close_button[@]}" >/dev/null
     button="${PIPESTATUS[1]}"
     
     if [ $button == 2 ];then
       #send error log
       send_error_report "$logfile"
+    elif [ $button == 3 ];then
+      #retry button clicked, return new queue line(s) back to manage daemon
+      echo "$line"
     fi
     
     i=$((i+1))
diff --git a/updater b/updater
--- a/updater
+++ b/updater
@@ -312,6 +312,7 @@ list_updates_gui() { #input: updatable_apps and updatable_files variables, outpu
   
   local LIST=''
   local app
+  local num_new_apps=0 #track how many newly available apps there are. If there are a lot, the user may be unchecking them, misunderstanding pi-apps updates
   local compressed_update=''
   for app in $updatable_apps ;do #generate a yad list for every updatable app
     # get app tooltip
@@ -319,6 +320,7 @@ list_updates_gui() { #input: updatable_apps and updatable_files variables, outpu
     # if ${app} folder did not exist before and install-${arch}, install, or packages file is in the new update, then this is a "new app"
     # results in applications that only have support for a different architecture to show under the compressed update
     if [ ! -d "${DIRECTORY}/apps/${app}" ] && ( [ -f "${DIRECTORY}/update/pi-apps/apps/${app}/install-${arch}" ] || [ -f "${DIRECTORY}/update/pi-apps/apps/${app}/install" ] || [ -f "${DIRECTORY}/update/pi-apps/apps/${app}/packages" ] ); then
+      num_new_apps=$((num_new_apps+1))
       LIST+="TRUE
 ${DIRECTORY}/update/pi-apps/apps/${app}/icon-24.png
 $app (new app)
@@ -326,6 +328,7 @@ refresh-app:$app
 $line"$'\n'
     # if install-${arch} is in the new update and it was not installable on this system before, then this is a "new app".
     elif [ -f "${DIRECTORY}/update/pi-apps/apps/${app}/install-${arch}" ] && [ ! -f "${DIRECTORY}/apps/${app}/install-${arch}" ] && [ ! -f "${DIRECTORY}/apps/${app}/install" ] && [ ! -f "${DIRECTORY}/apps/${app}/packages" ]; then
+      num_new_apps=$((num_new_apps+1))
       LIST+="TRUE
 ${DIRECTORY}/update/pi-apps/apps/${app}/icon-24.png
 $app (new app)
@@ -333,6 +336,7 @@ refresh-app:$app
 $line"$'\n'
     # similar to the above. if install script is in the new update and it was not installable on this system before, then this is a "new app".
     elif [ -f "${DIRECTORY}/update/pi-apps/apps/${app}/install" ] && [ ! -f "${DIRECTORY}/apps/${app}/install-${arch}" ] && [ ! -f "${DIRECTORY}/apps/${app}/install" ] && [ ! -f "${DIRECTORY}/apps/${app}/packages" ]; then
+      num_new_apps=$((num_new_apps+1))
       LIST+="TRUE
 ${DIRECTORY}/update/pi-apps/apps/${app}/icon-24.png
 $app (new app)
@@ -408,11 +412,18 @@ Refreshes the Pi-Apps details for apps that do not need to be reinstalled for th
     exit 0
   fi
   
+  # if user has 5+ "new apps", they may be unchecking them all each time. Provide an explanatory message.
+  if [ $num_new_apps -ge 5 ];then
+    local update_hint_message="<b>Pro tip:</b> <u>please leave the "\""new apps"\"" checked.</u> This is just how Pi-Apps announces a new app that can be installed. Unless you have a very specific reason to keep an old app version, don't uncheck anything."
+  else
+    local update_hint_message="Uncheck an item to skip updating it."
+  fi
+  
   #Display a list of everything updatable
   output="$(echo "$LIST" | yad --class Pi-Apps --name "Pi-Apps" --center --title='Pi-Apps' \
     --window-icon="${DIRECTORY}/icons/logo.png" --width=310 --height=300 \
     --list --checklist --separator='\n' --print-column=4 --no-headers \
-    --text="Updates available:"$'\n'"Uncheck an item to skip updating it." \
+    --text="Updates available:"$'\n'"$update_hint_message" \
     --column=:CHK --column=:IMG --column=Name --column=ID:HD --column=tip:HD --tooltip-column=5 \
     --button='Cancel'!"${DIRECTORY}/icons/exit.png"!"Close without updating anything":1 \
     --button='Update now'!"${DIRECTORY}/icons/download.png":0 \
@@ -433,7 +444,7 @@ Refreshes the Pi-Apps details for apps that do not need to be reinstalled for th
   
 }
 
-update_app() { #first arg is app name
+update_app() { #given app name, uninstall it, update app folder, install it again (not to be used for app refreshes!)
   local app="$1"
   [ -z "$app" ] && error "update_app(): no app specified!"  
   status "Updating \e[1m${app}\e[0m\e[96m..."
@@ -441,41 +452,35 @@ update_app() { #first arg is app name
   
   #Set terminal title
   echo -ne "\e]0;Updating ${app}\a"
-
+  
   # check if update app folder exists before doing anything
   # it can happen that executing the updater from the pi-apps GUI the update folder is missing
   # if the user has no internet or internet issues the update folder will be removed due to the failed git pull and then wait in the loop for a new git clone
   # the GUI updater executes check_repo with the "fast" option so it skips updating the pi-apps update folder and obtains any previously determined updatable apps and files
   # if we do not check for this then apps will be removed, the older version moved to trash, and then the new version will fail to copy over since it does not exist
   if [ -d "${DIRECTORY}/update/pi-apps/apps/${app}" ]; then
-    local installback=no
-    if will_reinstall "$app";then
-      installback=yes
-      status "$app's install script has been updated. Reinstalling $app..."
-      #uninstall it
+    
+    status "$app's install script has been updated. Reinstalling $app..."
+    #uninstall it - if retrying an update with successful uninstall and failed install, don't uninstall again
+    if [ "$(app_status "$app")" != uninstalled ];then
       "${DIRECTORY}/manage" uninstall "$app" update #report to the app uninstall script that this is an uninstall for the purpose of updating by passing "update"
-      
-      #fix edge case: if app is installed but uninstall script doesn't exist somehow, then pretend app was uninstalled so that the reinstall later will happen noninteractively
-      if [ "$(app_status "$app")" == installed ];then
-        echo 'uninstalled' > "${DIRECTORY}/data/status/${app}"
-      fi
     fi
-
+    
+    #copy new version of the app folder to main pi-apps directory
     no_status=true refresh_app "$app"
     
-    failed=false
-    if [ "$installback" == 'yes' ];then
-      #install the app again
-      "${DIRECTORY}/manage" install "$app" update #report to the app install script that this is an install for the purpose of updating by passing "update"
-      if [ $? != 0 ]; then
-        failed=true
-      else
-        # click update link only if app is already installed and the update succeeded
-        shlink_link "$app" update &
-      fi
+    local failed=false
+
+    #install the app again
+    "${DIRECTORY}/manage" install "$app" update #report to the app install script that this is an install for the purpose of updating by passing "update"
+    if [ $? != 0 ]; then
+      failed=true
+    else
+      # click update link only if app is already installed and the update succeeded
+      shlink_link "$app" update &
     fi
   else
-    failed=true
+    local failed=true
   fi
   
   if [ "$failed" == 'true' ]; then
@@ -487,7 +492,7 @@ update_app() { #first arg is app name
   fi
 }
 
-refresh_app() { #first arg is app name
+refresh_app() { #update app folder only
   local app="$1"
   [ -z "$app" ] && error "refresh_app(): no app specified!"  
   [ "$no_status" != true ] && status -n "Refreshing \e[1m${app}\e[0m\e[96m... "
@@ -535,7 +540,11 @@ update_now_cli() { #input: updatable_files and updatable_apps variables
   done
   
   for app in $updatable_apps ;do
-    update_app "$app"
+    if will_reinstall "$app" ;then
+      update_app "$app"
+    else
+      refresh_app "$app"
+    fi
   done
   
   update_git
@@ -549,7 +558,11 @@ update_now_gui_apps() { # deprecated function that is only here so old updater s
   local failed_apps=""
   local IFS=$'\n'
   for app in $updatable_apps ;do
-    update_app "$app" || failed_apps+="$app"$'\n'
+    if will_reinstall "$app" ;then
+      update_app "$app" || failed_apps+="$app"$'\n'
+    else
+      refresh_app "$app" || failed_apps+="$app"$'\n'
+    fi
   done
   
   #Set terminal title
@@ -558,7 +571,7 @@ update_now_gui_apps() { # deprecated function that is only here so old updater s
   #load the app list now to reduce launch time
   refresh_app_list &
   
-  action=update diagnose_apps "$failed_apps"
+  diagnose_apps "$(echo "$failed_apps" | sed 's/^/update;/g')"
 }
 
 update_now_gui() { #input: updatable_files and updatable_apps variables
