move terminal_manage to api script
source api if terminal_manage is not found

on the initial update to the new changes, terminal_manage was moved from the `gui` to the `api` file so that it could be used in other scripts. the old updater did not source the new `api` file after updating to the new changes so `terminal_manage` will be unavailable if the `gui` goes to call it before the `gui` is restarted (like if a user tries to install/uninstall an app without restart the `gui`)

diff --git a/api b/api
--- a/api
+++ b/api
@@ -675,6 +675,60 @@ debian_ppa_installer() { #setup a PPA on a Debian distro. Arguments: ppa_name di
     apt_update || exit 1
   fi
 }
+
+terminal_manage() { #function to install/uninstall one app - uses a terminal and refreshes the app list
+  if [ "$1" == 'uninstall' ];then
+    action=uninstall
+  elif [ "$1" == 'install' ];then
+    action=install
+  else
+    error "terminal_manage(): Must specify an action: either 'install' or 'uninstall'"
+  fi
+  
+  app="$2" #one app name
+  
+  #To prevent multiple simultaneous manage instances, use the 'daemon' mode. This will create a queue of actions that are executed concurrently.
+  #The first daemon instance is the 'master' process. Subsequent processes will add the action to the queue and then exit.
+  #All output is generated by the 'master' daemon process. Subsequent processes shouldn't open a terminal, because the master one is already open.
+  if [ -f "${DIRECTORY}/data/manage-daemon/pid" ] && [ -f "/proc/$(cat "${DIRECTORY}/data/manage-daemon/pid")/status" ];then
+    #The 'master' daemon is already running. Avoid launching a second terminal.
+    "${DIRECTORY}/manage" daemon "$action $app"
+    
+  else
+    #in a terminal, first get the api functions, display the pi-apps logo, run the manage script, and refresh the app list if the $pipe variable is set
+    "${DIRECTORY}/etc/terminal-run" '
+      DIRECTORY="'"$DIRECTORY"'"
+      export geometry2="'"$geometry2"'"
+      source "${DIRECTORY}/api"
+      generate_logo
+      
+      refresh_list() { #Refresh the current list of apps in the event of a change
+        if [ ! -z "'"$pipe"'" ];then
+          echo -e "\f" > "'"$pipe"'"
+          "${DIRECTORY}/preload" yad "'"$prefix"'" > "'"$pipe"'" 2>/dev/null
+        fi
+      }
+      
+      "${DIRECTORY}/manage" daemon "'"$action $app"'"
+      
+      #refresh app list
+      refresh_list
+      
+      for i in {30..1} ;do
+        echo -en "You can close this window now. Auto-closing in $i seconds.\e[0K\r"
+        sleep 1
+      done
+      ' "Terminal Output"
+    
+    # Check if terminal-run failed to launch. GUI users don't see any terminal output if it fails (since there is no terminal open) so we need to prompt them with a GUI window
+    if [ "$?" != 0 ]; then
+      echo -e "Unable to open a terminal.\nDebug output below.\n$(DEBUG=1 "${DIRECTORY}/etc/terminal-run" 2>&1)" | yad --center --window-icon="${DIRECTORY}/icons/logo.png" \
+      --width=700 --height=300 --text-info --title="Error occured when calling terminal-run" \
+      --image="${DIRECTORY}/icons/error.png" --image-on-top --fontname=12 \
+      --button='OK'
+    fi
+  fi
+}
 #end of apt functions
 
 #flatpak functions
