Few fix to `api`

diff --git a/api b/api
--- a/api
+++ b/api
@@ -1367,13 +1367,21 @@ git_clone() { #silently clone a git repository but display the output if an erro
   
   [ -z "$url" ] && error "git_clone(): no repository URL specified."
   
-  local folder="$(pwd)/$(dirname "$url")"
+  local repo_name=$(basename "$url" | sed s/.git//g)
   
-  status -n "Downloading $(dirname "$url") repository... "
+  local folder="$(pwd)/$repo_name"
+  
+  status -n "Downloading $repo_name repository... "
   
   rm -rf "$folder"
-  local errors="$(git clone "$@" 2>&1)" || error "\nFailed to download $(dirname "$url") repository.\nErrors: $errors"
+  local errors="$(git clone "$@" 2>&1)" 
+  local exitcode=$?
+  #filter error messages
+  local errors="$(echo $errors | sed s/"Cloning into '$repo_name'..."//g)"
   
+  if [ "$exitcode" != 0 ]; then
+    error "\nFailed to download $repo_name repository.\nErrors: $errors"
+  fi
   status 'Done'
 }
 
@@ -1472,7 +1480,7 @@ wget() { #Intercept all wget commands. When possible, uses aria2c.
 
 chmod() { #say what is being made executable
   status "Making executable: $2"
-  command chmod "$@"
+  command chmod "$@" || command sudo chmod "$@"
   return $?
 }
 
