api: improve diagnose_apps and fix enable_module
Fixed a couple interface details in diagnose_apps and made all variables
local.
Moved the catch for other modprobe errors within the if statement so
that it only exits with an error if there actually was an error with
modprobe.

diff --git a/api b/api
--- a/api
+++ b/api
@@ -1995,28 +1995,31 @@ send_error_report() { #non-interactively send a Pi-Apps error log file to the Bo
 
 diagnose_apps() { #Given a list of apps that failed to install/uninstall, loop through each error log, diagnose it, and provide a "Send report" button if applicable.
   local failed_apps="$1"
+  local IFS=$'\n'
   
-  local num_lines="$(wc -l <<<"$failed_apps")"
+  local num_lines="$(grep . <<<"$failed_apps" | wc -l)"
   local i=1 #counter to track which failed_app in the list is current
+  local app
+  local button
   
   for app in $failed_apps ;do
-    logfile="$(get_logfile "$app")"
+    local logfile="$(get_logfile "$app")"
     #given the app's logfile, categorize the error and set the error_type variable
-    diagnosis="$(log_diagnose "$logfile")"
+    local diagnosis="$(log_diagnose "$logfile")"
     
-    error_type="$(echo "$diagnosis" | head -n1)" #first line of diagnosis is the type of error
-    error_caption="$(echo "$diagnosis" | tail -n +2)" #subsequent lines of diagnosis are caption(s)
+    local error_type="$(echo "$diagnosis" | head -n1)" #first line of diagnosis is the type of error
+    local error_caption="$(echo "$diagnosis" | tail -n +2)" #subsequent lines of diagnosis are caption(s)
     
     #set the window-text
     if [ "$error_type" == unknown ];then
-      text="<b>${app^}</b> failed to $action for an <b>unknown</b> reason."
+      local text="<b>${app^}</b> failed to $action for an <b>unknown</b> reason."
     else
-      text="<b>${app^}</b> failed to $action because Pi-Apps encountered $([[ "$error_type" == [aeiou]* ]] && echo an || echo a) <b>$error_type</b> error."
+      local text="<b>${app^}</b> failed to $action because Pi-Apps encountered $([[ "$error_type" == [aeiou]* ]] && echo an || echo a) <b>$error_type</b> error."
     fi
     
     #if the error_type is NOT system, internet, or package, AND the app exists in the official Pi-Apps repository, AND the app-script has not been modified, AND the system setup is supported, AND the app is not a package-app, then enable the "Send report button"
     if [ "$(app_type "$app")" == package ];then
-      text+=$'\n'"Error report cannot be sent because this \"app\" is really just a shortcut to $action a Debian package. It's not a problem that Pi-Apps can fix."
+      text+=$'\n'"Error report cannot be sent because this \"app\" is really just a shortcut to install a Debian package. It's not a problem that Pi-Apps can fix."
     elif [[ "$error_type" =~ ^(system|internet|package)$ ]];then
       text+=$'\n'"Error report cannot be sent because this is not an issue with Pi-Apps."
     elif ! list_apps online | grep -q "$app" ;then
@@ -2029,7 +2032,7 @@ diagnose_apps() { #Given a list of apps that failed to install/uninstall, loop t
       text+=$'\n'"Error report cannot be sent because your system is unsupported."
     else
       #if all of the above checks evaluate to FALSE, then display the "Send report" button.
-      send_button=(--button='Send report'!"${DIRECTORY}/icons/send-error-report.png":2)
+      local send_button=(--button='Send report'!"${DIRECTORY}/icons/send-error-report.png":2)
     fi
     
     #display support links, depending on if this was a package-app or a script-app
@@ -2049,12 +2052,12 @@ diagnose_apps() { #Given a list of apps that failed to install/uninstall, loop t
     
     #this dialog may be one in a series of failed_app dialogs. Name the window-close button accordingly.
     if [ $i -lt $num_lines ];then
-      close_button=(--button="Next error!${DIRECTORY}/icons/forward.png":1)
+      local close_button=(--button="Next error!${DIRECTORY}/icons/forward.png":1)
     else
-      close_button=(--button="Close!${DIRECTORY}/icons/exit.png":1)
+      local close_button=(--button="Close!${DIRECTORY}/icons/exit.png":1)
     fi
     
-    echo "$error_caption" | yad "${yadflags[@]}" --class Pi-Apps --name "Pi Apps" --text-info --width=700 --height=300 --title="Error occured when $(echo "${action}" | sed 's/updateing/updating/g') $app ($i/$num_lines)" \
+    echo "$error_caption" | yad "${yadflags[@]}" --class Pi-Apps --name "Pi Apps" --text-info --width=700 --height=300 --title="Error occured when $(echo "${action}ing" | sed 's/updateing/updating/g') $app ($i/$num_lines)" \
       --image="${DIRECTORY}/icons/error.png" --image-on-top \
       --text="$text" --wrap --fontname=12 \
       --button='View log'!"${DIRECTORY}/icons/log-file.png"!"Review the output from when <b>$app</b> tried to $action.":"bash -c 'view_file "\""$logfile"\""'" \
@@ -2475,10 +2478,10 @@ enable_module() { #Permanent equivalent to modprobe, this will load the module o
       if [ ! -d "/lib/modules/$(uname -r)" ];then
         error "\nUser error: Failed to load the '$module' kernel module because you upgraded the kernel and have not rebooted yet.
 Please reboot to load the new kernel, then try again."
+      else
+        #other modprobe error: exit now and display modprobe output
+        error "$errors"
       fi
-    else
-      #other modprobe error: exit now and display modprobe output
-      error "$errors"
     fi
   fi
   
