api and more ram: better handle kernel upgrades preventing modprobe

diff --git a/api b/api
--- a/api
+++ b/api
@@ -2425,7 +2425,17 @@ enable_module() { #Permanent equivalent to modprobe, this will load the module o
   
   #load the module now if not already loaded
   if ! lsmod | awk '{print $1}' | grep -qxF "$module" ;then
-    sudo modprobe "$module" || exit 1
+    errors="$(sudo modprobe "$module" 2>&1)"
+    if [ $? != 0 ];then
+      #if modprobe fails, the module may be missing because user upgraded the kernel and has not rebooted yet.
+      if [ ! -d "/lib/modules/$(uname -r)" ];then
+        error "\nUser error: Failed to load the '$module' kernel module because you upgraded the kernel and have not rebooted yet.
+Please reboot to load the new kernel, then try again."
+      fi
+    else
+      #other modprobe error: exit now and display modprobe output
+      error "$errors"
+    fi
   fi
   
   #make it load on boot
diff --git a/apps/More RAM/install b/apps/More RAM/install
--- a/apps/More RAM/install
+++ b/apps/More RAM/install
@@ -84,8 +84,20 @@ elif ! command -v swapoff >/dev/null ;then
   error "\nUser error: Incompatible because the 'swapoff' command is missing on your system."
 elif ! command -v modprobe >/dev/null ;then
   error "\nUser error: Incompatible because the 'modprobe' command is missing on your system."
-elif ! sudo modprobe zram &>/dev/null ;then
-  error "\nUser error: Incompatible because the 'zram' kernel module is missing on your system."
+fi
+
+#load zram module
+if false && command -v enable_module >/dev/null ;then
+  enable_module zram || exit 1
+elif ! lsmod | awk '{print $1}' | grep -qxF zram ;then
+  if ! sudo modprobe zram &>/dev/null ;then
+    if [ ! -d "/lib/modules/$(uname -r)" ];then
+        error "\nUser error: Failed to load the 'zram' kernel module because you upgraded the kernel and have not rebooted yet.
+Please reboot to load the new kernel, then try again."
+    else
+      error "\nUser error: Incompatible because the 'zram' kernel module is missing on your system."
+    fi
+  fi
 fi
 status_green "Done"
 
@@ -131,9 +143,11 @@ elif [ "$1" == storage-on ]; then
 fi
 
 # Load zram module
-if ! modprobe zram ;then
-  echo "Failed to load zram kernel module"
-  exit 1
+if ! lsmod | awk "{print $1}" | grep -qxF zram ;then
+  if ! modprobe zram ;then
+    echo "Failed to load zram kernel module"
+    exit 1
+  fi
 fi
 
 # disable all zram devices
