api: add `pipx_install` and `pipx_uninstall`
installs and uninstalls python packages with pipx as well as installs pipx itself

diff --git a/api b/api
--- a/api
+++ b/api
@@ -732,6 +732,35 @@ adoptium_installer() {
   fi
 }
 
+pipx_install() {
+  # install pipx keeping in mind distro issues
+  # pipx <= 0.16.1 is compatible with 3.7 <= python3 < 3.9
+  # pipx >= 0.16.1 is compatible with python3 >= 3.7
+  # some distros lack pipx entirely
+  # some distros (raspbian bullseye specifically) have incompatible combinations of pipx (0.12.3) and python3 (3.9) versions, necessitating pipx to be installed/upgraded from pip
+  if package_available pipx && package_is_new_enough pipx 0.16.1 ;then
+    install_packages pipx python3-venv || exit 1
+  elif package_available pipx && ! package_is_new_enough pipx 0.16.1 && ! package_is_new_enough python3 3.9 ;then
+    install_packages pipx python3-venv || exit 1
+  elif package_available pipx && ! package_is_new_enough pipx 0.16.1 && package_is_new_enough python3 3.9 ;then
+    install_packages python3-venv || exit 1
+    sudo -H python3 -m pip install --upgrade pipx || exit 1
+  elif package_is_new_enough python3 3.7 ; then
+    install_packages python3-venv || exit 1
+    sudo -H python3 -m pip install --upgrade pipx || exit 1
+  elif package_available python3.8 ;then
+    install_packages python3.8 python3.8-venv || exit 1
+    sudo -H python3.8 -m pip install --upgrade pipx || exit 1
+  else
+    error "pipx is not available so cannot install powerline-shell to python venv"
+  fi
+  sudo PIPX_HOME=/usr/local/pipx PIPX_BIN_DIR=/usr/local/bin pipx install "$@" || error "Failed to install $@ with pipx"
+}
+
+pipx_uninstall() {
+  sudo PIPX_HOME=/usr/local/pipx PIPX_BIN_DIR=/usr/local/bin pipx uninstall "$@" || error "Failed to uninstall $@ with pipx"
+}
+
 terminal_manage() { # wrapper for the original terminal_manage function to terminal_mange_multi
   action="$1"
   app="$2" #one app name
