Categories added to Pi-Apps!

diff --git a/gui b/gui
--- a/gui
+++ b/gui
@@ -17,20 +17,17 @@ if [ ! -z "$1" ];then
 fi
 
 #hide Chromium Widevine & Back to Chromium v78 on existing TwisterOS installs
-(if [ -f /usr/local/bin/twistver ] && [ -z "$(cat "${DIRECTORY}/data/hidelist" | grep "Lightpad")" ];then
+if [ -f "${DIRECTORY}/data/hidelist" ] || [ ! -d "${DIRECTORY}/data/categories" ];then
   "${DIRECTORY}/install"
+  rm "${DIRECTORY}/data/hidelist"
 fi
-#prettify hidelist file
-hidelist="$(cat "${DIRECTORY}/data/hidelist" | sort | uniq | sed '/^[[:space:]]*$/d')"
-echo "$hidelist" > "${DIRECTORY}/data/hidelist"
-) &
 
 #rename 'Vivaldi web browser' to Vivaldi
-(find "$DIRECTORY" -name 'Vivaldi '* | while read f; do mv -v "$f" "$(echo "${f}" | sed 's/ web browser//g')"; done
-if [ ! -z "$(cat "$DIRECTORY/data/preload/LIST" | grep 'Vivaldi web browser')" ];then
-  rm -rf "$DIRECTORY/data/preload"
-fi
-) &
+#(find "$DIRECTORY" -name 'Vivaldi '* | while read f; do mv -v "$f" "$(echo "${f}" | sed 's/ web browser//g')"; done
+#if [ ! -z "$(cat "$DIRECTORY/data/preload/LIST" | grep 'Vivaldi web browser')" ];then
+#  rm -rf "$DIRECTORY/data/preload"
+#fi
+#) &
 
 (if cat ~/.config/autostart/pi-apps-updater.desktop | grep -q installedonly ;then
   "${DIRECTORY}/install"
@@ -93,8 +90,10 @@ guimode="$(cat "${DIRECTORY}/data/settings/App List Style")"
 [ -z "$guimode" ] && guimode=yad
 #mode=yad
 
+prefix=''
+
 while true;do
-  LIST="$("${DIRECTORY}/preload" $guimode)"
+  LIST="$("${DIRECTORY}/preload" $guimode $prefix)"
   #LIST="$(cat "${DIRECTORY}/data/preload/LIST")"
   #echo "$LIST"
   
@@ -103,20 +102,34 @@ while true;do
   
   while [ -z "$output" ];do
     
-    if [ $guimode == yad ];then
-      output="$(echo -e "$LIST" | yad --center --title='Pi-Apps' --width=310 --height=400 --no-headers \
-        --text="$motd" --image="${DIRECTORY}/icons/logo-64.png" --image-on-top \
+    if [ "$guimode" == yad ];then
+      if [ -z "$prefix" ];then
+        buttons=("--button=Install!${DIRECTORY}/icons/install.png:4" \
+        "--button=Uninstall!${DIRECTORY}/icons/uninstall.png:2" \
+        "--button=Details!${DIRECTORY}/icons/info.png!View more about the selected software:0" )
+      else
+        buttons=("--button=!${DIRECTORY}/icons/back.png!Back:3" \
+        "--button=!${DIRECTORY}/icons/install.png!Install:4" \
+        "--button=!${DIRECTORY}/icons/uninstall.png!Uninstall:2" \
+        "--button=!${DIRECTORY}/icons/info.png!Details:0" )
+      fi
+      
+      output="$(echo -e "$LIST" | yad --center --title='Pi-Apps'"$([ ! -z "$prefix" ] && echo ": $(echo "$prefix" | tr '/' '>')")" --width=310 --height=400 --no-headers \
+        --text="$([ -z "$prefix" ] && echo "$motd" || echo "Viewing $(echo "$prefix" | tr '/' '>') category")" --image="${DIRECTORY}/icons/logo-64.png" --image-on-top \
         --list --multiple --separator='\n' --window-icon="${DIRECTORY}/icons/logo.png" \
-        --column=:IMG --column=:IMG --column=Name --column=tip:HD --print-column=3 --tooltip-column=4 \
-        --button=Install!"${DIRECTORY}/icons/install.png":4 \
-        --button=Uninstall!"${DIRECTORY}/icons/uninstall.png":2 \
-        --button=Details!"${DIRECTORY}/icons/info.png"!'View more about the selected software:0' \
-        )"
+        --column=:IMG --column=:IMG --column=Name --column=Sysname:HD --column=tip:HD \
+        --print-column=4 --tooltip-column=5 \
+        "${buttons[@]}" \
+      )"
       
       button=$? #get exit code to determine which button was pressed
       echo "Button: ${button}"
       if [ $button -eq 252 ];then #if window manager x was pressed
         exit 0
+      fi
+      if [ "$button" == 3 ];then
+        #back button
+        break
       fi
       if [ -z "$output" ];then
         echo "output variable empty!"
@@ -126,7 +139,8 @@ while true;do
     (You didn"\'"t select an App)" \
           --button=OK:0
       fi
-    elif [ $guimode == xlunch ];then
+      
+    elif [ "$guimode" == xlunch ];then
       if [ ! -d "${DIRECTORY}/xlunch" ] || [ ! -f /usr/bin/xlunch ];then
         sudo rm -rf /usr/bin/xlunch "$DIRECTORY/xlunch" 2>/dev/null
         sudo apt install -y libimlib2-dev libx11-dev
@@ -141,33 +155,54 @@ while true;do
           error "xlunch should be installed now, but /usr/bin/xlunch does not exist!"
         fi
       fi
+      #xlunch compiled
+      
       screen_width="$(xdpyinfo | grep 'dimensions:' | tr 'x' '\n' | tr ' ' '\n' | sed -n 7p)"
       screen_height="$(xdpyinfo | grep 'dimensions:' | tr 'x' '\n' | tr ' ' '\n' | sed -n 8p)"
       height=700
       width=800
       xposition=$(((screen_width/2)-(width/2)))
       yposition=$(((screen_height/2)-(height/2)))
+      
       if false;then
         scrot -a "$((xposition+1)),$((yposition+33)),${width},${height}" blur.png #blur_init.png
         convert -blur 10x5 ~/blur.png ~/blur.png
       fi
+      
+      if [ ! -z "$prefix" ];then
+        echo "Adding back button to xlunch..."
+        LIST="Back;${DIRECTORY}/icons/back-64.png;./
+$LIST"
+        LIST="$(echo "$LIST" | grep .)"
+      fi
+      echo "$LIST"
+      
+      if [ -z "$prefix" ];then
+        searchbox="Search: "
+      else
+        searchbox="Viewing $(echo "$prefix" | tr '/' '>'). Search: "
+      fi
+      
       output="$(echo -e "$LIST" | xlunch -WoCS -s 64 --bc 000000A0 --tc ffffffff --pc 6060ffff --hc 60606010 \
-        -p "Search: " -a -c 2 --title "Pi-Apps: Raspberry Pi app store" \
+        -p "$searchbox" -a -c 2 --title "Pi-Apps: Raspberry Pi app store" \
         --icon "${DIRECTORY}/icons/logo.png" --scrollbarcolor ffffff40 --scrollindicatorcolor 0000ff80\
         --width $width --height $height --xposition $xposition --yposition $yposition \
         --button "${DIRECTORY}/icons/logo-128.png;;$((($width/2)-(128/2))),0;"
-        -g ~/blur.png)"
+        #-g ~/blur.png
+        )"
       button=0
       
       if [ -z "$output" ];then
-        exit 0
+        error "xlunch did not report any selected apps!"
       fi
+    else
+      error "Unrecognized app list style '$guimode'!"
     fi
     output="$(echo "$output" | sed '/^$/d')"
     echo "Output: ${output}EOO"
     
-    
   done
+  #output variable populated
   
   case $button in
 
@@ -175,121 +210,152 @@ while true;do
       echo "User exited."
       exit 0
       ;;
+    3)
+      echo "Back"
+      prefix="$(dirname "$prefix" | tr -d '.')"
+      ;;
     0)
       echo "Details"
-      output="$(echo "$output" | head -n1)"
-      if [ ! -z "$(cat "${DIRECTORY}/data/installed-packages/${output}")" ];then
-        installedpackages="
-This app installed these packages: $(cat "${DIRECTORY}/data/installed-packages/${output}" | sort | uniq | tr '\n' ' ')"
+      if echo "$output" | grep -q '/' ;then
+        #folder
+        if [ "$output" == './' ];then
+          echo "Back"
+          prefix="$(dirname "$prefix" | tr -d '.')"
+        else
+          prefix="$prefix/$output"
+          prefix="${prefix::-1}"
+          prefix="$(echo "$prefix" | sed 's+^/++')"
+        fi
+        echo "Prefix is $prefix"
+        output=''
       else
-        installedpackages=''
-      fi
-      
-      description="$(cat "${DIRECTORY}/apps/${output}/description" || echo 'Description unavailable')"
-      
-      text="$(echo "$(cat "${DIRECTORY}/apps/${output}/description" || echo "Description unavailable")" | head -n1)
+        #app
+        
+        output="$(echo "$output" | head -n1)"
+        if [ ! -z "$(cat "${DIRECTORY}/data/installed-packages/${output}")" ];then
+          installedpackages="
+This app installed these packages: $(cat "${DIRECTORY}/data/installed-packages/${output}" | sort | uniq | tr '\n' ' ')"
+        else
+          installedpackages=''
+        fi
+        
+        description="$(cat "${DIRECTORY}/apps/${output}/description" || echo 'Description unavailable')"
+        
+        text="$(echo "$(cat "${DIRECTORY}/apps/${output}/description" || echo "Description unavailable")" | head -n1)
 Current status: $(cat "${DIRECTORY}/data/status/${output}" || echo 'Uninstalled')
 Website: $(cat "${DIRECTORY}/apps/${output}/website" || echo 'unavailable')
 $(echo "$description" | grep -v "$(echo "$description" | head -n1)")
 $installedpackages"
-      
-      #if already installed then no need to provide install button. And vice versa.
-      whichbutton="$(
-      if [ "$(cat "${DIRECTORY}/data/settings/Show Edit button")" == 'Yes' ];then
-        echo "--button=Edit!${DIRECTORY}/icons/edit.png:10"
-      fi
-      if [ ! -f "${DIRECTORY}/data/status/${output}" ];then
-        #Taking a chance here. If status file is nonexistent, assume uninstalled.
-        echo "--button=Install!${DIRECTORY}/icons/install.png:4"
-      elif [ "$(cat "${DIRECTORY}/data/status/${output}")" == 'installed' ];then
-        echo "--button=Uninstall!${DIRECTORY}/icons/uninstall.png:2"
-      elif [ "$(cat "${DIRECTORY}/data/status/${output}")" == 'uninstalled' ];then
-        echo "--button=Install!${DIRECTORY}/icons/install.png:4"
-      else
-        #if status is corrupted or unknown, then show both buttons
-        echo "--button=Uninstall!${DIRECTORY}/icons/uninstall.png:2 --button=Install!${DIRECTORY}/icons/install.png:4"
-      fi
-      )"
-      
-      echo "$text" | yad --text-info --fontname=12 --wrap --show-uri \
-        --image="${DIRECTORY}/apps/${output}/icon-64.png" --image-on-top \
-        --title="Details of ${output}" --window-icon="${DIRECTORY}/icons/logo.png" --center --width=700 --height=300 \
-        $whichbutton \
-        --button=''!"${DIRECTORY}/icons/up.png"!'View previous App':6 \
-        --button=''!"${DIRECTORY}/icons/down.png"!'View next App':8 \
-        --button=Back!"${DIRECTORY}/icons/back.png":0
-      button=$? #get exit code to determine which button was pressed
-      echo "Button: ${button}"
-      
-      if [ $button == 0 ];then
-        echo 'Back' #do nothing, as user requested to go back
-        #clear app var
-        output=''
-      elif [ $button == 4 ];then
-        app="$output"
-        install "$app"
-      elif [ $button == 2 ];then
-        app="$output"
-        uninstall "$app"
-      elif [ $button == 6 ];then
-        echo 'previous app'
         
-        #convert $output into number, then subtract 1 from it
-        
-        lsoutput="$(echo "$(ls "${DIRECTORY}/apps")" | grep -vxE "$(cat "${DIRECTORY}/data/hidelist" | tr '\n' '|')")"
-        
-        number="$(echo "$lsoutput" | grep -nx "$output" | cut -f1 -d: )"
-        
-        lastline="$(echo "$lsoutput" | wc -l)"
-        
-        if [ $(($number - 1)) -lt '1' ];then
-          newnumber=$lastline
-        else
-          newnumber=$(($number - 1))
+        #if already installed then no need to provide install button. And vice versa.
+        whichbutton="$(
+        if [ "$(cat "${DIRECTORY}/data/settings/Show Edit button")" == 'Yes' ];then
+          echo "--button=Edit!${DIRECTORY}/icons/edit.png:10"
         fi
-        
-        output="$(echo "$lsoutput" | sed -n "${newnumber}p")"
-        
-        echo "Line number was ${number}, but now is ${newnumber}. Name is ${output}."
-        
-      elif [ $button == 8 ];then
-        echo 'next app'
-        
-        #convert $output into number, then add 1 to it
-        
-        lsoutput="$(echo "$(ls "${DIRECTORY}/apps")" | grep -vxE "$(cat "${DIRECTORY}/data/hidelist" | tr '\n' '|')")"
-        
-        number="$(echo "$lsoutput" | grep -nx "$output" | cut -f1 -d: )"
-        
-        echo "Line number was ${number}, but now is ${newnumber}. Name is ${output}."
-        
-        lastline="$(echo "$lsoutput" | wc -l)"
-        
-        if [ $(($number + 1)) -gt $lastline ];then
-          newnumber=1
+        if [ ! -f "${DIRECTORY}/data/status/${output}" ];then
+          #Taking a chance here. If status file is nonexistent, assume uninstalled.
+          echo "--button=Install!${DIRECTORY}/icons/install.png:4"
+        elif [ "$(cat "${DIRECTORY}/data/status/${output}")" == 'installed' ];then
+          echo "--button=Uninstall!${DIRECTORY}/icons/uninstall.png:2"
+        elif [ "$(cat "${DIRECTORY}/data/status/${output}")" == 'uninstalled' ];then
+          echo "--button=Install!${DIRECTORY}/icons/install.png:4"
         else
-          newnumber=$(($number + 1))
+          #if status is corrupted or unknown, then show both buttons
+          echo "--button=Uninstall!${DIRECTORY}/icons/uninstall.png:2 --button=Install!${DIRECTORY}/icons/install.png:4"
         fi
+        )"
         
-        output="$(echo "$lsoutput" | sed -n "${newnumber}p")"
+        echo "$text" | yad --text-info --fontname=12 --wrap --show-uri \
+          --image="${DIRECTORY}/apps/${output}/icon-64.png" --image-on-top \
+          --title="Details of ${output}" --window-icon="${DIRECTORY}/icons/logo.png" --center --width=700 --height=300 \
+          --button=Back!"${DIRECTORY}/icons/back.png":0 \
+          --button=''!"${DIRECTORY}/icons/up.png"!'View previous App':6 \
+          --button=''!"${DIRECTORY}/icons/down.png"!'View next App':8 \
+          $whichbutton
+        button=$? #get exit code to determine which button was pressed
+        echo "Button: ${button}"
         
-        echo "Line number was ${number}, but now is ${newnumber}. Name is ${output}."
-      elif [ $button == 10 ];then
-        echo "edit $output"
-        "${DIRECTORY}/createapp" "$output"
-      else
-        echo 'unknown button. Exiting now.'
-        exit 0
+        if [ $button == 0 ];then
+          echo 'Back' #do nothing, as user requested to go back
+          #clear app var
+          output=''
+        elif [ $button == 4 ];then
+          app="$output"
+          install "$app"
+        elif [ $button == 2 ];then
+          app="$output"
+          uninstall "$app"
+        elif [ $button == 6 ] || [ $button == 8 ];then
+          #previous or next app clicked
+          lsoutput="$(echo "$LIST" | grep -v '/' | grep -v '(' | grep -v *'\n App folder' | awk -F ';' '{print $NF}' | uniq)"
+          echo "$lsoutput"
+          
+          if [ $button == 6 ];then
+            echo 'previous app'
+            
+            #convert $output into number, then subtract 1 from it
+            number="$(echo "$lsoutput" | grep -nx "$output" | cut -f1 -d: )"
+            
+            lastline="$(echo "$lsoutput" | wc -l)"
+            
+            if [ $(($number - 1)) -lt '1' ];then
+              newnumber=$lastline
+            else
+              newnumber=$(($number - 1))
+            fi
+            
+            output="$(echo "$lsoutput" | sed -n "${newnumber}p")"
+            
+            echo "Line number was ${number}, but now is ${newnumber}. Name is ${output}."
+          elif [ $button == 8 ];then
+            echo 'next app'
+            
+            #convert $output into number, then add 1 to it
+            number="$(echo "$lsoutput" | grep -nx "$output" | cut -f1 -d: )"
+            
+            echo "Line number was ${number}, but now is ${newnumber}. Name is ${output}."
+            
+            lastline="$(echo "$lsoutput" | wc -l)"
+            
+            if [ $(($number + 1)) -gt $lastline ];then
+              newnumber=1
+            else
+              newnumber=$(($number + 1))
+            fi
+            
+            output="$(echo "$lsoutput" | sed -n "${newnumber}p")"
+            
+            echo "Line number was ${number}, but now is ${newnumber}. Name is ${output}."
+          fi
+        elif [ $button == 10 ];then
+          echo "edit $output"
+          "${DIRECTORY}/createapp" "$output"
+        else
+          echo 'unknown button. Exiting now.'
+          exit 0
+        fi
       fi
       ;;
     2)
-      uninstall "$output"
-      #clear output var to prompt main window to open next
+      #uninstal
+      if ! echo "$output" | grep -q '/' ;then
+        uninstall "$output"
+        #clear output var to prompt main window to open next
+      else
+        motd="Sorry, you can"\'"t uninstall folders."
+        prefix=''
+      fi
       output=''
       ;;
     4)
-      install "$output"
-      #clear output var to prompt main window to open next
+      #install
+      if ! echo "$output" | grep -q '/' ;then
+        install "$output"
+        #clear output var to prompt main window to open next
+      else
+        motd="Sorry, you can"\'"t install folders."
+        prefix=''
+      fi
       output=''
       ;;
     *)
diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,7 +7,7 @@ function error {
 
 DIRECTORY="$(readlink -f "$(dirname "$0")")"
 
-if [ -z "$(dpkg-query -W --showformat='${Status}\n' yad 2>/dev/null | grep "install ok installed")" ];then
+if ! command -v yad >/dev/null;then
   echo -n "YAD is required but not installed. Install now? [Y/n] "
   read answer
   if [ "$answer" == n ];then
@@ -18,6 +18,8 @@ if [ -z "$(dpkg-query -W --showformat='${Status}\n' yad 2>/dev/null | grep "inst
     sudo apt install -y yad
   elif [ -f /usr/bin/pacman ];then
     sudo pacman -S yad
+  else
+    error "Failed to find any package manager"
   fi
 fi
 
@@ -36,7 +38,7 @@ Type=Application
 Categories=Utility;" > ~/.local/share/applications/pi-apps.desktop
 
 echo "Adding Desktop shortcut..."
-cp -f ${HOME}/.local/share/applications/pi-apps.desktop ${HOME}/Desktop/pi-apps.desktop
+cp -f ~/.local/share/applications/pi-apps.desktop ~/Desktop/pi-apps.desktop
 
 echo "Creating Settings menu button..."
 echo "[Desktop Entry]
@@ -62,7 +64,7 @@ NoDisplay=false" > ~/.config/autostart/pi-apps-updater.desktop
 
 mkdir -p "${DIRECTORY}/data"
 cd "${DIRECTORY}/data"
-mkdir -p installed-packages preload settings status update-status
+mkdir -p installed-packages preload settings status update-status categories
 cd $HOME
 
 #hide template file by default
@@ -70,7 +72,9 @@ echo "template" > "${DIRECTORY}/data/hidelist"
 
 #hide duplicates if running in twisteros
 if [ -f /usr/local/bin/twistver ];then
-  echo "BalenaEtcher
+  PREIFS="$IFS"
+  IFS=$'\n'
+  apps="BalenaEtcher
 Chromium Media Edition
 CommanderPi
 Box86
@@ -78,10 +82,15 @@ Discord
 piKiss
 Retropie
 Scrcpy
+Steam
 Windows 10 Theme
 Chromium Widevine
 Back to Chromium v78
-Lightpad" >> "${DIRECTORY}/data/hidelist"
+Lightpad"
+  for app in $apps ;do
+    "${DIRECTORY}/etc/categoryedit" "$app" 'hidden'
+  done
+  echo "Finished hiding apps on TwisterOS."
 fi
 
 echo "Creating settings if they don"\'"t exist..."
diff --git a/preload b/preload
--- a/preload
+++ b/preload
@@ -26,13 +26,21 @@ if [ -z "$format" ];then
   format=yad
 fi
 
+#specifies an app folder(s)
+prefix="$2"
+
+timestampfile="${DIRECTORY}/data/preload/timestamps-$(echo "$prefix" | tr -d '/')"
+listfile="${DIRECTORY}/data/preload/LIST-$(echo "$prefix" | tr -d '/')"
+
 mkdir -p "${DIRECTORY}/data/preload"
 
 mktimestamps() {
   #these directories are checked for changes
   checkdirs="${DIRECTORY}/apps
 ${DIRECTORY}/data/settings
-${DIRECTORY}/data/status"
+${DIRECTORY}/data/status
+${DIRECTORY}/data/categories
+${DIRECTORY}/etc"
   
   timestamps=''
   PREIFS="$IFS"
@@ -45,16 +53,19 @@ $(stat -c %Y "${dir}/$(ls -t "$dir" | head -n1)")"
   done
   IFS="$PREIFS"
   #remove first empty newline
-  timestamps="${timestamps:1}"
+  timestamps="$prefix
+$format
+$(ls -1q "${DIRECTORY}/apps"/* | wc -l)
+${timestamps:1}"
 }
 
 reloadlist=0
 
-if [ -f "${DIRECTORY}/data/preload/timestamps" ];then
+if [ -f "$timestampfile" ];then
   #get modified timestamps for directories
   mktimestamps
   
-  if [ "$timestamps" == "$(cat "${DIRECTORY}/data/preload/timestamps")" ];then
+  if [ "$timestamps" == "$(cat "$timestampfile")" ];then
     #if current timestamps and saved timestamps match, then don't reload the list
     reloadlist=0
     echo "Timestamps match." 1>&2
@@ -68,17 +79,75 @@ else
   reloadlist=1
 fi
 
-if [ ! -f "${DIRECTORY}/data/preload/LIST" ];then
+if [ ! -f "$listfile" ] || [ -z "$(cat "$listfile")" ];then
   echo "list file does not exist." 1>&2
   reloadlist=1
 fi
 
+#this ensures that all apps & categories stay preloaded.
+(sleep 5;"${DIRECTORY}/etc/preload-daemon" "$format") 1>&2 &
+
 if [ $reloadlist == 1 ];then
   echo "Generating list..." 1>&2
-  #get list of apps ----------------------------------- and exclude apps mentioned in hidelist file
-  APPS="$(echo "$(ls "${DIRECTORY}/apps")" | grep -vxE "$(cat "${DIRECTORY}/data/hidelist" | tr '\n' '|')")"
-  #APPS="$(echo "$(ls "${DIRECTORY}/apps")")"
   
+  APPS="$(ls "${DIRECTORY}/apps")"
+  structure="$(cat "${DIRECTORY}/data/categories/structure")"
+  
+  #generate a virtual file system with apps in folders represented as subdirectories
+  PREIFS="$IFS"
+  IFS=$'\n'
+  vfiles=''
+  for app in $APPS
+  do
+    line="$(echo "$structure" | grep "$app"'|' | awk -F'|' '{print $2 "/" $1}')"
+    
+    if [ -z "$line" ];then
+      echo "WARNING: $app app not found in $(echo "${DIRECTORY}/data/categories/structure" | sed 's+/home/pi+~+g') file." 1>&2
+      if [ -z "$onlinestructurefile" ];then
+        onlinestructurefile="$(wget -qO- 'https://raw.githubusercontent.com/Botspot/pi-apps/master/data/categories/structure')"
+      fi
+      onlinematch="$(echo "$onlinestructurefile" | grep "$app"'|')"
+      if [ ! -z "$onlinematch" ];then
+        echo -e "Located the default category for the $app app from github.\nIt is: ${onlinematch}EOO" 1>&2
+        echo "$onlinematch" >> "${DIRECTORY}/data/categories/structure"
+      else
+        echo -e "Could not find the default category for the $app app." 1>&2
+        echo "${app}|" >> "${DIRECTORY}/data/categories/structure"
+      fi
+      #refresh structure file
+      structure="$(cat "${DIRECTORY}/data/categories/structure")"
+      line="$(echo "$structure" | grep "$app"'|' | awk -F'|' '{print $2 "/" $1}')"
+    fi
+    
+    vfiles="$vfiles
+$line"
+  done
+  IFS="$PREIFS"
+  vfiles="$(echo "$vfiles" | grep . | sed 's+^/++g' | sort | uniq)"
+  #echo "$vfiles"
+  
+  if [ ! -z "$prefix" ];then
+    echo "Showing apps within $prefix/" 1>&2
+    
+    vfiles="$(echo "$vfiles" | grep "$prefix" | sed "s+$prefix/++g")"
+  fi
+  
+  vfiles="$(echo "$vfiles" | sed 's+/.*+/+g' | sort | uniq)"
+  #                         only root file name     replace \ with /   move first / to end of line     remove duplicate entries
+  #vfiles="$(echo "$vfiles" | awk -F '/' '{print $1}' | sed 's+\\+/+g' | sed 's+^/\(.*\)+\1/+' | sort | uniq)"
+  
+  #echo "$vfiles" 1>&2
+  
+  #get list of apps --------------- and exclude apps mentioned in hidelist file ---------------- remove lines containing '/'
+  APPS="$(echo "$vfiles" | grep -v '/')"
+  
+  #get list of "directories"
+  DIRS="$(echo "$vfiles" | grep '/' | tr -d '/' | grep -vx "hidden")"
+  #APPS="$(ls "${DIRECTORY}/apps")"
+  
+  #echo -e "Apps: $APPS\nDirs: $DIRS" 1>&2
+  
+  #exit 0
   #remove apps that are not compatible with OS architecture
   PREIFS="$IFS"
   IFS=$'\n'
@@ -96,16 +165,28 @@ if [ $reloadlist == 1 ];then
   #shuffle the list if enabled
   if [ "$(cat "${DIRECTORY}/data/settings/Shuffle App list")" == 'Yes' ];then
     APPS="$(echo "$APPS" | shuf)"
+    DIRS="$(echo "$DIRS" | shuf)"
   fi
   
   if [ "$format" == yad ];then
     PREIFS="$IFS"
     IFS=$'\n'
     LIST=''
+    for i in $DIRS
+    do
+      LIST="${LIST}${DIRECTORY}/icons/folder.png
+${DIRECTORY}/icons/none-24.png
+$i
+$i/
+App folder
+"
+    done
+    
     for i in $APPS
     do
       LIST="$LIST$(echo "${DIRECTORY}/icons/$(cat "${DIRECTORY}/data/status/${i}" 2>/dev/null || echo "none").png")
 ${DIRECTORY}/apps/${i}/icon-24.png
+$i
 $i
 "\("$(cat "${DIRECTORY}/data/status/${i}" 2>/dev/null || echo "uninstalled")"\)" $(echo "$(cat "${DIRECTORY}/apps/${i}/description" || echo "Description unavailable")" | head -n1)
 "
@@ -115,6 +196,12 @@ $i
     PREIFS="$IFS"
     IFS=$'\n'
     LIST=''
+    for i in $DIRS
+    do
+      LIST="$LIST
+${i};${DIRECTORY}/icons/folder-64.png;${i}/"
+    done
+    
     for i in $APPS
     do
       LIST="$LIST
@@ -125,21 +212,15 @@ ${i} "\("$(cat "${DIRECTORY}/data/status/${i}" 2>/dev/null || echo "uninstalled"
   LIST="$(echo -e "$LIST")"
   
   #save entire list string to file for future use
-  echo "$LIST" > "${DIRECTORY}/data/preload/LIST"
+  echo "$LIST" > "$listfile"
   export CACHED_LIST="$LIST"
   
   #save timestamps to file too
   mktimestamps
-  echo "$timestamps" > "${DIRECTORY}/data/preload/timestamps"
+  echo "$timestamps" > "$timestampfile"
 else
-  if [ -z "$CACHED_LIST" ];then
-    echo "Reading list file..." 1>&2
-    LIST="$(cat "${DIRECTORY}/data/preload/LIST")"
-    export CACHED_LIST="$LIST"
-  else
-    echo "Reading list variable..." 1>&2
-    LIST="$CACHED_LIST"
-  fi
+  echo "Reading list file..." 1>&2
+  LIST="$(cat "$listfile")"
 fi
 
 (#put icons in cache
