manage: only check for internet connection on install

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -180,7 +180,7 @@ validate_apps_gui() { #Given a list of actions and apps, graphically notify the 
         
         if [ $? == 0 ];then
           #if user clicked Yes, run the updater and avoid launching a second terminal
-          use_terminal=0 "${DIRECTORY}/updater" gui fast &>/dev/stderr
+          use_terminal=0 "${DIRECTORY}/updater" gui fast 1>&2
           
           #now that the api script was potentially updated, source it again to get new functions
           source "${DIRECTORY}/api" || error "failed to source ${DIRECTORY}/api"
@@ -545,10 +545,12 @@ elif [ "$1" == 'install' ] || [ "$1" == 'uninstall' ];then
     action=uninstall
   fi
   
-  #check for internet connection
-  errors="$(command wget --spider https://github.com 2>&1)"
-  if [ $? != 0 ];then
-    error "No internet connection! (github.com failed to respond)\nErrors:\n$errors"
+  if [ "$action" == install ];then
+    #check for internet connection
+    errors="$(command wget --spider https://github.com 2>&1)"
+    if [ $? != 0 ];then
+      error "No internet connection! (github.com failed to respond)\nErrors:\n$errors"
+    fi
   fi
   
   #ensure not a disabled app
