everything should be functional

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -438,7 +438,7 @@ $app"
   while true;do #repeat until nothing is left in the queue
     
     #check for new actions to be executed
-    echo -n > "${DIRECTORY}/data/manage-daemon/queue" & #ensure that the pipe is in write mode to prevent cat from hanging if the queue file is empty
+    echo -n > "${DIRECTORY}/data/manage-daemon/queue" & #ensure that the pipe is in write mode to prevent tac from hanging if the queue file is empty
     new_lines="$(tac "${DIRECTORY}/data/manage-daemon/queue")" # tac reverses the order of the list. a plain cat of the file will give the newest item in the queue first.
     
     #keep track of all actions for this session with the $queue variable
@@ -447,19 +447,39 @@ $app"
     elif [ ! -z "$new_lines" ];then # add new_lines to queue if new_lines is not empty
       queue+=$'\n'"$new_lines"
     fi
-
+    
+    #check if queue is complete - diagnose apps and provide the opportunity to retry failed actions, otherwise exit loop
+    if [ "${current_line_num}" -gt "$(echo "$queue" | wc -l)" ];then
+      #diagnose every failed app's logfile - list item format is $action;$app;$exitcode
+      failed_apps="$(echo "$queue" | grep ';1$' | sed 's/;1$//g')"
+      retry_apps="$(diagnose_apps "$failed_apps")"
+      if [ -z "$retry_apps" ];then
+        #user chose to not retry the failed action(s).
+        #edge case: user may have added more actions while the diagnosis window was open. Check for this, and if nothing found, exit loop
+        echo -n > "${DIRECTORY}/data/manage-daemon/queue" & #ensure that the pipe is in write mode to prevent tac from hanging if the queue file is empty
+        new_lines="$(tac "${DIRECTORY}/data/manage-daemon/queue")"
+        if [ -z "$new_lines" ];then
+          break
+        else
+          #Replace past '1' exit codes with "diagnosed" to avoid repeated diagnosis
+          queue="$(echo "$queue" | sed 's/;1$/;diagnosed/g')"
+          #user added more actions while the diagnosis window was open
+          queue+=$'\n'"$new_lines"
+        fi
+      else
+        #user chose to retry action(s). Replace '1' exit codes with "diagnosed" to avoid repeated diagnosis
+        queue="$(echo "$queue" | sed 's/;1$/;diagnosed/g')"
+        #and now add to queue the actions we want to retry.
+        queue+=$'\n'"$retry_apps"
+      fi
+    fi
+    
     # reorder queue list to prioritize app refresh and file update actions
     queue="$(reorder_list "$queue")"
     
     if [ ! -z "$new_lines" ] && [ "$sourced_updater" == 0 ] && grep -q "update\|refresh\|update-file" <<<"$new_lines" ;then #source updater if necessary
       source "${DIRECTORY}/updater" source
       sourced_updater=1
-    fi
-    #echo "length of queue is $(echo "$queue" | wc -l)"
-    
-    #exit loop if queue is complete and no new actions were added to the queue
-    if [ "${current_line_num}" -gt "$(echo "$queue" | wc -l)" ];then
-      break
     fi
     
     #echo "current position in queue is ${current_line_num}"
@@ -481,13 +501,13 @@ $app"
       write_list_pid=$!
       
       #secondary list-writing background process - kill it if it exists because write_list just sent a newer version of the list to yad
-      [ ! -z "$secondary_write_list_pid" ] && process_exists "$secondary_write_list_pid" && kill "$secondary_write_list_pid"
+      [ ! -z "$secondary_write_list_pid" ] && kill "$secondary_write_list_pid" 2>/dev/null
     else
       #if app1 is refreshed and app2 is then reinstalled, the list would only say app1 is bring refreshed for the entirety of app2's reinstallation, due to the process-skipping.
       #launch a secondary background process that waits for $write_list_pid to finish
       
       #only allow one secondary background process to run; kill previous jobs and start a new one
-      [ ! -z "$secondary_write_list_pid" ] && process_exists "$secondary_write_list_pid" && kill "$secondary_write_list_pid"
+      [ ! -z "$secondary_write_list_pid" ] && kill "$secondary_write_list_pid" 2>/dev/null
       (while process_exists $write_list_pid ;do sleep 1 ;done ; write_list "$queue") &
       secondary_write_list_pid=$!
     fi
@@ -500,17 +520,23 @@ $app"
       exitcode=$?
     elif [ "$action" == refresh ];then
       #Set terminal title
-      echo -ne "\e]0;${action^}ing ${app}\a"
+      echo -ne "\e]0;Refreshing ${app}\a"
       refresh_app "$app"
+      exitcode=$?
+    elif [ "$action" == update ];then #manage can handle this action, but avoid spawning subprocess
+      #Set terminal title
+      echo -ne "\e]0;Updating ${app}\a"
+      update_app "$app"
       exitcode=$?
     else
       #Set terminal title
-      echo -ne "\e]0;${action^}ing ${app}\a" | sed 's/Updateing/Updating/g'
+      echo -ne "\e]0;${action^}ing ${app}\a"
       "${DIRECTORY}/manage" "$action" "$app"
       exitcode=$?
     fi
     
     #record exit code in current line of $queue
+    [ "$exitcode" != 0 ] && exitcode=1 #for easier regex and sed lines, force non-zero exit codes to be 1
     queue="$(echo "$queue" | sed "${current_line_num}s/;in-progress$/;$exitcode/")"
     
     #one more line of $queue has been completed.
@@ -518,7 +544,7 @@ $app"
   done
   
   #refresh the list in queue-viewer window for the final time with all actions complete
-  [ ! -z "$secondary_write_list_pid" ] && process_exists "$secondary_write_list_pid" && kill "$secondary_write_list_pid" #kill secondary list writer
+  [ ! -z "$secondary_write_list_pid" ] && kill "$secondary_write_list_pid" 2>/dev/null #kill secondary list writer
   wait $write_list_pid
   write_list "$queue"
   
@@ -535,10 +561,6 @@ ${DIRECTORY}/icons/none-1.png
   #close the queue-viewer window in a few seconds
   (sleep 5; kill $yadpid 2>/dev/null) &
   
-  #diagnose every failed app's logfile - list item format is $action;$app;$exitcode
-  failed_apps="$(echo "$queue" | grep ';1$' | awk -F';' '{print $2}')"
-  diagnose_apps "$failed_apps"
-
   # if update refresh or update-file actions were run then update the .git folder
   if [ "$sourced_updater" == 1 ]; then
     update_git
