Add `-q` flag to suppress output

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -389,14 +389,14 @@ elif [ "$1" == 'check-all' ];then
   #if the updater script exists in update folder, then just git pull to save time
   if [ -f "${DIRECTORY}/update/pi-apps/updater" ];then
     cd "${DIRECTORY}/update/pi-apps"
-    git pull || rm -rf "${DIRECTORY}/update"
+    git pull -q 1>&2 || rm -rf "${DIRECTORY}/update"
   fi | grep -v "Already up to date." 1>&2
   
   #re-check and if updater script does not exist then do a git clone
   if [ ! -f "${DIRECTORY}/update/pi-apps/updater" ];then
     rm -rf "${DIRECTORY}/update"
     mkdir -p "${DIRECTORY}/update" && cd "${DIRECTORY}/update" || error "failed to enter the update directory!"
-    git clone --depth=1 "$(cat "${DIRECTORY}/etc/git_url")" 1>&2 || error "failed to clone repository to the update directory!"
+    git clone --depth=1 "$(cat "${DIRECTORY}/etc/git_url")" -q 1>&2 || error "failed to clone repository to the update directory!"
   fi
   
   echo "Done" 1>&2
