kg-install: mark ALL packages as autoremovable

diff --git a/pkg-install b/pkg-install
--- a/pkg-install
+++ b/pkg-install
@@ -256,9 +256,9 @@ fi
 
 #inform user packages are upgradeable
 if [ ! -z "$(echo "$output" | grep 'packages can be upgraded' )" ];then
-  echo -e "\e[33mSome packages can be upgraded.\e[39m Please consider running \e[4msudo apt full-upgrade\e[0m."
+  echo -e "\e[33mSome packages can be upgraded.\e[39m Please consider running \e[4msudo a\e[0mp\e[4mt full-u\e[0mpg\e[4mrade\e[0m."
 elif [ ! -z "$(echo "$output" | grep 'package can be upgraded' )" ];then
-  echo -e "\e[33mOne package can be upgraded.\e[39m Please consider running \e[4msudo apt full-upgrade\e[0m."
+  echo -e "\e[33mOne package can be upgraded.\e[39m Please consider running \e[4msudo a\e[0mp\e[4mt full-u\e[0mpg\e[4mrade\e[0m."
 fi
 
 #exit on apt error
@@ -295,8 +295,6 @@ for package in $PKG_LIST ;do
       error "pkg_install: While installing local packages, $package failed to install."
     fi
     
-    sudo -E apt-mark auto "$packagename" || error "pkg-install: failed to mark the $packagename package as autoremovable.\nlocal package path: $package"
-    
   fi
   
 done
@@ -328,6 +326,13 @@ done
 if echo "$PKG_LIST" | grep -q '*';then 
   error "pkg_install: failed to remove all regex from the package list!\nContents of PKG_LIST:\n$PKG_LIST"
 fi
+}
+
+#mark ALL packages as autoremovable
+{
+for package in $PKG_LIST ;do
+  sudo -E apt-mark auto "$packagename" || error "pkg-install: failed to mark the $packagename package as autoremovable."
+done
 }
 
 #format PKG_LIST - remove double spaces, preceding spaces, and trailing spaces.
