Add `reduceapt` function

diff --git a/purge-installed b/purge-installed
--- a/purge-installed
+++ b/purge-installed
@@ -11,6 +11,10 @@ function error {
   exit 1
 }
 
+reduceapt() { #remove unwanted lines from apt output
+  grep -v "apt does not have a stable CLI interface.\|Reading package lists...\|Building dependency tree\|Reading state information...\|Need to get\|After this operation,\|Get:\|Fetched\|Selecting previously unselected package\|Preparing to unpack\|Unpacking \|Setting up \|Processing triggers for "
+}
+
 DIRECTORY="$(readlink -f "$(dirname "$0")")"
 
 echo -e "\e[97m\nRunning purge-installed...\e[39m"
@@ -34,7 +38,7 @@ if dpkg -l pi-apps-$appnamehash &>/dev/null ;then
   #new pkg-install implementation - using dummy debs
   
   echo -e "\e[97m\nRemoving dummy deb for $app...\e[39m"
-  sudo -E apt purge -y pi-apps-$appnamehash --autoremove || error "apt failed to purge dummy deb (pi-apps-$appnamehash)!"
+  sudo -E apt purge -y pi-apps-$appnamehash --autoremove 2>&1 | reduceapt || error "apt failed to purge dummy deb (pi-apps-$appnamehash)!"
   
 elif [ -f "${DIRECTORY}/data/installed-packages/${app}" ];then
   #old pkg-install implementation
