hopefully manage fixed now

diff --git a/updater b/updater
--- a/updater
+++ b/updater
@@ -161,20 +161,23 @@ echo "Button: ${button}"
 
 lxterminal --title='Updating apps...' -e '
 trap "sleep infinity" EXIT
+DIRECTORY="'${DIRECTORY}'"
+mainupdate="'$mainupdate'"
+updatable="'$updatable'"
 PREIFS="$IFS"
 IFS="|"
-for i in '$updatable'
+for i in $updatable
 do
   "${DIRECTORY}/manage" update "$i" nofetch
   echo -e "\e[92m${i} was updated successfully.\e[39m"
 done
 
-for i in '$mainupdate'
+for i in $mainupdate
 do
-  mkdir -p "$(dirname "'${DIRECTORY}'/${i}")"
+  mkdir -p "$(dirname "${DIRECTORY}/${i}")"
   
   #copy new version to apps/
-  cp -f "'${DIRECTORY}'/update/pi-apps/${i}" "'${DIRECTORY}'/${i}" || error \"Failed to copy '${DIRECTORY}'/update/pi-apps/"${i}"!
+  cp -f "${DIRECTORY}/update/pi-apps/${i}" "${DIRECTORY}/${i}" || error \"Failed to copy ${DIRECTORY}/update/pi-apps/"${i}"!
   
   echo -e "\e[92m${i} was updated successfully.\e[39m"
 done
