Update apps/XiaoMiTool/install
Co-authored-by: Crilum <91354257+Crilum@users.noreply.github.com>

diff --git a/apps/XiaoMiTool/install b/apps/XiaoMiTool/install
--- a/apps/XiaoMiTool/install
+++ b/apps/XiaoMiTool/install
@@ -17,7 +17,7 @@ Exec=gksudo -k -u root JAVA_HOME=$JAVA_HOME $HOME/XiaoMiToolV2/gradlew run
 Icon=$(dirname "$0")/icon-64.png
 Terminal=false
 Type=Application
-Categories=System" > ~/.local/share/applications/XiaoMiTool.desktop || error "Failed to create menu shortcut."
+Categories=Utilities;" > ~/.local/share/applications/XiaoMiTool.desktop || error "Failed to create menu shortcut."
 
 echo "Creating execution script..."
 echo "#!/bin/sh
