Use instant binary instead of adding adoptium repo

diff --git a/apps/Unciv/install b/apps/Unciv/install
--- a/apps/Unciv/install
+++ b/apps/Unciv/install
@@ -7,44 +7,21 @@ install_packages lsb-release wget gpg || error "Failed to install dependencies"
 mkdir -p $HOME/Unciv || error "Failed to create folder $HOME/Unciv"
 
 ### Add LICENSE from Github if doesn't exist
-if [[ ! -f ~/Unciv/LICENSE ]]; then
-  status "Adding license file"
-  wget -O ~/Unciv/LICENSE https://raw.githubusercontent.com/yairm210/Unciv/master/LICENSE || error 'Failed to download license!'
-fi
+status "Adding license file"
+wget -O ~/Unciv/LICENSE https://raw.githubusercontent.com/yairm210/Unciv/master/LICENSE || error 'Failed to download license!'
 
-### install temurin-8-jdk
+### download temurin-8-jdk
 # the 'default-jre' (OpenJDK-11-jre) package takes too much RAM and runs very sloppy in Raspberry Pi 3B+
 # so, we will use Temurin OpenJDK 8 installation cause thats the minimal Java version Unciv needs
 # Temurin very smoothly on Raspberry Pi 3B+ without any problems
 
-status "Adding Adoptium repository:"
-
-echo "- public key -> keyring"
-rm -f /tmp/adoptium-public-key /tmp/adoptium-archive-keyring.gpg
-wget -O /tmp/adoptium-public-key https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
-gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --import /tmp/adoptium-public-key
-rm -f /tmp/adoptium-public-key
-
-echo " - keyring -> GPG key"
-gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --export --output /tmp/adoptium-archive-keyring.gpg
-rm -f /tmp/adoptium-keyring.gpg
-
-echo " - Moving GPG key to /usr/share/keyrings"
-sudo mv -f /tmp/adoptium-archive-keyring.gpg /usr/share/keyrings
-
-echo " - Creating /etc/apt/sources.list.d/adoptium.list"
-echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adoptium.list >/dev/null
-
-echo " - Installing temurin-8-jdk"
-#try to install temurin-8-jdk; if it fails, remove repository to avoid breaking user's system
-(install_packages temurin-8-jdk)
-if [ $? != 0 ];then
-  sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
-  error "Failed to install temurin packages. Adoptium repository has been removed."
-fi
+wget -O "$HOME/Unciv/openjdk-8.tar.gz" https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_arm_linux_hotspot_8u312b07.tar.gz || exit 1
+tar -xf "$HOME/Unciv/openjdk-8.tar.gz" -C  "$HOME/Unciv" || error "Failed to extract $HOME/Unciv/openjdk-8.tar.gz"
+mv -f "$HOME/Unciv/jdk8u312-b07-aarch32-20211101-jre" "$HOME/Unciv/openjdk-8-jre" || error "Failed to rename "$HOME/Unciv/jdk8u312-b07-aarch32-20211101-jre" to "$HOME/Unciv/openjdk-8-jre""
+rm -rf "$HOME/Unciv/openjdk-8.tar.gz" 
 
 ### Download Unciv.jar
-wget -O "$HOME/Unciv/Unciv.jar" https://github.com/yairm210/Unciv/releases/download/3.18.10-patch1/Unciv.jar || exit 1
+wget -O "$HOME/Unciv/Unciv.jar" https://github.com/yairm210/Unciv/releases/download/3.18.11/Unciv.jar || exit 1
 
 status "Creating runner script ($HOME/Unciv/Unciv.sh)"
 # This is necessary because some special characters are supported in Desktop Entry Files.
@@ -52,12 +29,10 @@ status "Creating runner script ($HOME/Unciv/Unciv.sh)"
 # see https://github.com/yairm210/Unciv/blob/master/desktop/linuxFilesForJar/Unciv.sh
 echo "\
 cd $HOME/Unciv
-$(echo /usr/lib/jvm/temurin-8-*/jre/bin/java) -jar ./Unciv.jar" \
-> ~/Unciv/Unciv.sh || error "Failed to write $HOME/Unciv/Unciv.sh!"
+"$HOME/Unciv/openjdk-8-jre/bin/java" -jar ./Unciv.jar" > ~/Unciv/Unciv.sh || error "Failed to write $HOME/Unciv/Unciv.sh!"
 
 chmod +x $HOME/Unciv/Unciv.sh || error "Failed to make $HOME/Unciv/Unciv.sh executable!"
 
-status "Creating menu launcher"
 echo "\
 [Desktop Entry]
 Comment=Open-source Android/Desktop remake of Civ V
