Unciv: improve safety, verbosity, and cosmetics

diff --git a/apps/Unciv/install b/apps/Unciv/install
--- a/apps/Unciv/install
+++ b/apps/Unciv/install
@@ -8,6 +8,7 @@ mkdir -p $HOME/Unciv || error "Failed to create folder $HOME/Unciv"
 
 ### Add LICENSE from Github if doesn't exist
 if [[ ! -f ~/Unciv/LICENSE ]]; then
+  status "Adding license file"
   wget -O ~/Unciv/LICENSE https://raw.githubusercontent.com/yairm210/Unciv/master/LICENSE || error 'Failed to download license!'
 fi
 
@@ -16,23 +17,36 @@ fi
 # so, we will use Temurin OpenJDK 8 installation cause thats the minimal Java version Unciv needs
 # Temurin very smoothly on Raspberry Pi 3B+ without any problems
 
-# add repo keyring
-cd /tmp
-sudo rm -rf public
-wget https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
-gpg --no-default-keyring --keyring ./adoptium-keyring.gpg --import public
-gpg --no-default-keyring --keyring ./adoptium-keyring.gpg --export --output adoptium-archive-keyring.gpg
-rm -rf public
-rm -rf adoptium-keyring.gpg
-sudo mv adoptium-archive-keyring.gpg /usr/share/keyrings
-echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
-sudo apt update
-install_packages temurin-8-jdk || error "Failed to install temurin packages"
+status "Adding Adoptium repository:"
+
+echo "- public key -> keyring"
+rm -f /tmp/adoptium-public-key /tmp/adoptium-archive-keyring.gpg
+wget -O /tmp/adoptium-public-key https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
+gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --import /tmp/adoptium-public-key
+rm -f /tmp/adoptium-public-key
+
+echo " - keyring -> GPG key"
+gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --export --output /tmp/adoptium-archive-keyring.gpg
+rm -f /tmp/adoptium-keyring.gpg
+
+echo " - Moving GPG key to /usr/share/keyrings"
+sudo mv -f /tmp/adoptium-archive-keyring.gpg /usr/share/keyrings
+
+echo " - Creating /etc/apt/sources.list.d/adoptium.list"
+echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adoptium.list >/dev/null
+
+echo " - Installing temurin-8-jdk"
+#try to install temurin-8-jdk; if it fails, remove repository to avoid breaking user's system
+(install_packages temurin-8-jdk)
+if [ $? != 0 ];then
+  sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
+  error "Failed to install temurin packages. Adoptium repository has been removed."
+fi
 
 ### Download Unciv.jar
-wget -O "$HOME/Unciv/Unciv.jar" https://github.com/yairm210/Unciv/releases/download/3.18.11/Unciv.jar || exit 1
+wget -O "$HOME/Unciv/Unciv.jar" https://github.com/yairm210/Unciv/releases/download/3.18.10-patch1/Unciv.jar || exit 1
 
-### Make Unciv.sh
+status "Creating runner script ($HOME/Unciv/Unciv.sh)"
 # This is necessary because some special characters are supported in Desktop Entry Files.
 # Without running Unciv.jar from ~/Unciv, the Game Data will be saved in ~ by default (not ~/Unciv).
 # see https://github.com/yairm210/Unciv/blob/master/desktop/linuxFilesForJar/Unciv.sh
@@ -43,7 +57,7 @@ $(echo /usr/lib/jvm/temurin-8-*/jre/bin/java) -jar ./Unciv.jar" \
 
 chmod +x $HOME/Unciv/Unciv.sh || error "Failed to make $HOME/Unciv/Unciv.sh executable!"
 
-### Make Desktop entry
+status "Creating menu launcher"
 echo "\
 [Desktop Entry]
 Comment=Open-source Android/Desktop remake of Civ V
