chage `LICENSE` download failure error message
Co-authored-by: cycool29 <cycool29@gmail.com>

diff --git a/apps/Unciv/install b/apps/Unciv/install
--- a/apps/Unciv/install
+++ b/apps/Unciv/install
@@ -5,7 +5,7 @@ mkdir -p $HOME/Unciv || error "Failed to create folder $HOME/Unciv"
 
 ### Add LICENSE from Github if doesn't exist
 if [[ ! -f ~/Unciv/LICENSE ]]; then
-  wget -O ~/Unciv/LICENSE https://raw.githubusercontent.com/yairm210/Unciv/master/LICENSE || error 'Failed to make folder $HOME/Unciv!'
+  wget -O ~/Unciv/LICENSE https://raw.githubusercontent.com/yairm210/Unciv/master/LICENSE || error 'Failed to download license!'
 fi
 
 ### install openjdk-8-jre-headless
