use `temurin-8-jdk` instead of `openjdk-8-jre`
Co-authored-by: theofficialgman <28281419+theofficialgman@users.noreply.github.com>

diff --git a/apps/Unciv/install b/apps/Unciv/install
--- a/apps/Unciv/install
+++ b/apps/Unciv/install
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+### Install dependencies
+install_packages lsb-release wget gpg || error "Failed to install dependencies"
+
 ### Make directory ~/Unciv if not available
 mkdir -p $HOME/Unciv || error "Failed to create folder $HOME/Unciv"
 
@@ -8,11 +11,23 @@ if [[ ! -f ~/Unciv/LICENSE ]]; then
   wget -O ~/Unciv/LICENSE https://raw.githubusercontent.com/yairm210/Unciv/master/LICENSE || error 'Failed to download license!'
 fi
 
-### install openjdk-8-jre
-# the 'default jre' (OpenJDK-11-jre) package takes too much RAM and runs very sloppy in Raspberry Pi 3B+
-# so, we will OpenJDK 8 JRE installation cause thats the minimal Java version Unciv needs
-# openjdk-8-jre very smoothly without any problems
-install_packages openjdk-8-jre || exit 1
+### install temurin-8-jdk
+# the 'default-jre' (OpenJDK-11-jre) package takes too much RAM and runs very sloppy in Raspberry Pi 3B+
+# so, we will use Temurin OpenJDK 8 installation cause thats the minimal Java version Unciv needs
+# Temurin very smoothly on Raspberry Pi 3B+ without any problems
+
+# add repo keyring
+cd /tmp
+sudo rm -rf public
+wget https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
+gpg --no-default-keyring --keyring ./adoptium-keyring.gpg --import public
+gpg --no-default-keyring --keyring ./adoptium-keyring.gpg --export --output adoptium-archive-keyring.gpg
+rm -rf public
+rm -rf adoptium-keyring.gpg
+sudo mv adoptium-archive-keyring.gpg /usr/share/keyrings
+echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
+sudo apt update
+install_packages temurin-8-jdk || error "Failed to install temurin packages"
 
 ### Download Unciv.jar
 wget -O "$HOME/Unciv/Unciv.jar" https://github.com/yairm210/Unciv/releases/download/3.18.10-patch1/Unciv.jar || exit 1
