Temurin repo addition (#1285)
* update MultiMC to use temurin apt repo

* bump MultiMC Launcher version to latest

* ubuntu jammy (22.04) has removed openjdk-16, only install if available

openjdk-17 works for running minecraft 1.17.X+ but 16 should be installed if available (because thats what mojang uses)

* only remove repo if safe - MMC

if no packages have been installed from this repo (like through other scripts), and the install_packages failed, then remove the repo and key

* only remove repo if safe - Unciv

diff --git a/apps/Unciv/install b/apps/Unciv/install
--- a/apps/Unciv/install
+++ b/apps/Unciv/install
@@ -39,8 +39,15 @@ status "Installing temurin-8-jdk"
 #try to install temurin-8-jdk; if it fails, remove repository to avoid breaking user's system
 (install_packages temurin-8-jdk)
 if [ $? != 0 ]; then
-  sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
-  error "Failed to install temurin packages. Adoptium repository has been removed."
+  anything_installed_from_repo "https://adoptium.jfrog.io/artifactory/deb"
+  if [ $? != 0 ]; then
+    # nothing installed from repo, this check is to prevent removing repos which other pi-apps scripts or the user have used successfully
+    # safe to remove
+    sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
+    error "Failed to install temurin packages. Adoptium repository has been removed."
+  else
+    error "Failed to install temurin packages."
+  fi
 fi
 
 status "Downloading Unciv.jar"
