brave: delete repo if keyring download fails
should prevent an "unsigned" error a user reported

diff --git a/apps/Brave/install-64 b/apps/Brave/install-64
--- a/apps/Brave/install-64
+++ b/apps/Brave/install-64
@@ -3,7 +3,10 @@
 sudo rm -f /usr/share/keyrings/brave-browser-archive-keyring.gpg
 sudo rm -f /etc/apt/sources.list.d/brave-browser-release.list
 echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
-sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
+if ! sudo wget -O /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg ;then
+  sudo rm -f /etc/apt/sources.list.d/brave-browser-release.list /usr/share/keyrings/brave-browser-archive-keyring.gpg
+  error "Failed to download keyring for brave-browser. brave-browser repository has been removed."
+fi
 
 (install_packages brave-browser)
 if [ $? != 0 ]; then
