Various error-fixes to Doom 3

diff --git a/apps/Doom 3/uninstall b/apps/Doom 3/uninstall
--- a/apps/Doom 3/uninstall
+++ b/apps/Doom 3/uninstall
@@ -10,7 +10,8 @@ function error {
 #if your app installs any packages, keep this command here so those packages will be removed.
 "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
 
-#Running Uninstall script
-
-cd ~/RPIDoom3Installer || "Failed to Change directory"
-./uninstall.sh || error "Failed to execute uninstall script :("
+if [ -d ~/RPIDoom3Installer ];then
+  cd ~/RPIDoom3Installer || "Failed to Change directory"
+  echo "Running uninstall script..."
+  ./uninstall.sh || error "Failed to execute uninstall script :("
+fi
