Firefox Rapid Release: add mozillateam official email
Mozilla Team uses their own mailing list for all ubuntu mozilla bug (including their ppas) https://lists.ubuntu.com/mailman/listinfo/ubuntu-mozillateam-bugs

diff --git a/apps/Firefox Rapid Release/install b/apps/Firefox Rapid Release/install
--- a/apps/Firefox Rapid Release/install
+++ b/apps/Firefox Rapid Release/install
@@ -23,7 +23,7 @@ Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/firefox >/dev/null
   
     # allow unattented upgrades to upgrade from this ppa if unattented upgrades is enabled
     echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox >/dev/null
-    install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu ${__os_codename^}. Please contact Mozilla Team for any issues https://launchpad.net/~mozillateam/+archive/ubuntu/ppa"
+    install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu ${__os_codename^}. Please contact Mozilla Team via email for any issues ubuntu-mozillateam-bugs@lists.ubuntu.com"
   else
     install_packages firefox || exit 1
   fi
@@ -46,7 +46,7 @@ Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/firefox >/dev/null
       sudo rm -f /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-bionic.list
       debian_ppa_installer "mozillateam/ppa" "jammy" "0AB215679C571D1C8325275B9BDB3D89CE49EC21" || exit 1
       echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:jammy";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox >/dev/null
-      install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu Jammy (used for Debian Bookworm). Please contact Mozilla Team for any issues https://launchpad.net/~mozillateam/+archive/ubuntu/ppa"
+      install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu Jammy (used for Debian Bookworm). Please contact Mozilla Team via email for any issues ubuntu-mozillateam-bugs@lists.ubuntu.com"
     fi
     ;;
   bullseye)
@@ -54,12 +54,12 @@ Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/firefox >/dev/null
     sudo rm -f /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-bionic.list
     debian_ppa_installer "mozillateam/ppa" "focal" "0AB215679C571D1C8325275B9BDB3D89CE49EC21" || exit 1
     echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:focal";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox >/dev/null    
-    install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu Focal (used for Debian Bullseye). Please contact Mozilla Team for any issues https://launchpad.net/~mozillateam/+archive/ubuntu/ppa"
+    install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu Focal (used for Debian Bullseye). Please contact Mozilla Team via email for any issues ubuntu-mozillateam-bugs@lists.ubuntu.com"
     ;;
   *)
     debian_ppa_installer "mozillateam/ppa" "bionic" "0AB215679C571D1C8325275B9BDB3D89CE49EC21" || exit 1
     echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:bionic";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox >/dev/null
-    install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu Bionic. Please contact Mozilla Team for any issues https://launchpad.net/~mozillateam/+archive/ubuntu/ppa"
+    install_packages firefox || error "User error (reporting allowed): Firefox is not available from Mozilla Team PPA for $arch Ubuntu Bionic. Please contact Mozilla Team via email for any issues ubuntu-mozillateam-bugs@lists.ubuntu.com"
     ;;
   esac
   sudo apt --only-upgrade install firefox -y | less_apt
