only allow current architecture packages from ubuntu-ports
if user had amd64 or i386 architecures enabled in dpkg, the ubuntu-ports repo would error on apt update, since it does not have these architectures

fixes https://github.com/Botspot/pi-apps/issues/1468

diff --git a/apps/Firefox Rapid Release/install b/apps/Firefox Rapid Release/install
--- a/apps/Firefox Rapid Release/install
+++ b/apps/Firefox Rapid Release/install
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Add repository source to apt sources.list
 echo "Adding ubuntu repository..."
-echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-updates main" | sudo tee /etc/apt/sources.list.d/firefox-ubuntu.list || error "Failed to add repository to sources.list!"
+echo "deb [arch=$(dpkg --print-architecture)] http://ports.ubuntu.com/ubuntu-ports bionic-updates main" | sudo tee /etc/apt/sources.list.d/firefox-ubuntu.list || error "Failed to add repository to sources.list!"
 
 # Add ubuntu keyring
 echo "Signing ubuntu repository..."
