Snapdrop, StackEdit, and WhatsApp: specify --class so that custom icon gets used for browser process

diff --git a/apps/Snapdrop/install b/apps/Snapdrop/install
--- a/apps/Snapdrop/install
+++ b/apps/Snapdrop/install
@@ -6,7 +6,7 @@ sudo mkdir -p /usr/local/bin /usr/local/share/applications /usr/local/share/icon
 echo "Creating launcher and menu button..."
 echo '#!/bin/bash
 
-chromium-browser --user-data-dir="$HOME/.config/webapps/snapdrop" --app=https://snapdrop.net/' | sudo tee /usr/local/bin/snapdrop >/dev/null || error "Failed to create snapdrop launcher!"
+chromium-browser --user-data-dir="$HOME/.config/webapps/snapdrop" --app=https://snapdrop.net/ --class=snapdrop' | sudo tee /usr/local/bin/snapdrop >/dev/null || error "Failed to create snapdrop launcher!"
 
 sudo chmod +x /usr/local/bin/snapdrop || error "Failed to set snapdrop launcher permissions!"
 
@@ -23,5 +23,6 @@ Exec=/usr/local/bin/snapdrop
 Icon=snapdrop
 Terminal=false
 StartupNotify=true
+StartupWMClass=snapdrop
 Type=Application
 Categories=Utility" | sudo tee /usr/local/share/applications/snapdrop.desktop >/dev/null || error "Failed to create menu shortcut!"
diff --git a/apps/StackEdit/install b/apps/StackEdit/install
--- a/apps/StackEdit/install
+++ b/apps/StackEdit/install
@@ -6,7 +6,7 @@ sudo mkdir -p /usr/local/bin /usr/local/share/applications /usr/local/share/icon
 echo "Creating launcher and menu button..."
 echo '#!/bin/bash
 
-chromium-browser --user-data-dir="$HOME/.config/webapps/stackedit" --app=https://stackedit.io/app#' | sudo tee /usr/local/bin/stackedit >/dev/null || error "Failed to create stackedit launcher!"
+chromium-browser --user-data-dir="$HOME/.config/webapps/stackedit" --app=https://stackedit.io/app# --class=stackedit' | sudo tee /usr/local/bin/stackedit >/dev/null || error "Failed to create stackedit launcher!"
 
 sudo chmod +x /usr/local/bin/stackedit || error "Failed to set stackedit launcher permissions!"
 
@@ -23,5 +23,6 @@ Exec=/usr/local/bin/stackedit
 Icon=stackedit
 Terminal=false
 StartupNotify=true
+StartupWMClass=stackedit
 Type=Application
 Categories=Development;IDE;" | sudo tee /usr/local/share/applications/stackedit.desktop >/dev/null || error "Failed to create menu shortcut!"
diff --git a/apps/WhatsApp/install b/apps/WhatsApp/install
--- a/apps/WhatsApp/install
+++ b/apps/WhatsApp/install
@@ -6,7 +6,7 @@ sudo mkdir -p /usr/local/bin /usr/local/share/applications /usr/local/share/icon
 echo "Creating launcher and menu button..."
 echo '#!/bin/bash
 
-chromium-browser --user-data-dir="$HOME/.config/webapps/WhatsApp" --app=https://web.whatsapp.com' | sudo tee /usr/local/bin/whatsapp >/dev/null || error "Failed to create whatsapp launcher!"
+chromium-browser --user-data-dir="$HOME/.config/webapps/WhatsApp" --app=https://web.whatsapp.com --class=whatsapp' | sudo tee /usr/local/bin/whatsapp >/dev/null || error "Failed to create whatsapp launcher!"
 
 sudo chmod +x /usr/local/bin/whatsapp || error "Failed to set whatsapp launcher permissions!"
 
@@ -23,6 +23,6 @@ Exec=/usr/local/bin/whatsapp
 Icon=whatsapp
 Type=Application
 StartupNotify=false
-StartupWMClass=WhatsApp
+StartupWMClass=whatsapp
 Categories=Internet;Chat;Network
 Keywords=whatsapp;" | sudo tee /usr/local/share/applications/whatsapp.desktop >/dev/null || error "Failed to create menu shortcut!"
