add additional dependencies
also allow building if glslang-dev and glslang-tools are not available by default (like on ubuntu bionic)

diff --git a/apps/DDnet/install b/apps/DDnet/install
--- a/apps/DDnet/install
+++ b/apps/DDnet/install
@@ -1,7 +1,15 @@
 #!/bin/bash
 
 #Dependencies
-install_packages build-essential cmake git libcurl4-openssl-dev libssl-dev libfreetype6-dev libglew-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libsqlite3-dev libwavpack-dev python google-mock || exit 1
+install_packages build-essential cmake git libcurl4-openssl-dev libssl-dev libfreetype6-dev libglew-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libsqlite3-dev libwavpack-dev python google-mock glslang-tools glslang-dev libx264-dev || exit 1
+
+package_available glslang-tools
+if [[ $? == "0" ]]; then
+  install_packages glslang-tools glslang-dev || error "Failed to install dependencies"
+  vulkan=1
+else
+  vulkan=0
+fi
 
 #Clone the Repository
 cd /tmp
@@ -11,6 +19,10 @@ git_clone https://github.com/ddnet/ddnet --recursive || exit 1
 cd ddnet || exit 1
 mkdir build
 cd build || exit 1
-cmake .. || error 'Failed at cmake!'
+if [[ $vulkan == 1 ]]; then
+  cmake .. || error 'Failed at cmake!'
+else
+  cmake .. -DVULKAN=OFF || error 'Failed at cmake!'
+fi
 make -j$(nproc) || error 'Failed at make!'
 sudo make install || error "Failed to install"
