Update uninstall

diff --git a/apps/Falkon/uninstall b/apps/Falkon/uninstall
--- a/apps/Falkon/uninstall
+++ b/apps/Falkon/uninstall
@@ -1,8 +1,16 @@
-#! /bin/bash
-# Removes shortcuts
-rm -f ~/.local/share/applications/aiw.desktop
-# Removes main folder
-sudo rm -rf ~/All-is-well
-# Removes alias
-sed -i '/alias aiw=.*All-is-well.*/d' ~/.bashrc
-exit 0
+#!/bin/bash
+
+DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
+
+function error {
+  echo -e "\\e[91m$1\\e[39m"
+  exit 1
+}
+
+reduceapt() { #remove unwanted lines from apt output
+  grep -v "apt does not have a stable CLI interface.\|Reading package lists...\|Building dependency tree\|Reading state information...\|Need to get\|After this operation,\|Get:\|Fetched\|Selecting previously unselected package\|Preparing to unpack\|Unpacking \|Setting up \|Processing triggers for "
+}
+
+"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 0
+
+sudo apt purge falkon -y 2>&1 | reduceapt || error "Failed to purge packages!"
