Descent 1 and 2: show wget errors so they can be diagnosed

diff --git a/apps/Descent 1/install b/apps/Descent 1/install
--- a/apps/Descent 1/install
+++ b/apps/Descent 1/install
@@ -38,7 +38,7 @@ fi
 if $MISSING_GAME_DATA; then
     rm -rf $SOURCE_FOLDER
     sudo mkdir -p /opt/d1x-rebirth
-    wget -q --show-progress https://web.archive.org/web/20221208193117if_/https://www.dxx-rebirth.com/download/dxx/content/descent-pc-shareware.zip || error "failed to download game content!"
+    wget https://web.archive.org/web/20221208193117if_/https://www.dxx-rebirth.com/download/dxx/content/descent-pc-shareware.zip -O $PWD/descent-pc-shareware.zip || error "failed to download game content!"
     sudo unzip descent-pc-shareware.zip -d /opt/d1x-rebirth
     rm descent-pc-shareware.zip
 else
@@ -46,10 +46,10 @@ else
    rm -rf $SOURCE_FOLDER
 fi
 
-sudo wget -N -q --show-progress https://web.archive.org/web/20230702124034if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-hires.dxa --output-file /opt/d1x-rebirth/d1xr-hires.dxa || error "failed to download hires pack!"
-sudo wget -N -q --show-progress https://web.archive.org/web/20221208193318if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-sc55-music.dxa --output-file /opt/d1x-rebirth/d1xr-sc55-music.dxa  || error "failed to download ogg soundtrack!"
+sudo wget -N --show-progress https://web.archive.org/web/20230702124034if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-hires.dxa -O /opt/d1x-rebirth/d1xr-hires.dxa || error "failed to download hires pack!"
+sudo wget -N --show-progress https://web.archive.org/web/20221208193318if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-sc55-music.dxa -O /opt/d1x-rebirth/d1xr-sc55-music.dxa  || error "failed to download ogg soundtrack!"
 
-git_clone https://github.com/dxx-rebirth/dxx-rebirth
+git_clone https://github.com/dxx-rebirth/dxx-rebirth || exit 1
 cd dxx-rebirth
 scons sdl2=1 sdlmixer=1 d1x=1 -j$(nproc) || error "Failed to compile Descent 1 game engine!"
 sudo cp ./build/d1x-rebirth/d1x-rebirth /opt/d1x-rebirth/d1x-rebirth
