Descent games: try to fix dependency list

diff --git a/apps/Descent 1/install b/apps/Descent 1/install
--- a/apps/Descent 1/install
+++ b/apps/Descent 1/install
@@ -3,7 +3,7 @@ echo '                         __________'
 echo '__________/ DXX-Rebirth /'
 
 status "Installing required dependencies..."
-install_packages scons libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 libphysfs-dev libphysfs1 libglu1-mesa || exit 1
+install_packages scons libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libphysfs-dev libglu1-mesa-dev libgl1-mesa-dev || exit 1
 
 # Migration steps from old install
 SOURCE_FOLDER="~/.d1x-rebirth"
@@ -46,8 +46,8 @@ else
    rm -rf $SOURCE_FOLDER
 fi
 
-sudo wget -N --show-progress https://web.archive.org/web/20230702124034if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-hires.dxa -O /opt/d1x-rebirth/d1xr-hires.dxa || error "failed to download hires pack!"
-sudo wget -N --show-progress https://web.archive.org/web/20221208193318if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-sc55-music.dxa -O /opt/d1x-rebirth/d1xr-sc55-music.dxa  || error "failed to download ogg soundtrack!"
+sudo wget https://web.archive.org/web/20230702124034if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-hires.dxa -O /opt/d1x-rebirth/d1xr-hires.dxa || error "failed to download hires pack!"
+sudo wget https://web.archive.org/web/20221208193318if_/https://www.dxx-rebirth.com/download/dxx/res/d1xr-sc55-music.dxa -O /opt/d1x-rebirth/d1xr-sc55-music.dxa  || error "failed to download ogg soundtrack!"
 
 git_clone https://github.com/dxx-rebirth/dxx-rebirth || exit 1
 cd dxx-rebirth
diff --git a/apps/Descent 2/install b/apps/Descent 2/install
--- a/apps/Descent 2/install
+++ b/apps/Descent 2/install
@@ -3,7 +3,7 @@ echo '                         __________'
 echo '__________/ DXX-Rebirth /'
 
 status "Installing required dependencies..."
-install_packages scons libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 libphysfs-dev libphysfs1 libglu1-mesa || exit 1
+install_packages scons libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libphysfs-dev libglu1-mesa-dev libgl1-mesa-dev || exit 1
 
 # Migration steps from old install
 SOURCE_FOLDER="~/.d2x-rebirth"
@@ -38,7 +38,7 @@ fi
 if $MISSING_GAME_DATA; then
     rm -rf $SOURCE_FOLDER
     sudo mkdir -p /opt/d2x-rebirth
-    wget --show-progress https://web.archive.org/web/20221208193117if_/https://www.dxx-rebirth.com/download/dxx/content/descent2-pc-demo.zip -O $PWD/descent2-pc-demo.zip || error "failed to download game content!"
+    wget https://web.archive.org/web/20221208193117if_/https://www.dxx-rebirth.com/download/dxx/content/descent2-pc-demo.zip -O $PWD/descent2-pc-demo.zip || error "failed to download game content!"
     sudo unzip descent2-pc-demo.zip -d /opt/d2x-rebirth
     rm descent2-pc-demo.zip
 else
@@ -51,7 +51,7 @@ cd /opt/d2x-rebirth
 for i in $( ls | grep [A-Z] ); do sudo mv -f $i `echo $i | tr 'A-Z' 'a-z'`; done
 cd ~/
 
-sudo wget -N --show-progress https://web.archive.org/web/20221208193318if_/https://www.dxx-rebirth.com/download/dxx/res/d2xr-sc55-music.dxa -O /opt/d2x-rebirth/d2xr-sc55-music.dxa  || error "failed to download ogg soundtrack!"
+sudo wget https://web.archive.org/web/20221208193318if_/https://www.dxx-rebirth.com/download/dxx/res/d2xr-sc55-music.dxa -O /opt/d2x-rebirth/d2xr-sc55-music.dxa  || error "failed to download ogg soundtrack!"
 
 git_clone https://github.com/dxx-rebirth/dxx-rebirth || exit 1
 cd dxx-rebirth
