Update Geekbench to 5.4.4

diff --git a/apps/Geekbench/install b/apps/Geekbench/install
--- a/apps/Geekbench/install
+++ b/apps/Geekbench/install
@@ -1,7 +1,10 @@
 #!/bin/bash
-wget -O Geekbench.tar.gz https://cdn.geekbench.com/Geekbench-5.4.3-LinuxARMPreview.tar.gz
+
+version=5.4.4
+
+wget -O Geekbench.tar.gz https://cdn.geekbench.com/Geekbench-${version}-LinuxARMPreview.tar.gz
 tar -xf Geekbench.tar.gz || error "Failed to extract files!"
-sudo mv -f ./Geekbench-5.4.3-LinuxARMPreview /opt/geekbench || error "Failed to move source folder to /opt!"
+sudo mv -f ./Geekbench-${version}-LinuxARMPreview /opt/geekbench || error "Failed to move source folder to /opt!"
 
 # Create symbolic link
 if [ $arch == 32 ]; then
