Update install-32

diff --git a/apps/eDEX-UI/install-32 b/apps/eDEX-UI/install-32
--- a/apps/eDEX-UI/install-32
+++ b/apps/eDEX-UI/install-32
@@ -10,8 +10,8 @@ function error {
 rm -rf ~/eDEX-UI-RPi &>/dev/null
 mkdir ~/eDEX-UI-RPi
 wget -O ~/'eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.7.AppImage' 'https://github.com/GitSquared/edex-ui/releases/download/v2.2.7/eDEX-UI-Linux-armv7l.AppImage' || error 'Failed to download 2.2.6 appimage!'
-wget -O ~/'eDEX-UI-RPi/eDEX-UI-Linux-armv7l_3.0.0.AppImage' 'https://github.com/Botspot/eDEX-UI-RPi/raw/main/eDEX-UI%20Linux%20(armv7l)_3.0.0.AppImage' || error 'Failed to download v3.0 appimage!'
-chmod +x ~/'eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.7.AppImage' ~/'eDEX-UI-RPi/eDEX-UI-Linux-armv7l_3.0.0.AppImage' || error 'Failed to mark the appimage's as executable!'
+chmod +x ~/'eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.7.AppImage' || error 'Failed to mark the appimage's as executable!'
+
 
 echo "[Desktop Entry]
 Name=eDEX-UI 2.2.7
@@ -25,14 +25,3 @@ X-AppImage-Version=2.2.7
 Categories=System;
 X-Desktop-File-Install-Version=0.23
 X-AppImage-Comment=Generated by /tmp/.mount_eDEX-UDQYwse/AppRun" > ~/.local/share/applications/appimagekit-edex-ui.desktop
-
-echo "[Desktop Entry]
-Name=eDEX-UI 3.0.0
-Comment=eDEX-UI sci-fi interface
-Exec=bash -c "\""sudo modprobe fuse; $HOME/eDEX-UI-RPi/eDEX-UI Linux (armv7l)_3.0.0.AppImage"\"" %U
-Terminal=false
-Type=Application
-Icon=$(dirname "$0")/icon-64.png
-StartupWMClass=eDEX-UI
-X-AppImage-Version=3.0.0
-Categories=System;" > ~/.local/share/applications/appimagekit-edex-ui-3.desktop
