edex-ui: add update script, improve desktop shortcut

diff --git a/apps/eDEX-UI/install-32 b/apps/eDEX-UI/install-32
--- a/apps/eDEX-UI/install-32
+++ b/apps/eDEX-UI/install-32
@@ -1,20 +1,22 @@
 #!/bin/bash
 
-wget -O $HOME/eDEX-UI.AppImage 'https://github.com/GitSquared/edex-ui/releases/download/v2.2.8/eDEX-UI-Linux-armv7l.AppImage' || error 'Failed to download 2.2.8 appimage!'
+version=2.2.8
+
+wget -O $HOME/eDEX-UI.AppImage 'https://github.com/GitSquared/edex-ui/releases/download/v${version}/eDEX-UI-Linux-armv7l.AppImage' || error 'Failed to download ${version} appimage!'
 chmod +x $HOME/eDEX-UI.AppImage || error 'Failed to make the appimage executable!'
 
 enable_module fuse || exit 1
 
 mkdir -p ~/.local/share/applications
 echo "[Desktop Entry]
-Name=eDEX-UI 2.2.8
+Name=eDEX-UI
 Comment=eDEX-UI sci-fi interface
 Exec=$HOME/eDEX-UI.AppImage %U
 Terminal=false
 Type=Application
 Icon=$(dirname "$0")/icon-64.png
 StartupWMClass=eDEX-UI
-X-AppImage-Version=2.2.8
+X-AppImage-Version=${version}
 Categories=System;
 X-Desktop-File-Install-Version=0.23
-X-AppImage-Comment=Generated by /tmp/.mount_eDEX-UDQYwse/AppRun" > ~/.local/share/applications/appimagekit-edex-ui.desktop
+X-AppImage-Comment=Generated by /tmp/.mount_eDEX-UDQYwse/AppRun" > ~/.local/share/applications/edex-ui.desktop
