fix chroot: failed to run command ‘./chroot-xmrig-inst.sh’: No such file or directory

diff --git a/apps/XMRig/install-32 b/apps/XMRig/install-32
--- a/apps/XMRig/install-32
+++ b/apps/XMRig/install-32
@@ -294,7 +294,7 @@ sudo chmod 775 $chroot_dir/chroot-xmrig-inst.sh || error "Failed to make '$chroo
 status_green 'Done.'
 
 # Run install script
-sudo chroot $HOME/xmrig/bullseye ./chroot-xmrig-inst.sh || error 'Failed to build XMRig inside chroot!!!'
+sudo chroot $HOME/xmrig/bullseye /chroot-xmrig-inst.sh || error 'Failed to build XMRig inside chroot!!!'
 
 if [ -e $HOME/xmrig.json.bak ]; then
     userinput_func "Do you want to use your previous 'xmrig.json'?" "${default_table[@]}"
