Big rewrite of install script

diff --git a/apps/XMRig/install b/apps/XMRig/install
--- a/apps/XMRig/install
+++ b/apps/XMRig/install
@@ -7,20 +7,20 @@ function userinput_func {
   height=$(($(echo "$1" | grep -o '\\n' | wc -l) + 8))
   height_gui=$(echo $(( height * 15 + ${#@} * 20 + 100 )))
   height_gui_buttons=$(echo $(( height * 15 )))
-  if [[ "${#@}" == "2" ]];then
+  if [ "${#@}" == "2" ];then
     echo -e "$1" |  yad --fixed --no-escape --undecorated --show-uri --center --image "dialog-information" --borders="20" --title "User Info Prompt" \
-    --text-info --fontname="@font@ 11" --wrap --width=800 --height=$height_gui --window-icon="${DIRECTORY}/apps/XMRig/icon-64.png" \
+    --text-info --fontname="@font@ 11" --wrap --width=800 --height=$height_gui --window-icon="$(dirname "$0")/icon-64.png" \
     --show-uri \
     --button="$2":0
     output="$2"
-  elif [[ "${#@}" == "3" ]];then
+  elif [ "${#@}" == "3" ];then
     yad --image "dialog-question" \
-    --borders="20" --height=$height_gui_buttons --center --fixed\
-    --window-icon=${DIRECTORY}/apps/XMRig/icon-64.png \
+    --borders="20" --height=$height_gui_buttons --center --fixed \
+    --window-icon="$(dirname "$0")/icon-64.png" \
     --text="$1" \
     --button="$2":0 \
     --button="$3":1
-    if [[ $? -ne 0 ]]; then
+    if [ $? -ne 0 ]; then
     output="$3"
     else
     output="$2"
@@ -33,7 +33,7 @@ function userinput_func {
     output=$(
     yad --no-escape --undecorated --center \
       --borders="20" --height=$height_gui\
-      --window-icon="${DIRECTORY}/apps/XMRig/icon-64.png" \
+      --window-icon="$(dirname "$0")/icon-64.png" \
       --text "$1" \
       --list \
       --no-headers \
@@ -44,105 +44,77 @@ function userinput_func {
       --column "Selection" \
       --print-column=2 \
       --separator='' \
-      --button="Ok":0 \
+      --button="OK":0 \
       "${uniq_selection[@]}"
     )
   fi
 }
 
-function userinput_text_func {
-  yad --window-icon="${DIRECTORY}/apps/XMRig/icon-64.png" --center --wrap --text "$1" --entry --button="Ok":0
-}
-
 default_table=("Yes" "No")
 
-function config_helper() {
-    # Set mining pool
-
-    check=0
-    until [ "$check" == "1" ]; do
-        pool_pref=$(userinput_text_func "What mining pool do you want to use?  Example: gulf.moneroocean.stream:10032")
-        userinput_func "Your mining pool will be set to ${pool_pref}. Is this ok?" "${default_table[@]}"
-        case $output in
-        Yes)
-            check=1
-            status_green "Your pool is now set to ${pool_pref}. You can change this by editing the '\"url\":' field in '$HOME/.config/xmrig.json.'."
-            ;;
-        No) check=0 ;;
-        *)
-            check=0
-            echo 'Invalid input! Please answer y/n, or yes/no.'
-            ;;
-        esac
-    done
-
-    # Set SSL/TLS options
-
-    userinput_func "Does your mining pool support SSL/TLS? If you don't know what this is, just say no." "${default_table[@]}"
-    case $output in
-    Yes)
-        tls="true"
-        status_green "Your config now has SSL/TLS enabled. You can change this by editing the '\"tls\":' field in '$HOME/.config/xmrig.json.'."
-        ;;
-    *) tls="false" ;;
-    esac
-
-    # Set keepalive options
-
-    userinput_func "Does your mining pool support keepalived packets? If you don't know what this is, just say no." "${default_table[@]}"
-    case $output in
-    Yes)
-        keepalived="true"
-        status_green "Your config now has keepalived packets enabled. You can change this by editing the '\"keepalive\":' field in '$HOME/.config/xmrig.json'."
-        ;;
-    *) keepalived="false" ;;
-    esac
-
-    # Set Wallet Address
-
-    check=0
-    until [ "$check" == "1" ]; do
-        wallet_address=$(userinput_text_func "What is your Wallet Address? This will only be used in $HOME/xmrig/bullseye/root/.config/xmrig.json.")
-        userinput_func "Your Wallet Address will be set to $wallet_address. Is this ok?" "${default_table[@]}"
-        case $output in
-        Yes)
-            check=1
-            status_green "Your Wallet Address is now set to ${wallet_address}. You can change this by editing the '\"user\":' field in '$HOME/.config/xmrig.json'."
-            ;;
-        No) check=0 ;;
-        *)
-            check=0
-            echo 'Invalid input! Please answer y/n, or yes/no.'
-            ;;
-        esac
-    done
-
-    # Set miner name
-
-    check=0
-    userinput_func "Do you want to name your Miner?" "${default_table[@]}"
-    if [ "$output" == "Yes" ]; then
-        until [ "$check" == "1" ]; do
-            miner_name=$(userinput_text_func "What to you want to name your Miner?")
-            userinput_func "Your Miner's name will be ${miner_name}. Is this ok?" "${default_table[@]}"
-            case $output in
-            Yes)
-                check=1
-                status_green "Your Miner's name is now set to ${miner_name}. You can change this by editing the '\"rig-id\":' field in '$HOME/.config/xmrig.json'."
-                ;;
-            No) check=0 ;;
-            *)
-                check=0
-                echo 'Invalid input! Please answer y/n, or yes/no.'
-                ;;
-            esac
-        done
+function setup_wizard() {
+  
+  #For the setup wizard window, set initial values. Either these are the default, or derived from the config file.
+  miner_name="${USER^}"
+  wallet_address="42ppvRzPoJhUeTfW4xUNwWGBn36ssqhjFZqwCmqdmXHW6aG5rESJLzE1uHCXyZjgdLPD23Zng3AN6AEWtEBCVjUfDs3DvgV"
+  mining_pool="gulf.moneroocean.stream:10032"
+  tls=false
+  keepalive=false
+  
+  while true;do
+    #tls and keepalive lines are a yes/no format. Make the options list for them.
+    if [ "$tls" == false ];then
+      local tls_options='Disabled!Supported by mining pool'
     else
-        status "You chose not to name your Miner. If you change your mind, you can edit the '\"rig-id\":' line in '$HOME/.config/xmrig.json'. Continuing..."
+      local tls_options='Supported by mining pool!Disabled'
     fi
-    # copy the settings to xmrig.json
-
-    cat <<EOT | tee $HOME/xmrig/xmrig.json 1>&2 || error 'Failed to create $HOME/xmrig/xmrig.json!'
+    
+    if [ "$keepalive" == false ];then
+      local keepalive_options='Disabled!Supported by mining pool'
+    else
+      local keepalive_options='Supported by mining pool!Disabled'
+    fi
+    
+    #One window to choose everything
+    local output
+    output="$(yad --center --no-escape --form --separator='\n' \
+      --title="Create miner config" \
+      --window-icon="$(dirname "$0")/icon-64.png" \
+      --button="Skip this setup":1 \
+      --button=OK:0 \
+      --field="Name your miner" "$miner_name" \
+      --field="Wallet address" "$wallet_address" \
+      --field="Mining pool" "$mining_pool" \
+      --field="SSL/TLS:CB" "$tls_options" \
+      --field="Keepalive packets:CB" "$keepalive_options")"
+    local button=$?
+    
+    if [ $button == 0 ];then
+      miner_name="$(sed -n 1p <<<"$output")"
+      wallet_address="$(sed -n 2p <<<"$output")"
+      mining_pool="$(sed -n 3p <<<"$output")"
+      tls="$(sed -n 4p <<<"$output" | sed 's/Disabled/false/' | sed 's/Supported by mining pool/true/')"
+      keepalive="$(sed -n 5p <<<"$output" | sed 's/Disabled/false/' | sed 's/Supported by mining pool/true/')"
+      
+      if [ -z "$wallet_address" ];then
+        warning "Wallet address cannot be left blank!"
+      elif [ -z "$mining_pool" ];then
+        warning "Mining pool cannot be left blank!"
+      else
+        local save_settings='yes'
+        break
+      fi
+    else
+      local save_settings='no'
+      break
+    fi
+  done
+  
+  if [ "$save_settings" == 'yes' ];then
+    # Save choices to xmrig.json
+    status "Saving to $HOME/.config/xmrig.json"
+    echo "Contents of file:"
+    cat <<EOT | tee $HOME/.config/xmrig.json 1>&2 || error 'Failed to create $HOME/.config/xmrig.json!'
 {
     "autosave": true,
     "cpu": true,
@@ -151,50 +123,82 @@ function config_helper() {
     "rx": [-1, -1],
     "pools": [
         {
-            "url": "${pool_pref}",
+            "url": "${mining_pool}",
             "user": "${wallet_address}",
             "rig-id": "${miner_name}",
-            "keepalive": ${keepalived},
+            "keepalive": ${keepalive},
             "tls": ${tls}
         }
     ]
 }
 EOT
-    cp $HOME/xmrig/xmrig.json $HOME/.config/xmrig.json || error "Failed to copy 'xmrig.json' to '$HOME/.config/xmrig.json'!"
-    status_green 'Done!'
-
-} # End config_helper()
+  else #User skipped setup wizard
+    echo -e "You chose to not set up a configuration for xmrig."
+  fi
+  
+} # End setup_wizard()
 
 cd
-install_packages git build-essential cmake libuv1-dev libssl-dev libhwloc-dev yad || exit 1
 rm -rf $HOME/xmrig
-git_clone --branch v$version https://github.com/xmrig/xmrig || error 'Failed to clone repository!'
-mkdir $HOME/xmrig/build; cd $HOME/xmrig/build || error 'Failed to create and cd into build directory!'
-cmake .. || error 'Failed to generate build files!'
-make -j"$(nproc)" || error 'Failed to build XMRig!'
-sudo cp $HOME/xmrig/build/xmrig /usr/local/bin/xmrig || error "Failed to copy 'xmrig' executable to '/usr/local/bin/xmrig'!!"
-output=""
-if [ -e $HOME/xmrig.json.bak ]; then
-    userinput_func "Do you want to use your previous 'xmrig.json'?" "${default_table[@]}"
-    if [ "$output" == "Yes" ]; then
-        status "\nCopying old 'xmrig.json' to xmrig folder..."
-        cp $HOME/xmrig.json.bak $HOME/xmrig/xmrig.json || error "Failed to copy '$HOME/xmrig.json.bak' to '$HOME/xmrig/xmrig.json'!!"
-        mkdir -p $HOME/.config
-        sudo cp $HOME/xmrig.json.bak $HOME/.config/xmrig.json || error "Failed to copy '$HOME/xmrig.json.bak' to '$HOME/.config/xmrig.json'!!"
-        rm $HOME/xmrig.json.bak &>/dev/null
-    else
-        status '\nI won'\''t use the previous config...'
-        use_old_config="no"
-    fi
-elif [ "$use_old_config" == "no" ] || [ ! -e $HOME/xmrig.json.bak ]; then
-    userinput_func "Do you want to setup your xmrig.json? This will make running xmrig easier." "${default_table[@]}"
-    if [ "$output" == "Yes" ]; then
-        status_green "\nStarting helper..."
-        config_helper
-    else
-        status '\nI won'\''t run the config helper...'
-    fi
+
+#Compile xmrig; set to false to skip compilation
+if false;then
+  install_packages git build-essential cmake libuv1-dev libssl-dev libhwloc-dev yad || exit 1
+  
+  git_clone https://github.com/MoneroOcean/xmrig || error 'Failed to clone repository!'
+  
+  mkdir $HOME/xmrig/build; cd $HOME/xmrig/build || error 'Failed to create and cd into build directory!'
+  
+  #Optimize for specific CPU architecture, if detected. Get full list with 'gcc --target-help -mtune=foo' 
+  if lscpu | grep -q Cortex-A72 ;then
+    #Host device is using cortex-a72 CPU - this includes Pi4
+    mtune='-mtune=cortex-a72'
+  elif lscpu | grep -q Cortex-A53 ;then
+    #Host device is using cortex-a53 CPU - this includes Pi3
+    mtune='-mtune=cortex-a53'
+  fi
+  
+  if [ "$arch" == 32 ];then
+    DARM_TARGET=7
+  elif [ "$arch" == 64 ];then
+    DARM_TARGET=8
+  else
+    error "Failed to detect OS CPU architecture! Something is very wrong."
+  fi
+  
+  #Cmake flags:
+  # -O3: enables many performance optimizations at the expense of compilation time. From: https://www.youtube.com/watch?v=4e0fRKHG7Hk
+  # -mtune: tunes the program for current system's detected CPU. From: https://github.com/xmrig/xmrig/issues/446#issuecomment-373450600
+  # -ffast-math: speeds up math and seems to be stable for xmrig.
+  # -funsafe-loop-optimizations: Assume no overflowing loops
+  # -DARM_TARGET: selects ARM processor major architecture - either 7 or 8
+  
+  cmake .. -O3 -DCMAKE_CXX_FLAGS="$mtune -ffast-math -funsafe-loop-optimizations" -DARM_TARGET="$DARM_TARGET" || error 'Failed to generate build files!'
+  #More cmake flags that are specific to xmrig can be found at: https://xmrig.com/docs/miner/cmake-options
+  
+  #compile
+  make -j"$(nproc)" || error 'Failed to build XMRig!'
+  
+  #move binary to /usr/local/bin
+  sudo cp $HOME/xmrig/build/xmrig /usr/local/bin/xmrig || error "Failed to copy 'xmrig' executable to '/usr/local/bin/xmrig'!!"
+  
+  #No need to keep the xmrig git repo anymore
+  rm -rf $HOME/xmrig
 fi
 
-status_green "\nAll done!"
-status "\n\nIf you chose to run the config helper, you can now run XMRig by running 'xmrig' in your Terminal.\nIf you didn't (set up a config), then you'll need to use flags to specify your Wallet Address, Rig ID, and so forth.\nHave fun!"
+output=""
+if [ -s $HOME/.config/xmrig.json ];then
+  userinput_func "$HOME/.config/xmrig.json already exists. Do you want to use this configuration?" "${default_table[@]}"
+  if [ "$output" == "No" ]; then
+    setup_wizard #User may decide to 'skip' setup, in which case the pre-existing configuration will still be intact
+  fi
+  
+else #xmrig.json does not exist or is zero size, so run setup wizard
+  setup_wizard
+fi
+
+if [ -s $HOME/.config/xmrig.json ];then
+  status "\nYou can run 'xmrig' in your Terminal to start the miner.\nOtherwize, you can use command-line flags to specify Wallet Address, mining pool, and so forth.\nHave fun!"
+else
+  status "\nSince you don't have a configuration yet, you can either create one later at '$HOME/.config/xmrig.json', or run 'xmrig' with command-line flags specify Wallet Address, mining pool, and so forth.\nHave fun!"
+fi
