Fix single-quoted variables, and couple other edits

diff --git a/apps/XMRig/install-32 b/apps/XMRig/install-32
--- a/apps/XMRig/install-32
+++ b/apps/XMRig/install-32
@@ -151,7 +151,7 @@ function config_helper() {
     fi
     # copy the settings to xmrig.json
 
-    cat <<EOT | tee $HOME/xmrig/xmrig.json 1>&2 || error 'Failed to create $HOME/xmrig/xmrig.json!'
+    cat <<EOT | tee $HOME/xmrig/xmrig.json 1>&2 || error "Failed to create '$HOME/xmrig/xmrig.json'!"
 {
     "autosave": true,
     "cpu": true,
@@ -221,17 +221,17 @@ if [ -d "$HOME/xmrig" ]; then
         case "$output" in
         Delete)
             if [ -e "$HOME/xmrig/xmrig.json" ]; then 
-                status 'Creating backup of '\''$HOME/xmrig/xmrig.json'\'' to $HOME/xmrig.json.bak...'
-                cp $HOME/xmrig/xmrig.json $HOME/xmrig.json.bak 1>&2 || sudo cp $HOME/xmrig/xmrig.json $HOME/xmrig.json.bak || error 'Failed to create a backup of '\''$HOME/xmrig/xmrig.json'\''!'
+                status "Creating backup of '$HOME/xmrig/xmrig.json' to $HOME/xmrig.json.bak..."
+                cp $HOME/xmrig/xmrig.json $HOME/xmrig.json.bak 1>&2 || sudo cp $HOME/xmrig/xmrig.json $HOME/xmrig.json.bak || error "Failed to create a backup of '$HOME/xmrig/xmrig.json'!"
                 status_green 'Done!'
             else
                 warning "No 'xmrig.json' found! Not backing up... Continuing in ten seconds..."; sleep 10
             fi
             status "Removing '$HOME/xmrig'..."
-            sudo rm -rf $HOME/xmrig || error 'I was not able to remove '\''$HOME/xmrig'\''!'
+            sudo rm -rf $HOME/xmrig || error "I was not able to remove '$HOME/xmrig'!"
             status_green 'Done!'
-            status 'Creating new '\''$HOME/xmrig'\'' directory...'
-            mkdir -p $HOME/xmrig/ || error 'I was not able to create '\''$HOME/xmrig'\''!'
+            status "Creating new '$HOME/xmrig' directory..."
+            mkdir -p $HOME/xmrig/ || error "I was not able to create '$HOME/xmrig'!"
             status_green 'Done!'
             status 'Starting debootstrap... This next part will take a while.\n'
             sudo debootstrap --variant=buildd --arch arm64 bullseye $HOME/xmrig/bullseye http://ftp.us.debian.org/debian/ || error 'Failed to debootstrap chroot environment!!!'
@@ -255,7 +255,7 @@ if [ -d "$HOME/xmrig" ]; then
 fi
 sudo mkdir -p $chroot_dir/home/$USER/ $chroot_dir/root/.config || error 'Failed to create folders in chroot!'
 sudo cp /etc/resolv.conf $chroot_dir/etc/resolv.conf || error 'Failed to copy '\''/etc/resolv.conf'\'' into chroot environment!'
-echo "export LANG=C" | sudo tee --append $HOME/xmrig/bullseye/etc/.bashrc 1>&2 || error 'Failed to echo '\''export LANG=C'\'' to chroot environment\''s .bashrc'
+echo "export LANG=C" | sudo tee --append $HOME/xmrig/bullseye/etc/.bashrc 1>&2 || error 'Failed to echo '\''export LANG=C'\'' to chroot environment'\''s .bashrc'
 
 status 'Generating chroot XMRig install script...'
 sudo rm $chroot_dir/chroot-xmrig-inst.sh &>/dev/null && sudo touch $chroot_dir/chroot-xmrig-inst.sh
@@ -282,7 +282,7 @@ cmake .. || error 'Failed to generate build files!'
 make -j$(nproc) || error 'Failed to build XMRig!'
 cp xmrig /usr/bin/xmrig || error 'Failed to copy xmrig onto PATH!'
 EOT
-sudo chmod 775 $chroot_dir/chroot-xmrig-inst.sh || error 'Failed to make '\''$chroot_dir/chroot-xmrig-inst.sh'\'' executable!'
+sudo chmod 775 $chroot_dir/chroot-xmrig-inst.sh || error "Failed to make '$chroot_dir/chroot-xmrig-inst.sh' executable!"
 status_green 'Done.'
 
 # Run install script
diff --git a/apps/XMRig/install-64 b/apps/XMRig/install-64
--- a/apps/XMRig/install-64
+++ b/apps/XMRig/install-64
@@ -62,7 +62,6 @@ function config_helper() {
     check=0
     until [ "$check" == "1" ]; do
         pool_pref=$(userinput_text_func "What mining pool do you want to use?  Example: gulf.moneroocean.stream:10032")
-        table=("Yes" "No")
         userinput_func "Your mining pool will be set to ${pool_pref}. Is this ok?" "${default_table[@]}"
         case $output in
         Yes)
@@ -168,9 +167,9 @@ EOT
 cd
 install_packages git build-essential cmake libuv1-dev libssl-dev libhwloc-dev || exit 1
 git_clone --branch v$version https://github.com/xmrig/xmrig || error 'Failed to clone repository!'
-mkdir $HOME/xmrig/build && cd $HOME/xmrig/build || error 'Failed to create and cd into build directory!'
+mkdir $HOME/xmrig/build; cd $HOME/xmrig/build || error 'Failed to create and cd into build directory!'
 cmake .. || error 'Failed to generate build files!'
-make -j$(nproc) || error 'Failed to build XMRig!'
+make -j"$(nproc)" || error 'Failed to build XMRig!'
 sudo cp $HOME/xmrig/build/xmrig /usr/bin/xmrig || error "Failed to copy 'xmrig' executable to '/usr/bin/xmrig'!!"
 
 if [ -e $HOME/xmrig.json.bak ]; then
