Update install-64
fixes/updates

diff --git a/apps/XMRig/install-64 b/apps/XMRig/install-64
--- a/apps/XMRig/install-64
+++ b/apps/XMRig/install-64
@@ -65,9 +65,15 @@ function config_helper() {
         table=("Yes" "No")
         userinput_func "Your mining pool will be set to ${pool_pref}. Is this ok?" "${default_table[@]}"
         case $output in
-            Yes) check=1; status_green "Your pool is now set to ${pool_pref}. You can change this by editing the '\"url\":' field in '$HOME/.config/xmrig.json.'." ;;
-            No) check=0 ;;
-            *) check=0; echo 'Invalid input! Please answer y/n, or yes/no.' ;;
+        Yes)
+            check=1
+            status_green "Your pool is now set to ${pool_pref}. You can change this by editing the '\"url\":' field in '$HOME/.config/xmrig.json.'."
+            ;;
+        No) check=0 ;;
+        *)
+            check=0
+            echo 'Invalid input! Please answer y/n, or yes/no.'
+            ;;
         esac
     done
 
@@ -75,18 +81,23 @@ function config_helper() {
 
     userinput_func "Does your mining pool support SSL/TLS? If you don't know what this is, just say no." "${default_table[@]}"
     case $output in
-        Yes) tls="true"; status_green "Your config now has SSL/TLS enabled. You can change this by editing the '\"tls\":' field in '$HOME/.config/xmrig.json.'." ;;
-        *) tls="false";;
+    Yes)
+        tls="true"
+        status_green "Your config now has SSL/TLS enabled. You can change this by editing the '\"tls\":' field in '$HOME/.config/xmrig.json.'."
+        ;;
+    *) tls="false" ;;
     esac
 
     # Set keepalive options
 
     userinput_func "Does your mining pool support keepalived packets? If you don't know what this is, just say no." "${default_table[@]}"
     case $output in
-        Yes) keepalived="true"; status_green "Your config now has keepalived packets enabled. You can change this by editing the '\"keepalive\":' field in '$HOME/.config/xmrig.json'." ;;
-        *) keepalived="false" ;;
+    Yes)
+        keepalived="true"
+        status_green "Your config now has keepalived packets enabled. You can change this by editing the '\"keepalive\":' field in '$HOME/.config/xmrig.json'."
+        ;;
+    *) keepalived="false" ;;
     esac
-
 
     # Set Wallet Address
 
@@ -95,9 +106,15 @@ function config_helper() {
         wallet_address=$(userinput_text_func "What is your Wallet Address? This will only be used in $HOME/xmrig/bullseye/root/.config/xmrig.json.")
         userinput_func "Your Wallet Address will be set to $wallet_address. Is this ok?" "${default_table[@]}"
         case $output in
-            Yes) check=1; status_green "Your Wallet Address is now set to ${wallet_address}. You can change this by editing the '\"user\":' field in '$HOME/.config/xmrig.json'." ;;
-            No) check=0 ;;
-            *) check=0; echo 'Invalid input! Please answer y/n, or yes/no.' ;;
+        Yes)
+            check=1
+            status_green "Your Wallet Address is now set to ${wallet_address}. You can change this by editing the '\"user\":' field in '$HOME/.config/xmrig.json'."
+            ;;
+        No) check=0 ;;
+        *)
+            check=0
+            echo 'Invalid input! Please answer y/n, or yes/no.'
+            ;;
         esac
     done
 
@@ -110,18 +127,23 @@ function config_helper() {
             miner_name=$(userinput_text_func "What to you want to name your Miner?")
             userinput_func "Your Miner's name will be ${miner_name}. Is this ok?" "${default_table[@]}"
             case $output in
-                Yes) check=1; status_green "Your Miner's name is now set to ${miner_name}. You can change this by editing the '\"rig-id\":' field in '$HOME/.config/xmrig.json'." ;;
-                No) check=0 ;;
-                *) check=0; echo 'Invalid input! Please answer y/n, or yes/no.' ;;
+            Yes)
+                check=1
+                status_green "Your Miner's name is now set to ${miner_name}. You can change this by editing the '\"rig-id\":' field in '$HOME/.config/xmrig.json'."
+                ;;
+            No) check=0 ;;
+            *)
+                check=0
+                echo 'Invalid input! Please answer y/n, or yes/no.'
+                ;;
             esac
         done
     else
         status "You chose not to name your Miner. If you change your mind, you can edit the '\"rig-id\":' line in '$HOME/.config/xmrig.json'. Continuing..."
     fi
+    # copy the settings to xmrig.json
 
-    # copy the settings to $HOME/.config/xmrig.json.
-
-    cat << EOT | sudo tee $HOME/.config/xmrig.json || error '$HOME/.config/xmrig.json!'
+    cat <<EOT | tee $HOME/xmrig/xmrig.json 1>&2 || error 'Failed to create $HOME/xmrig/xmrig.json!'
 {
     "autosave": true,
     "cpu": true,
@@ -138,10 +160,12 @@ function config_helper() {
     ]
 }
 EOT
+    cp $HOME/xmrig/xmrig.json $HOME/.config/xmrig.json || error "Failed to copy 'xmrig.json' to '$HOME/.config/xmrig.json'!"
+    status_green 'Done!'
 
 } # End config_helper()
 
-cd $HOME
+cd
 install_packages git build-essential cmake libuv1-dev libssl-dev libhwloc-dev || exit 1
 git_clone --branch v$version https://github.com/xmrig/xmrig || error 'Failed to clone repository!'
 mkdir $HOME/xmrig/build && cd $HOME/xmrig/build || error 'Failed to create and cd into build directory!'
@@ -156,3 +180,27 @@ if [ "$output" == "Yes" ]; then
 else
     status '\nI won'\''t run the config helper...'
 fi
+
+if [ -e $HOME/xmrig.json.bak ]; then
+    userinput_func "Do you want to use your previous 'xmrig.json'?" default_table
+    if [ "$output" == "Yes" ]; then
+        status "\nCopying old 'xmrig.json' to chroot..."
+        cp $HOME/xmrig.json.bak $HOME/xmrig/xmrig.json
+        sudo cp $HOME/xmrig.json.bak $HOME/xmrig/bullseye/root/.config/xmrig.json
+        rm $HOME/xmrig.json.bak
+    else
+        status '\nI won'\''t use the previous config...'
+        use_old_config="no"
+    fi
+elif [ "$use_old_config" == "no" ] || [ ! -e $HOME/xmrig.json.bak ]; then
+    userinput_func "Do you want to setup your xmrig.json? This will make running xmrig easier." default_table
+    if [ "$output" == "Yes" ]; then
+        status_green "\nStarting helper..."
+        config_helper
+    else
+        status '\nI won'\''t run the config helper...'
+    fi
+fi
+
+status_green "\nAll done!"
+status "\n\nIf you chose to run the config helper, you can now run XMRig by running 'xmrig' in from your Terminal.\nIf you didn't (set up a config), then you'll need to use flags to specify your Wallet Address, Rig ID, and so forth.\nHave fun!"
