Update uninstall

diff --git a/apps/XMRig/uninstall b/apps/XMRig/uninstall
--- a/apps/XMRig/uninstall
+++ b/apps/XMRig/uninstall
@@ -1,11 +1,10 @@
 #!/bin/bash
 
+purge_packages || exit 1
+sudo rm -f /usr/local/bin/xmrig /usr/local/bin/xmrig-chroot
+
 if [ "$1" == "update" ]; then
-purge_packages || exit 1
-sudo rm /usr/local/bin/xmrig
-status "Not removing the 'xmrig' folder because uninstall run from updater."
+  status "Not removing the 'xmrig' folder because uninstall run from updater."
 else
-purge_packages || exit 1
-sudo rm -rf $HOME/xmrig || error 'Failed to remove $HOME/xmrig dir!'
-sudo rm -f /usr/local/bin/xmrig &>/dev/null
+  sudo rm -rf $HOME/xmrig || error 'Failed to remove $HOME/xmrig dir!'
 fi
