Update uninstall
updates

diff --git a/apps/XMRig/uninstall b/apps/XMRig/uninstall
--- a/apps/XMRig/uninstall
+++ b/apps/XMRig/uninstall
@@ -1,4 +1,11 @@
 #!/bin/bash
+
+if [ "$1" == "update" ]; then
+purge_installed || exit 1
+sudo rm /usr/local/bin/xmrig || error 'Failed to remove "xmrig" command!'
+status "Not removing the 'xmrig' folder because uninstall run from updater."
+else
 purge_installed || exit 1
 rm -rf $HOME/xmrig || sudo rm -rf $HOME/xmrig || error 'Failed to remove $HOME/xmrig dir!'
 sudo rm /usr/local/bin/xmrig || error 'Failed to remove "xmrig" command!'
+fi
