snap store: run debug if snapd service fails

diff --git a/apps/Snap Store/install b/apps/Snap Store/install
--- a/apps/Snap Store/install
+++ b/apps/Snap Store/install
@@ -12,7 +12,14 @@ function error {
 sudo apt install -y snapd || error "APT failed to install snapd"
 
 sudo systemctl enable --now snapd.socket || error "Unable to enable snapd.socket"
-sudo systemctl start snapd.service || error "Unable to start snapd.service"
+sudo systemctl start snapd.service
+if [ !? != 0 ];then
+  echo "Unable to start snapd.service. Running debug..."
+  echo "Running 'systemctl status snapd.service'"
+  systemctl status snapd.service
+  exit 1
+fi
+
 sudo snap refresh
 sudo systemctl restart snapd.service || error "Unable to restart snapd.service"
 
