uninstall snap store: rm /var/snap/snap-store & skip if no snap
+sudo rm -rf

diff --git a/apps/Snap Store/uninstall b/apps/Snap Store/uninstall
--- a/apps/Snap Store/uninstall
+++ b/apps/Snap Store/uninstall
@@ -7,12 +7,15 @@ function error {
   exit 1
 }
 
-sudo snap remove snap-store || error "The snap command failed to uninstall snap-store\nPerhaps running this command would fix it?\nsudo apt install --reinstall snapd"
+sudo rm -rf /var/snap/snap-store
+if command -v snap >/dev/null ;then
+  sudo snap remove snap-store || error "The snap command failed to uninstall snap-store\nPerhaps running this command would fix it?\nsudo apt install --reinstall snapd"
 
 echo -e "\e[93mNote: To prevent removing user data, uninstalling the Snap Store app does not uninstall the snapd package!\nTo completely remove everything snap-related, run this command:
 
 sudo apt purge snapd\e[39m
 "
-sleep 3
-echo "Waiting 30 seconds..."
-sleep 30
+  
+else
+  echo "Warning: attempting to uninstall snap store but the snap command is not found. This script is exiting with 'success', as obviously nothing is installed."
+fi
