Fix precompiled kernel in Wine (x86)

diff --git a/apps/Wine (x86)/install-32 b/apps/Wine (x86)/install-32
--- a/apps/Wine (x86)/install-32
+++ b/apps/Wine (x86)/install-32
@@ -107,7 +107,7 @@ elif echo "$vmsplit_output" | grep -q "^CONFIG_VMSPLIT_2G=y" || echo "$vmsplit_o
       #extract precompiled kernel
       echo "Extracting prebuilt kernel..."
       sleep 0.5 # so user has time to read what is happening
-      unzip ~/rpi23_3g1g_kernel.zip || error "Failed to extract kernel!"
+      unzip ~/3g1g-rpi-kernel.zip || error "Failed to extract kernel!"
       cd linux || error "Failed to change folder to ~/linux!"
       #install the precompiled kernel
       export KERNEL=kernel7
@@ -117,7 +117,7 @@ elif echo "$vmsplit_output" | grep -q "^CONFIG_VMSPLIT_2G=y" || echo "$vmsplit_o
       sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
       sudo cp arch/arm/boot/zImage /boot/$KERNEL.img || error "Failed to copy kernel to /boot/$KERNEL.img!"
       cd
-      rm -rf linux
+      rm -rf linux ~/3g1g-rpi-kernel.zip
       #message
       echo -e "\e[1mIt appears the precompiled 3G/1G kernel has been installed successfully.\nPlease reboot and install the Wine app again.\e[0m"
       sleep infinity
