Wine: check for box86 command & error if ~/wine/bin/wine missing

diff --git a/apps/Wine (x86)/install-32 b/apps/Wine (x86)/install-32
--- a/apps/Wine (x86)/install-32
+++ b/apps/Wine (x86)/install-32
@@ -143,6 +143,10 @@ fi
 #install box86
 "${DIRECTORY}/manage" install-if-not-installed Box86 || error "Box86 failed to install somehow!"
 
+if ! command -v box86 >/dev/null ;then
+  error "Pi-Apps thinks Box86 is installed, however no command named 'box86' exists. Please install Box86 manually."
+fi
+
 pkill -9 wine
 sudo apt purge -y wine &>/dev/null &
 
@@ -157,6 +161,8 @@ wget https://twisteros.com/wine.tgz -O ~/wine.tgz || error 'Failed to download w
 tar zxf ~/wine.tgz || error 'Failed to extract wine!'
 rm ~/wine.tgz
 
+[ ! -f ~/wine/bin/wine ] && error "the wine.tgz extraction succeeded, but the file '$HOME/wine/bin/wine' is missing!"
+
 # Install
 #sudo ln -s ~/wine/bin/wine /usr/local/bin/wine
 sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
@@ -166,12 +172,6 @@ sudo ln -s ~/wine/bin/wineboot /usr/local/bin/wineboot
 echo "#!/bin/bash
 setarch linux32 -L $HOME/wine/bin/wine"' "$@"' | sudo tee /usr/local/bin/wine >/dev/null
 sudo chmod +x /usr/local/bin/wine /usr/local/bin/wineboot /usr/local/bin/wineserver /usr/local/bin/winecfg
-
-#winetricks pre-patched
-#see https://discord.com/channels/670543161525010442/736736690932285481/793931182302560277
-#sudo wget https://cdn.discordapp.com/attachments/736736690932285481/793931182249213972/winetricks -O /usr/local/bin/winetricks || error "Failed to get winetricks!"
-#winetricks patch (doesn't work)
-#sudo sed -i 's|echo "${arg%%=*}"=\""${arg#*=}"\"|echo ${arg%%=*}=\"${arg#*=}\"|g' /usr/local/bin/winetricks
 
 sudo wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -O /usr/local/bin/winetricks || error "Failed to download winetricks!"
 sudo chmod +x /usr/local/bin/winetricks
