Wine (x86): simplify and make SOC checking better
only check for VMSPLIT if the kernel is not 64bit (x86_64 for CI and aarch64 for intended pi-apps users)

SOC_ID as returned from the device tree must match bcm2836/bcm2837 to allow building the kernel using the written scripts

diff --git a/apps/Wine (x86)/install-32 b/apps/Wine (x86)/install-32
--- a/apps/Wine (x86)/install-32
+++ b/apps/Wine (x86)/install-32
@@ -1,41 +1,39 @@
 #!/bin/bash
-if grep -q ARMv7 /proc/cpuinfo ;then
-  hardware='pi3'
-elif grep -q ARMv6 /proc/cpuinfo ;then
-  hardware='pi0'
+if grep -q ARMv6 /proc/cpuinfo ;then
   error "Wine is not compatible with the Raspberry Pi Zero or other ARMv6 boards."
-else
-  hardware='pi4'
 fi
 
-if [ -e /boot/config-$(uname -r) ];then
-  vmsplit_output="$(cat /boot/config-$(uname -r) | grep VMSPLIT)"
-else
-  if [ ! -e /proc/config.gz ];then
-    sudo modprobe configs || exit 1
+kernel="$(uname -m)"
+if ! [[ "$kernel" =~ "64" ]]; then
+  if [ -e /boot/config-$(uname -r) ];then
+    vmsplit_output="$(cat /boot/config-$(uname -r) | grep VMSPLIT)"
+  else
     if [ ! -e /proc/config.gz ];then
-      error "/proc/config.gz does not exist after running sudo modprobe configs!"
+      sudo modprobe configs || exit 1
+      if [ ! -e /proc/config.gz ];then
+        error "/proc/config.gz does not exist after running sudo modprobe configs!"
+      fi
     fi
+    vmsplit_output="$(gunzip < /proc/config.gz | grep VMSPLIT)"
   fi
-  vmsplit_output="$(gunzip < /proc/config.gz | grep VMSPLIT)"
 fi
 if [ -z "$vmsplit_output" ];then
-  kernel="$(uname -m)"
-  if [ $kernel == aarch64 ];then
-    echo "No memory split information due to running a 64-bit kernel. Continuing..."
+  if [[ "$kernel" =~ "64" ]];then
+    status "No memory split information due to running a $kernel kernel. Continuing..."
   else
-    echo "No memory split information and not running a 64-bit kernel. Strange."
-    sleep 2
-    echo "Continuing..."
+    status "No memory split information and running a $kernel kernel. Strange."
+    status "Continuing..."
   fi
 elif echo "$vmsplit_output" | grep -q "^CONFIG_VMSPLIT_2G=y" || echo "$vmsplit_output" | grep -q "^# CONFIG_VMSPLIT_3G is not set" ;then
   
-  #ensure hardware is armv7 for kernel compiling to work
-  if [ "$hardware" != 'pi3' ];then
-    error "User error: This script is not capable of handling your $hardware board with a 2G/2G memory split.\nWhatever you did to get yourself into this situation, undo it and try installing Wine again."
-  #ensure /boot/config.txt exists to make sure this is a rpi board
-  elif [ ! -f /boot/config.txt ];then
-    error "User error: Your system is not currently compatible with Wine. It needs a kernel with 3G/1G memory split. This is easy to do: switch to the 64-bit kernel by adding a line to /boot/config.txt. However, that file does not exist. Most likely you are trying to use Pi-Apps on an unsupported device or operating system."
+  #ensure hardware is bcm2836/bcm2837 for kernel compiling to work
+  #note that bcm2709 dts has a compatible tag of bcm2836 so SOC_ID will be bcm2836
+  # obtain SOC_ID
+  get_model
+  if [ "$SOC_ID" == 'bcm2836' ] || [ "$SOC_ID" == 'bcm2837' ];then
+    true
+  else
+    error "User error: This script is not capable of handling your $SOC_ID soc with a 2G/2G memory split.\nWhatever you did to get yourself into this situation, undo it and try installing Wine again."
   fi
   
   #continue asking until valid answer
