no longer use box86-updater for anything

diff --git a/apps/Wine (x86)/install-32 b/apps/Wine (x86)/install-32
--- a/apps/Wine (x86)/install-32
+++ b/apps/Wine (x86)/install-32
@@ -131,11 +131,12 @@ fi
 
 #Past this point, the pi is running a Wine-compatible kernel.
 
-if [ ! -f /usr/local/bin/box86 ];then
-  echo 'Installing box86 first...'
-  wget -qO- https://raw.githubusercontent.com/Botspot/box86-updater/main/update-box86 | bash
-  if [ ! -f /usr/local/bin/box86 ];then
-    error "Box86 failed to install somehow!"
+#install box86
+if ! command -v box86 || [ "$(cat "${DIRECTORY}/data/status/Box86" 2>/dev/null)" != 'installed' ];then
+  echo 'Installing box86...'
+  "${DIRECTORY}/manage" install Box86 || error "Box86 failed to install somehow!"
+  if ! command -v box86 ;then
+    error "Box86 executable does not exist!"
   else
     echo "installed" > "${DIRECTORY}/data/status/Box86"
   fi
