Wine (x86): remove precompiled build and update dts directory for buildscript

diff --git a/apps/Wine (x86)/install-32 b/apps/Wine (x86)/install-32
--- a/apps/Wine (x86)/install-32
+++ b/apps/Wine (x86)/install-32
@@ -39,18 +39,16 @@ elif echo "$vmsplit_output" | grep -q "^CONFIG_VMSPLIT_2G=y" || echo "$vmsplit_o
 Wine will not work on such systems. What would you like to do?
 
 - Compile a 3G/1G kernel (several hours)
-- Install a precompiled 3G/1G kernel (about 2 minutes but might be outdated)
 - Exit now"
-    userinput_func "$description" "Compile 3G/1G kernel" "Install precompiled 3G/1G kernel" "Exit"
+    userinput_func "$description" "Compile 3G/1G kernel" "Exit"
   elif [ "$SOC_ID" == 'bcm2837' ];then
     description="You are using a kernel with a 2G/2G memory split.
 Wine will not work on such systems. What would you like to do?
 
 - Switch to the 64-bit kernel (about 2 minutes)
 - Compile a 3G/1G kernel (several hours)
-- Install a precompiled 3G/1G kernel (about 2 minutes but might be outdated)
 - Exit now"
-    userinput_func "$description" "Switch to a 64-bit kernel" "Compile 3G/1G kernel" "Install precompiled 3G/1G kernel" "Exit"
+    userinput_func "$description" "Switch to a 64-bit kernel" "Compile 3G/1G kernel" "Exit"
   else
     error "User error: This script is not capable of handling your $SOC_ID soc with a 2G/2G memory split.\nWhatever you did to get yourself into this situation, undo it and try installing Wine again."
   fi
@@ -96,7 +94,7 @@ Wine will not work on such systems. What would you like to do?
     #install
     echo "Copying new files to /boot/..."
     sudo make modules_install || error "sudo make modules_install failed!"
-    sudo cp arch/arm/boot/dts/*.dtb /boot/ || error "Failed to copy dtb files to /boot!"
+    sudo cp arch/arm/boot/dts/broadcom/*.dtb /boot/ || error "Failed to copy dtb files to /boot!"
     sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/ || error "Failed to copy overlays to /boot/overlays!"
     sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
     sudo cp arch/arm/boot/zImage /boot/$KERNEL.img || error "Failed to copy kernel to /boot/$KERNEL.img!"
@@ -108,33 +106,6 @@ Wine will not work on such systems. What would you like to do?
     
     #message
     echo -e "It appears the 3G/1G kernel has been built and installed successfully.\nPlease reboot and install the Wine app again."
-    sleep infinity
-  elif [ "$output" == "Install precompiled 3G/1G kernel" ];then
-    #install precompiled 3g/1g kernel
-    
-    #backup ~/linux if it exists
-    rm -rf ~/linux.bak
-    [ -e ~/linux ] && (echo "$HOME/linux already exists, moving it to $HOME/linux.bak" ; mv -f ~/linux ~/linux.bak)
-    #download precompiled kernel
-    cd $HOME
-    echo "Downloading precompiled kernel..."
-    wget https://github.com/Itai-Nelken/RPi-3g-1g-kernel-wine/releases/download/5/rpi23_3g1g_kernel.zip -O ~/3g1g-rpi-kernel.zip || error "Failed to download prebuilt kernel!"
-    #extract precompiled kernel
-    echo "Extracting prebuilt kernel..."
-    sleep 0.5 # so user has time to read what is happening
-    unzip ~/3g1g-rpi-kernel.zip || error "Failed to extract kernel!"
-    cd linux || error "Failed to change folder to ~/linux!"
-    #install the precompiled kernel
-    export KERNEL=kernel7
-    sudo make modules_install || error "sudo make modules_install failed!"
-    sudo cp arch/arm/boot/dts/*.dtb /boot/ || error "Failed to copy dtb files to /boot!"
-    sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/ || error "Failed to copy overlays to /boot/overlays!"
-    sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
-    sudo cp arch/arm/boot/zImage /boot/$KERNEL.img || error "Failed to copy kernel to /boot/$KERNEL.img!"
-    cd
-    rm -rf linux ~/3g1g-rpi-kernel.zip
-    #message
-    echo -e "\e[1mIt appears the precompiled 3G/1G kernel has been installed successfully.\nPlease reboot and install the Wine app again.\e[0m"
     sleep infinity
   else
     error "User error: exited."
