Steam: small updates pulled from L4T-Megascript
add alternative download link (other regions may block steamcdn-a.akamihd.net) and remove ~/Desktop/steam.desktop whenever it gets generated by steam (since it is incorrect and will not launch steam)

diff --git a/apps/Steam/install-64 b/apps/Steam/install-64
--- a/apps/Steam/install-64
+++ b/apps/Steam/install-64
@@ -26,7 +26,7 @@ fi
 
 echo "Installing steam.deb"
 # install_packages https://steamcdn-a.akamaihd.net/client/installer/steam.deb || error "Could not install steam deb"
-wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb -qO /tmp/steam.deb || error "Failed to download steam.deb"
+wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb -qO /tmp/steam.deb || wget https://repo.steampowered.com/steam/archive/stable/steam_latest.deb -O /tmp/steam.deb || error "Failed to download steam.deb"
 apt_lock_wait
 sudo apt install --no-install-recommends -y /tmp/steam.deb || error "Failed to install steam.deb"
 
@@ -35,7 +35,9 @@ sudo mkdir -p /usr/local/bin /usr/local/share/applications
 echo '#!/bin/bash
 export STEAMOS=1
 export STEAM_RUNTIME=1
-BOX64_LOG=1 BOX86_LOG=1 BOX64_EMULATED_LIBS=libmpg123.so.0 /usr/lib/steam/bin_steam.sh -no-cef-sandbox steam://open/minigameslist "$@"' | sudo tee /usr/local/bin/steam || error "Failed to create steam launch script"
+BOX64_LOG=1 BOX86_LOG=1 BOX64_EMULATED_LIBS=libmpg123.so.0 /usr/lib/steam/bin_steam.sh -no-cef-sandbox steam://open/minigameslist "$@"
+
+rm -f /home/${USER}/Desktop/steam.desktop' | sudo tee /usr/local/bin/steam || error "Failed to create steam launch script"
 
 # set execution bit
 sudo chmod +x /usr/local/bin/steam
