Steam app total overhaul

diff --git a/apps/Steam/install-32 b/apps/Steam/install-32
--- a/apps/Steam/install-32
+++ b/apps/Steam/install-32
@@ -9,27 +9,26 @@ function error {
 
 "${DIRECTORY}/pkg-install" "libappindicator1 libnm0" "$(dirname "$0")" || exit 1
 
-if [ "$(cat "$DIRECTORY/data/status/Box86")" != 'installed' ] && [ ! -f /usr/local/bin/twistver ];then
+if [ ! -f /usr/local/bin/box86 ];then
   echo 'Installing box86 first...'
-  "$DIRECTORY/manage" install Box86
+  wget -qO- https://raw.githubusercontent.com/Botspot/box86-updater/main/update-box86 | bash
+  if [ ! -f /usr/local/bin/box86 ];then
+    error "Box86 failed to install somehow!"
+  fi
 fi
 
 echo "Downloading steam.deb"
 wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb || error "Failed to download steam.deb!"
 
-echo "Extracting steam.deb"
-ar x steam.deb
+sudo dpkg -i ~/steam.deb || error "dpkg failed to install steam.deb!"
 
-echo "Installing files..."
-sudo tar xf data.tar.xz -C /
+rm ~/steam.deb
 
-echo "Edited steam script to run on Raspberry Pi..."
+echo "Editing steam script to run on Raspberry Pi..."
 sudo sed -i 's/set -e/set -e\nexport STEAMOS=1\nexport STEAM_RUNTIME=1/' /usr/lib/steam/bin_steam.sh
 
 echo "Creating a Steam config file so it will launch in Small Mode..."
-[ ! -e ~/.local/share/Steam/config ] && mkdir -p ~/.local/share/Steam/config
+mkdir -p ~/.local/share/Steam/config
 wget https://raw.githubusercontent.com/Botspot/Steam-RPi/main/DialogConfig.vdf -O ~/.local/share/Steam/config/DialogConfig.vdf
 
-echo "Cleaning up..."
-rm steam.deb control.tar.gz debian-binary data.tar.xz
 exit 0
