Steam: remove install-32 and add install-64 (#2276)
* Steam: remove install-32 and add install-64

closes https://github.com/Botspot/pi-apps/pull/653
closes https://github.com/Botspot/pi-apps/issues/1481

* add removal of Steam/install-32 to runonce

diff --git a/apps/Steam/uninstall b/apps/Steam/uninstall
--- a/apps/Steam/uninstall
+++ b/apps/Steam/uninstall
@@ -1,7 +1,12 @@
 #!/bin/bash
 
 purge_packages || exit 1
-sudo apt purge -y steam-launcher
+sudo dpkg -r steam-launcher || error "Failed to uninstall steam-launcher"
 
-sudo rm -rf /usr/bin/steam ~/.steam ~/.local/share/Steam /usr/lib/steam /usr/share/applications/steam.desktop /usr/share/doc/steam ~/Desktop/steam.desktop
-exit 0
+sudo rm -f /lib/udev/rules.d/60-steam-*.rules || error "Failed to remove /lib/udev/rules.d/60-steam-*.rules"
+sudo rm -rf /usr/local/bin/steam /usr/local/share/applications/steam.desktop /usr/share/applications/steam.desktop ~/Desktop/steam.desktop || error "Failed to remove steam files and folders"
+
+if [[ "$1" != "update" ]];then
+  # remove game downloads, saves, and cached files
+  sudo rm -rf ~/.steam ~/.local/share/Steam
+fi
