Chiaki: add ffmpeg dependency

diff --git a/apps/Chiaki/install b/apps/Chiaki/install
--- a/apps/Chiaki/install
+++ b/apps/Chiaki/install
@@ -1,9 +1,8 @@
 #!/bin/bash
 # install dependencies
-install_packages cmake python3-protobuf protobuf-compiler libavcodec-dev libopus-dev libsdl2-dev libssl-dev qtbase5-dev qtchooser qtmultimedia5-dev libqt5svg5-dev libqt5multimedia5-plugins libqt5opengl5-dev || error "Failed to install dependencies"
+install_packages ffmpeg cmake python3-protobuf protobuf-compiler libavcodec-dev libopus-dev libsdl2-dev libssl-dev qtbase5-dev qtchooser qtmultimedia5-dev libqt5svg5-dev libqt5multimedia5-plugins libqt5opengl5-dev || error "Failed to install dependencies"
 # install qt5-default if its availabe in apt (necessary on debian/ubuntu versions prior to bullseye/hirsute)
-package_available qt5-default
-if [[ $? == "0" ]]; then
+if package_available qt5-default ;then
   install_packages qt5-default || error "Failed to install dependencies"
 fi
 # install Chiaki
