add python3(or 2)-dev package whenever pip is installed
many of these scripts have been seen to fail when the python3-dev packages is missing (resulting in fatal error: Python.h: No such file or directory compilation errors when pip has to compile a package from source)

also update packages to use install_packages and purge_packages (where appropriate)

diff --git a/apps/Minecraft Pi (Modded)/install b/apps/Minecraft Pi (Modded)/install
--- a/apps/Minecraft Pi (Modded)/install
+++ b/apps/Minecraft Pi (Modded)/install
@@ -33,5 +33,5 @@ do
   esac
 done
 
-"${DIRECTORY}/pkg-install" "$MCPIL python3-pip" "$(dirname "$0")" || error "Failed to install ${MCPIL} and python3-pip packages!"
+install_packages $MCPIL python3-pip python3-dev || error "Failed to install dependencies"
 pip3 install mcpi || error "The pip3 command failed to install mcpi!"
