Fix install script for download

diff --git a/apps/Chesscoin/install b/apps/Chesscoin/install
--- a/apps/Chesscoin/install
+++ b/apps/Chesscoin/install
@@ -5,9 +5,25 @@ version=1.5.1
 #installs libfuse2
 enable_module fuse || exit 1
 
-wget -O /tmp/chesscoin-qt.AppImage https://github.com/AKKPP/ChessCoin032-Core-x64/releases/download/${version}/chesscoin-qt-v${version}-rpi5-aarch64.AppImage || error "Failed to download!"
-sudo mv -f /tmp/chesscoin-qt.AppImage /opt
-sudo chmod +x /opt/chesscoin-qt.AppImage
+
+
+# Download ZIP file
+wget -O /tmp/chesscoin-qt.zip "https://github.com/AKKPP/ChessCoin032-Core-x64/releases/download/v${version}/chesscoin-qt-v${version}-rpi5-aarch64.zip" || error "Failed to download!"
+
+# Unzip the file
+unzip -o /tmp/chesscoin-qt.zip -d /tmp/ || error "Failed to unzip!"
+
+# Move the extracted AppImage to /opt
+sudo mv -f /tmp/chesscoin-qt-v${version}-rpi5-aarch64/chesscoin-qt-aarch64.AppImage /opt/ || error "Failed to move AppImage!"
+
+# Set execution permissions
+sudo chmod +x /opt/chesscoin-qt-aarch64.AppImage || error "Failed to set permissions!"
+
+# Cleanup
+rm -f /tmp/chesscoin-qt.zip
+rm -rf /tmp/chesscoin-qt-v${version}-rpi5-aarch64
+
+echo "ChessCoin-Qt AppImage installed successfully!"
 
 sudo cp -f "$(dirname "$0")/icon-64.png" /usr/share/icons/hicolor/64x64/apps/chesscoin-qt.png || error "failed to copy icon"
 
@@ -18,13 +34,12 @@ sudo xdg-icon-resource forceupdate --mode system
 
 echo "[Desktop Entry]
 Type=Application
-Name=chesscoin-qt
-Exec=/opt/chesscoin-qt.AppImage
+Name=Chesscoin
+Exec=/opt/chesscoin-qt-aarch64.AppImage
 Icon=chesscoin-qt
 Hidden=false
 GenericName=chesscoin 0.32%%
 Comment=GUI application for Raspberry
 Terminal=false
 Categories=Office;
-StartupWMClass=chesscoin-qt
 Keywords=crypto;currency;XMR" | sudo tee /usr/share/applications/chesscoin-qt.desktop >/dev/null || error "Failed to create menu button!"
