optimize categoryedit
setting the directory variable and sourcing the api are not free.

only performing these actions if necessary brings the execution time from 0.110 sec to 0.085 sec

diff --git a/etc/categoryedit b/etc/categoryedit
--- a/etc/categoryedit
+++ b/etc/categoryedit
@@ -1,12 +1,18 @@
 #!/bin/bash
-DIRECTORY="$(readlink -f "$(dirname "$(dirname "$0")")")"
+
+if [ -z "$DIRECTORY" ]; then
+  DIRECTORY="$(readlink -f "$(dirname "$(dirname "$0")")")"
+fi
 
 function error {
   echo -e "\e[91m$1\e[39m"
   exit 1
 }
 
-source "${DIRECTORY}/api" || error "failed to source ${DIRECTORY}/api"
+#for read_category_files()
+if ! command -v read_category_files >/dev/null ;then
+  source "${DIRECTORY}/api" || error "failed to source ${DIRECTORY}/api"
+fi
 
 refresh() { #set the categories variable to the current categories
   categories="$(read_category_files)"
