Check Internet connection

diff --git a/etc/import-app b/etc/import-app
--- a/etc/import-app
+++ b/etc/import-app
@@ -105,7 +105,11 @@ if [[ "$import" == /* ]] ;then
   fi
   
 elif [[ "$import" == *'://'*'.zip' ]];then
+
   #given a download link to a zip file
+
+  #check for internet connection
+  ping -q -c1 google.com &>/dev/null || error "No internet connection!\ngoogle.com failed to respond.\nErrors: $(ping -q -c1 google.com 2>&1)" 
   
   #create a temporary directory to extract to
   tmpdir="$(mktemp -d)" || error "Failed to create a temporaty folder for some reason.\nErrors:\n$tmpdir"
@@ -122,6 +126,9 @@ elif [[ "$import" == *'://'*'.zip' ]];then
   
 elif [[ "$import" =~ ^[0-9]+$ ]] || [[ "$import" =~ *'://'*'/pull/'[0-9]+$ ]];then
   #given a pull request for an app
+  
+  #check for internet connection
+  ping -q -c1 google.com &>/dev/null || error "No internet connection!\ngoogle.com failed to respond.\nErrors: $(ping -q -c1 google.com 2>&1)" 
   
   #if given a PR number, assume it's a PR on the pi-apps repo
   if [[ "$import" =~ ^[0-9]+$ ]];then
