Update Tor to 11.0

diff --git a/apps/Tor/install-64 b/apps/Tor/install-64
--- a/apps/Tor/install-64
+++ b/apps/Tor/install-64
@@ -1,6 +1,6 @@
 #!/bin/bash
 rm -f ~/tor.tar.xz
-wget -O ~/tor.tar.xz https://sourceforge.net/projects/tor-browser-ports/files/10.5.8/tor-browser-linux-arm64-10.5.8_en-US.tar.xz/download || error "Failed to download!"
+wget -O ~/tor.tar.xz https://sourceforge.net/projects/tor-browser-ports/files/11.0/tor-browser-linux-arm64-11.0_en-US.tar.xz/download || error "Failed to download!"
 tar -xf ~/tor.tar.xz || error "Failed to extract!"
 rm -f ~/tor.tar.xz
 echo "[Desktop Entry]
