update tor-browser links

diff --git a/apps/Tor/install-32 b/apps/Tor/install-32
--- a/apps/Tor/install-32
+++ b/apps/Tor/install-32
@@ -1,6 +1,6 @@
 #!/bin/bash
 rm -f ~/tor.tar.xz
-wget -O ~/tor.tar.xz https://sourceforge.net/projects/tor-browser-ports/files/11.0/tor-browser-linux-armhf-11.0_en-US.tar.xz/download || error "Failed to download!"
+wget -O ~/tor.tar.xz https://versaweb.dl.sourceforge.net/project/tor-browser-ports/11.0.1/tor-browser-linux-armhf-11.0.1_en-US.tar.xz || error "Failed to download!"
 tar -xf ~/tor.tar.xz || error "Failed to extract!"
 rm -f ~/tor.tar.xz
 echo "[Desktop Entry]
