fixup debug logging so its compatible with all architecture in frtizing
also make the qmake error a User error:

diff --git a/apps/Fritzing/install b/apps/Fritzing/install
--- a/apps/Fritzing/install
+++ b/apps/Fritzing/install
@@ -11,12 +11,12 @@ fi
 
 # print debug output to terminal
 hash -r
-echo "Logging contents of file: /usr/lib/*-linux-gnu/qt-default/qtchooser/default.conf"
-cat /usr/lib/*-linux-gnu/qt-default/qtchooser/default.conf
-echo "Log file status: /usr/lib/*-linux-gnu/qt-default/qtchooser/default.conf"
-ls -l /usr/lib/*-linux-gnu/qt-default/qtchooser/default.conf
-echo "Logging contents of file: /usr/share/qtchooser/qt5-*-linux-gnu.conf"
-cat /usr/share/qtchooser/qt5-*-linux-gnu.conf
+echo "Logging contents of file: /usr/lib/*-linux-gnu*/qt-default/qtchooser/default.conf"
+cat /usr/lib/*-linux-gnu*/qt-default/qtchooser/default.conf
+echo "Log file status: /usr/lib/*-linux-gnu*/qt-default/qtchooser/default.conf"
+ls -l /usr/lib/*-linux-gnu*/qt-default/qtchooser/default.conf
+echo "Logging contents of file: /usr/share/qtchooser/qt5-*-linux-gnu*.conf"
+cat /usr/share/qtchooser/qt5-*-linux-gnu*.conf
 echo "Log qmake -v output"
 qmake -v
 
@@ -33,7 +33,7 @@ git clone https://github.com/fritzing/fritzing-app.git || error "Could not clone
 cd fritzing-app || error "Could not move to directory"
 git checkout 0.9.6
 sed -i 's/LIBGIT_STATIC = true/LIBGIT_STATIC = false/g' phoenix.pro
-qmake || error "PLEASE contact us in the Discord. We have seen multiple reports of this error and are unable to reproduce on our end. qmake failed on fritzing configure"
+qmake || error "User error: PLEASE contact us in the Discord. We have seen multiple reports of this error and are unable to reproduce on our end. qmake failed on fritzing configure"
 make -j$(nproc) || error "compilation failed"
 lupdate -noobsolete phoenix.pro
 lrelease -removeidentical phoenix.pro
