Powerline-Shell: use pipx, install globally, and bookworm compat
work towards https://github.com/Botspot/pi-apps/issues/2401

diff --git a/apps/Powerline-Shell/install b/apps/Powerline-Shell/install
--- a/apps/Powerline-Shell/install
+++ b/apps/Powerline-Shell/install
@@ -2,11 +2,24 @@
 
 install_packages python3 python3-pip python3-dev fonts-powerline fonts-fantasque-sans || exit 1
 
-sudo pip3 install powerline-shell || error "Failed to install powerline shell with pip3"
+if package_available pipx ;then
+  install_packages pipx python3-venv || exit 1
+elif package_available python3.8 ;then
+  install_packages python3.8 python3.8-venv || exit 1
+  sudo -H python3.8 -m pip install pipx || exit 1
+else
+  error "pipx is not available so cannot install powerline-shell to python venv"
+fi
 
-#Remove new powerline ~/.bashrc function if already there
+sudo PIPX_HOME=/usr/local/pipx PIPX_BIN_DIR=/usr/local/bin pipx install powerline-shell || error "Failed to install powerline shell with pipx"
+
+#Remove powerline-shell function from ~/.bashrc if already there
 sed -i '/powerline-shell/d' ~/.bashrc
+# Remove powerline-shell function from /etc/bash.bashrc if already there
+sudo sed -i '/powerline-shell/d' /etc/bash.bashrc
 
-#Add powerline to ~/.bashrc
-echo 'if [ $TERM != linux ] && [[ ! $PROMPT_COMMAND =~ "powerline-shell" ]]; then PROMPT_COMMAND="PS1="\"""\$"(powerline-shell)"\""; $PROMPT_COMMAND" ; fi' >> ~/.bashrc
-
+#Add powerline to /etc/bash.bashrc
+echo 'if [ $TERM != linux ] && [[ ! $PROMPT_COMMAND =~ "powerline-shell" ]]; then PROMPT_COMMAND="PS1="\"""\$"(powerline-shell)"\""; $PROMPT_COMMAND" ; fi' | sudo tee -a /etc/bash.bashrc > /dev/null || error "Could not modify /etc/bash.bashrc"
+#Also add to users ~/.bashrc . Some terminals (eg: gnome-terminal) overwrite the PROMPT_COMMAND with their own contents after /etc/bash.bashrc so is necessary for them
+#The following will only affect the current users install
+echo 'if [ $TERM != linux ] && [[ ! $PROMPT_COMMAND =~ "powerline-shell" ]]; then PROMPT_COMMAND="PS1="\"""\$"(powerline-shell)"\""; $PROMPT_COMMAND" ; fi' | tee -a ~/.bashrc > /dev/null || error "Could not modify ~/.bashrc"
