Powerline-Shell: fix font rendering issue and make bashrc line safer
All ASCII characters including the basic alphabet was rendered with
blank squares as a result of forcing lxterminal to use Fantasque Sans
Mono. Removing this config change allows lxterminal to choose its font
which works fine anyway.

diff --git a/apps/Powerline-Shell/install b/apps/Powerline-Shell/install
--- a/apps/Powerline-Shell/install
+++ b/apps/Powerline-Shell/install
@@ -1,5 +1,12 @@
 #!/bin/bash
-# Get dependencies
-install_packages python3 python3-pip python3-dev fonts-powerline fonts-fantasque-sans || error "Failed to install dependencies"
-wget -qO- https://raw.githubusercontent.com/techcoder20/RPI-PowerlineShell-Installer/main/install.sh | bash || error "install.sh failed!"
+
+install_packages python3 python3-pip python3-dev fonts-powerline fonts-fantasque-sans || exit 1
+
+sudo pip3 install powerline-shell || error "Failed to install powerline shell with pip3"
+
+#Remove new powerline ~/.bashrc function if already there
+sed -i '/powerline-shell/d' ~/.bashrc
+
+#Add powerline to ~/.bashrc
+echo 'if [ $TERM != linux ] && [[ ! $PROMPT_COMMAND =~ "powerline-shell" ]]; then PROMPT_COMMAND="PS1="\"""\$"(powerline-shell)"\""; $PROMPT_COMMAND" ; fi' >> ~/.bashrc
 
