Fixed Powerline Shell

diff --git a/apps/Powerline-Shell/install b/apps/Powerline-Shell/install
--- a/apps/Powerline-Shell/install
+++ b/apps/Powerline-Shell/install
@@ -1,5 +1,28 @@
 #!/bin/bash
-# Get dependencies
-install_packages python3 python3-pip python3-dev fonts-powerline fonts-fantasque-sans || error "Failed to install dependencies"
-wget -qO- https://raw.githubusercontent.com/techcoder20/RPI-PowerlineShell-Installer/main/install.sh | bash || error "install.sh failed!"
 
+# Uninstall Starship Prompt as it may cause issues
+"${DIRECTORY}/manage" uninstall 'Starship Prompt' 
+
+# Installing Dependencies
+install_packages python3 python3-pip python3-dev fonts-powerline fonts-fantasque-sans #No need to call for an "error"
+
+# Installing powerline shell with pip3
+sudo pip3 install powerline-shell || error "Failed to install Powerline-Shell"
+
+# Setting Fonts
+echo fontname >> ~/.config/lxterminal/lxterminal.conf
+sed -i '/fontname/c\fontname=Fantasque Sans Mono Bold 11' ~/.config/lxterminal/lxterminal.conf
+echo FontName >> ~/.config/xfce4/terminal/terminalrc
+sed -i '/FontName/c\FontName=Fantasque Sans Mono 12' ~/.config/xfce4/terminal/terminalrc
+
+# Removing powerline shell from ~/.bashrc if already there
+sed -i '/function _update_ps1() {/,/fi/{d}' ~/.bashrc
+
+# Adding powerline to ~/.bashrc
+echo '''function _update_ps1() {
+    PS1=$(powerline-shell $?)
+}
+
+if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
+    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
+fi ''' >> ~/.bashrc || error "Failed to set Powerline-Shell"
