Update apps/Pycharm CE/install
Co-authored-by: cycool29 <cycool29@gmail.com>

diff --git a/apps/Pycharm CE/install b/apps/Pycharm CE/install
--- a/apps/Pycharm CE/install
+++ b/apps/Pycharm CE/install
@@ -25,8 +25,8 @@ cd $HOME/fsnotifier-pycharm-rpi/
 bash ./make.sh || error "Failed to compile file watcher."
 mkdir -p $HOME/.config/JetBrains/PyCharmCE2021.3/options
 mv -f $HOME/fsnotifier-pycharm-rpi/fsnotifier $HOME/.config/JetBrains/PyCharmCE2021.3/ || error "Failed to move fsnotifier binary to $HOME/.config/JetBrains/PyCharmCE2021.3/."
-[ -a $HOME/.config/JetBrains/PyCharmCE2021.3.1/idea.properties ] && echo "$(cat $HOME/.config/JetBrains/PyCharmCE2021.3.1/idea.properties | grep -v idea.filewatcher.executable.path)" > $HOME/.config/JetBrains/PyCharmCE2021.3.1/idea.properties
-echo "idea.filewatcher.executable.path = $HOME/.config/JetBrains/PyCharmCE2021.3.1/fsnotifier" >> $HOME/.config/JetBrains/PyCharmCE2021.3.1/idea.properties || error "Failed to add file watcher executable path to $HOME/.config/JetBrains/PyCharmCE2021.3.1/idea.properties."
+[ -a $HOME/.config/JetBrains/PyCharmCE2021.3/idea.properties ] && echo "$(cat $HOME/.config/JetBrains/PyCharmCE2021.3/idea.properties | grep -v idea.filewatcher.executable.path)" > $HOME/.config/JetBrains/PyCharmCE2021.3/idea.properties
+echo "idea.filewatcher.executable.path = $HOME/.config/JetBrains/PyCharmCE2021.3/fsnotifier" >> $HOME/.config/JetBrains/PyCharmCE2021.3/idea.properties || error "Failed to add file watcher executable path to $HOME/.config/JetBrains/PyCharmCE2021.3/idea.properties."
 
 status "Remove bundled JRE version message ..."
 echo '<application>
