Pycharm: switch to unified version
the independent "Community Edition" was officially discontinued in https://blog.jetbrains.com/pycharm/2025/04/unified-pycharm/ and https://blog.jetbrains.com/pycharm/2025/12/pycharm-2025-3-unified-ide-jupyter-notebooks-in-remote-development-uv-as-default-and-more/

all users are to use the unified product now where pro/free can be selected in the software itself

this app should probably be renamed in pi-apps to reflect the change but I will leave that to a future commit.

diff --git a/apps/Pycharm CE/install-64 b/apps/Pycharm CE/install-64
--- a/apps/Pycharm CE/install-64
+++ b/apps/Pycharm CE/install-64
@@ -1,27 +1,27 @@
 #!/bin/bash
 
-version=2025.2.4
+version=2025.3.1.1
 
 install_packages python3-pip python3-dev || exit 1
 
-wget https://download.jetbrains.com/python/pycharm-community-${version}-aarch64.tar.gz -O pycharm-community.tar.gz || error "Failed to download pycharm-community.tar.gz"
-status "Extracting pycharm-community.tar.gz to /opt"
-sudo rm -rf /opt/pycharm-community && sudo mkdir -p /opt/pycharm-community
-sudo tar xzf pycharm-community.tar.gz -C /opt/pycharm-community || error "Failed to extract pycharm-community.tar.gz"
-sudo mv /opt/pycharm-community/*/* /opt/pycharm-community/
-sudo chmod +x /opt/pycharm-community/bin/pycharm.sh
+wget https://download.jetbrains.com/python/pycharm-$version-aarch64.tar.gz -O pycharm.tar.gz || error "Failed to download pycharm.tar.gz"
+status "Extracting pycharm.tar.gz to /opt"
+sudo rm -rf /opt/pycharm && sudo mkdir -p /opt/pycharm
+sudo tar xzf pycharm.tar.gz -C /opt/pycharm || error "Failed to extract pycharm.tar.gz"
+sudo mv /opt/pycharm/*/* /opt/pycharm/
+sudo chmod +x /opt/pycharm/bin/pycharm.sh
 
 status "Creating desktop shortcut ..."
 echo "[Desktop Entry]
 Type=Application
-Name=PyCharm Community Edition
+Name=PyCharm
 Icon=$(dirname "$0")/icon-64.png
-Exec=/opt/pycharm-community/bin/pycharm.sh
+Exec=/opt/pycharm/bin/pycharm.sh
 Comment=Python IDE
 Categories=Development;IDE;Programming;
 Terminal=false
-StartupWMClass=jetbrains-pycharm-ce
-StartupNotify=true" | sudo tee /usr/local/share/applications/jetbrains-pycharm-ce.desktop
+StartupWMClass=jetbrains-pycharm
+StartupNotify=true" | sudo tee /usr/local/share/applications/jetbrains-pycharm.desktop
 
 #cleanup
-rm -rf $HOME/pycharm-community.tar.gz $HOME/fsnotifier-pycharm-rpi  $HOME/fsnotifier-pycharm-rpi.zip
+sudo rm -rf $HOME/pycharm.tar.gz $HOME/fsnotifier-pycharm-rpi  $HOME/fsnotifier-pycharm-rpi.zip /usr/local/share/applications/jetbrains-pycharm-ce.desktop
diff --git a/apps/Pycharm CE/uninstall b/apps/Pycharm CE/uninstall
--- a/apps/Pycharm CE/uninstall
+++ b/apps/Pycharm CE/uninstall
@@ -4,8 +4,8 @@ purge_packages || exit 1
 
 rm_external_repo "adoptium"
 
-echo "Deleting /opt/pycharm-community directory"
-sudo rm -rf /opt/pycharm-community || error "Failed to delete /opt/pycharm-community directory"
-sudo rm -f ~/.local/share/applications/jetbrains-pycharm-ce.desktop /usr/local/share/applications/jetbrains-pycharm-ce.desktop
+echo "Deleting pycharm directory"
+sudo rm -rf /opt/pycharm-community /opt/pycharm || error "Failed to delete pycharm directory"
+sudo rm -f ~/.local/share/applications/jetbrains-pycharm-ce.desktop /usr/local/share/applications/jetbrains-pycharm-ce.desktop /usr/local/share/applications/jetbrains-pycharm.desktop
 # cleanup files leftover from potential failed install
-rm -rf $HOME/pycharm-community.tar.gz $HOME/pty4j $HOME/fsnotifier-pycharm-rpi  $HOME/fsnotifier-pycharm-rpi.zip
+rm -rf $HOME/pycharm-community.tar.gz $HOME/pycharm.tar.gz $HOME/pty4j $HOME/fsnotifier-pycharm-rpi  $HOME/fsnotifier-pycharm-rpi.zip
