Pycharm CE: use new aarch64 community edition download
contains bundled aarch64 JRE and JCEF

diff --git a/apps/Pycharm CE/install-64 b/apps/Pycharm CE/install-64
--- a/apps/Pycharm CE/install-64
+++ b/apps/Pycharm CE/install-64
@@ -2,177 +2,26 @@
 
 version=2022.3.2
 
-status "Installing Java 17"
-# first check if lsb_release has an upstream option -u
-# if not, check if there is an upstream-release file
-# if not, check if there is a lsb-release.diverted file
-# if not, assume that this is not a ubuntu derivative
-if lsb_release -a -u &>/dev/null; then
-  # This is a Ubuntu Derivative, checking the upstream-release version info
-  __os_id="$(lsb_release -s -i -u)"
-  __os_desc="$(lsb_release -s -d -u)"
-  __os_release="$(lsb_release -s -r -u)"
-  __os_codename="$(lsb_release -s -c -u)"
-elif [ -f /etc/upstream-release/lsb-release ]; then
-  # ubuntu 22.04+ linux mint no longer includes the lsb_release -u option
-  # add a parser for the /etc/upstream-release/lsb-release file
-  source /etc/upstream-release/lsb-release
-  __os_id="$DISTRIB_ID"
-  __os_desc="$DISTRIB_DESCRIPTION"
-  __os_release="$DISTRIB_RELEASE"
-  __os_codename="$DISTRIB_CODENAME"
-  unset DISTRIB_ID DISTRIB_DESCRIPTION DISTRIB_RELEASE DISTRIB_CODENAME
-elif [ -f /etc/lsb-release.diverted ]; then
-  # ubuntu 22.04+ popOS no longer includes the /etc/upstream-release/lsb-release or the lsb_release -u option
-  # add a parser for the new /etc/lsb-release.diverted file
-  source /etc/lsb-release.diverted
-  __os_id="$DISTRIB_ID"
-  __os_desc="$DISTRIB_DESCRIPTION"
-  __os_release="$DISTRIB_RELEASE"
-  __os_codename="$DISTRIB_CODENAME"
-  unset DISTRIB_ID DISTRIB_DESCRIPTION DISTRIB_RELEASE DISTRIB_CODENAME
-else
-  __os_id="$(lsb_release -s -i)"
-  __os_desc="$(lsb_release -s -d)"
-  __os_release="$(lsb_release -s -r)"
-  __os_codename="$(lsb_release -s -c)"
-fi
-case "$__os_id" in
-# Raspbian is not reported as a derivative of Debian (no /etc/upstream-release/lsb-release file)
-Raspbian | Debian)
-  case "$__os_codename" in
-  bullseye | buster)
-    install_packages lsb-release wget apt-transport-https gnupg || error "Failed to install dependencies"
-    hash -r
+install_packages python3-pip python3-dev || exit 1
 
-    status "Adding Adoptium repository:"
-
-    echo "- public key -> keyring"
-    rm -f /tmp/adoptium-public-key /tmp/adoptium-archive-keyring.gpg
-    wget -O /tmp/adoptium-public-key https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
-    gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --import /tmp/adoptium-public-key
-    rm -f /tmp/adoptium-public-key
-
-    echo " - keyring -> GPG key"
-    gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --export --output /tmp/adoptium-archive-keyring.gpg
-    rm -f /tmp/adoptium-keyring.gpg
-
-    echo " - Moving GPG key to /usr/share/keyrings"
-    sudo mv -f /tmp/adoptium-archive-keyring.gpg /usr/share/keyrings
-
-    echo " - Creating /etc/apt/sources.list.d/adoptium.list"
-    echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb $__os_codename main" | sudo tee /etc/apt/sources.list.d/adoptium.list >/dev/null
-
-    echo " - Installing temurin-17-jdk"
-    #try to install temurin java versions; if it fails, remove repository to avoid breaking user's system
-    (install_packages temurin-17-jdk)
-    if [ $? != 0 ]; then
-      anything_installed_from_repo "https://adoptium.jfrog.io/artifactory/deb"
-      if [ $? != 0 ]; then
-        # nothing installed from repo, this check is to prevent removing repos which other pi-apps scripts or the user have used successfully
-        # safe to remove
-        sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
-      fi
-      error "Failed to install temurin packages. Adoptium repository has been removed."
-    fi
-    java_home="$(dpkg -L temurin-17-jdk | grep "/usr/lib/jvm.*$(dpkg --print-architecture)$")"
-    ;;
-  bookworm | sid)
-    warning "You are running Debian $__os_codename which is an unstable repo."
-    install_packages openjdk-17-jdk || exit 1
-    java_home="$(dpkg -L openjdk-17-jdk | grep "/usr/lib/jvm.*$(dpkg --print-architecture)$")"
-    ;;
-  *)
-    error "Debian version ($__os_codename) is too old, update to debian Buster or newer"
-    ;;
-  esac
-  ;;
-Kali)
-  install_packages wget apt-transport-https gnupg || error "Failed to install dependencies"
-  hash -r
-
-  status "Adding Adoptium repository:"
-
-  echo "- public key -> keyring"
-  rm -f /tmp/adoptium-public-key /tmp/adoptium-archive-keyring.gpg
-  wget -O /tmp/adoptium-public-key https://adoptium.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public
-  gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --import /tmp/adoptium-public-key
-  rm -f /tmp/adoptium-public-key
-
-  echo " - keyring -> GPG key"
-  gpg --no-default-keyring --keyring /tmp/adoptium-keyring.gpg --export --output /tmp/adoptium-archive-keyring.gpg
-  rm -f /tmp/adoptium-keyring.gpg
-
-  echo " - Moving GPG key to /usr/share/keyrings"
-  sudo mv -f /tmp/adoptium-archive-keyring.gpg /usr/share/keyrings
-
-  echo " - Creating /etc/apt/sources.list.d/adoptium.list"
-  echo "deb [signed-by=/usr/share/keyrings/adoptium-archive-keyring.gpg] https://adoptium.jfrog.io/artifactory/deb buster main" | sudo tee /etc/apt/sources.list.d/adoptium.list >/dev/null
-
-  echo " - Installing temurin-17-jdk"
-  #try to install temurin java versions; if it fails, remove repository to avoid breaking user's system
-  (install_packages temurin-17-jdk)
-  if [ $? != 0 ]; then
-    anything_installed_from_repo "https://adoptium.jfrog.io/artifactory/deb"
-    if [ $? != 0 ]; then
-      # nothing installed from repo, this check is to prevent removing repos which other pi-apps scripts or the user have used successfully
-      # safe to remove
-      sudo rm -f /etc/apt/sources.list.d/adoptium.list /usr/share/keyrings/adoptium-archive-keyring.gpg
-    fi
-    error "Failed to install temurin packages. Adoptium repository has been removed."
-  fi
-  java_home="$(dpkg -L temurin-17-jdk | grep "/usr/lib/jvm.*$(dpkg --print-architecture)$")"
-  ;;
-Ubuntu)
-  # ubuntu default repositories now include openjdk-17
-  # install java
-  install_packages openjdk-17-jdk || exit 1
-  java_home="$(dpkg -L openjdk-17-jdk | grep "/usr/lib/jvm.*$(dpkg --print-architecture)$")"
-  ;;
-*)
-  error "$__os_id appears to be an unsupported OS"
-  ;;
-esac
-
-install_packages python3-pip python3-dev build-essential clang || exit 1
-
-wget https://download.jetbrains.com/python/pycharm-community-${version}.tar.gz -O pycharm-community.tar.gz || error "Failed to download pycharm-community.tar.gz"
+wget https://download.jetbrains.com/python/pycharm-community-${version}-aarch64.tar.gz -O pycharm-community.tar.gz || error "Failed to download pycharm-community.tar.gz"
 status "Extracting pycharm-community.tar.gz to /opt"
 sudo rm -rf /opt/pycharm-community && sudo mkdir -p /opt/pycharm-community
 sudo tar xzf pycharm-community.tar.gz -C /opt/pycharm-community || error "Failed to extract pycharm-community.tar.gz"
 sudo mv /opt/pycharm-community/*/* /opt/pycharm-community/
 sudo chmod +x /opt/pycharm-community/bin/pycharm.sh
 
-cd $HOME
-status "Compiling file watcher ..."
-wget https://github.com/Pi-Apps-Coders/files/raw/main/fsnotifier-pycharm-rpi.zip || exit 1
-unzip fsnotifier-pycharm-rpi.zip || error "Failed to unzip fsnotifier-pycharm-rpi.zip."
-cd $HOME/fsnotifier-pycharm-rpi/
-gcc -O2 -Wall -Wextra -Wpedantic -std=c11 -o fsnotifier main.c inotify.c util.c || error "Failed to compile file watcher."
-chmod 755 fsnotifier || error "Failed to set file watcher as executable."
-mkdir -p "$HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/options"
-mv -f "$HOME/fsnotifier-pycharm-rpi/fsnotifier" "$HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/" || error "Failed to move fsnotifier binary to $HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/."
-[ -a "$HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties" ] && echo "$(cat $HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties | grep -v idea.filewatcher.executable.path)" > "$HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties"
-echo "idea.filewatcher.executable.path = $HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/fsnotifier" >> "$HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties" || error "Failed to add file watcher executable path to $HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties."
-
-status "Remove bundled JRE version message ..."
-echo '<application>
-  <component name="PropertiesComponent">
-    <property name="ignore.bundled.jre.version.message" value="true" />
-  </component>
-</application>' > "$HOME/.config/JetBrains/PyCharmCE$(echo "$version" | sed 's/\.[^.]*//2g')/options/other.xml"
-
 status "Creating desktop shortcut ..."
 echo "[Desktop Entry]
 Type=Application
 Name=PyCharm Community Edition
 Icon=$(dirname "$0")/icon-64.png
-Exec=bash -c "\""JAVA_HOME=$java_home PATH=$java_home/bin/:$PATH /opt/pycharm-community/bin/pycharm.sh"\""
+Exec=/opt/pycharm-community/bin/pycharm.sh
 Comment=Python IDE
 Categories=Development;IDE;Programming;
 Terminal=false
 StartupWMClass=jetbrains-pycharm-ce
-StartupNotify=true" > ~/.local/share/applications/jetbrains-pycharm-ce.desktop
+StartupNotify=true" > /usr/local/share/applications/jetbrains-pycharm-ce.desktop
 
 #cleanup
 rm -rf $HOME/pycharm-community.tar.gz $HOME/fsnotifier-pycharm-rpi  $HOME/fsnotifier-pycharm-rpi.zip
