Monero GUI: add -latomic for 32bit architectures
https://gitlab.kitware.com/cmake/cmake/-/issues/21174

diff --git a/apps/Monero GUI/install b/apps/Monero GUI/install
--- a/apps/Monero GUI/install
+++ b/apps/Monero GUI/install
@@ -15,7 +15,11 @@ git_clone --recursive https://github.com/monero-project/monero-gui || exit 1
 
 #compile
 cd /tmp/monero-gui
-make release -j$(nproc) || error "Compiling monero-gui failed. Check errors above."
+if [ "$arch" == 32 ]; then
+  LDFLAGS=-latomic make release -j$(nproc) || error "Compiling monero-gui failed. Check errors above."
+else
+  make release -j$(nproc) || error "Compiling monero-gui failed. Check errors above."
+fi
 cd
 
 IFS=$'\n'
