Update Wine to 11.4 to allow Lego Digital Designer and WACUP to (hopefully) work

diff --git a/apps/Wine (x64)/install-64 b/apps/Wine (x64)/install-64
--- a/apps/Wine (x64)/install-64
+++ b/apps/Wine (x64)/install-64
@@ -1,35 +1,37 @@
 #!/bin/bash
 
 #note to maintainer, if you change the below version make sure to update it in the uninstall script as well
-version=9.17
+version=11.4
 
+# for now commenting this out as the 16K issue should have been fixed with Wine 10.5+
+# but still TODO to check if it works on 16K kernels
 # https://github.com/raspberrypi/bookworm-feedback/issues/107
-PAGE_SIZE="$(getconf PAGE_SIZE)"
-if [[ "$PAGE_SIZE" == "16384" ]]; then
-  #switch to 4K pagesize kernel
-  if [ -f /boot/config.txt ] || [ -f /boot/firmware/config.txt ]; then
-    if [ -f /boot/firmware/config.txt ]; then
-      boot_config="/boot/firmware/config.txt"
-    elif [ -f /boot/config.txt ]; then
-      boot_config="/boot/config.txt"
-    fi
-    text="Raspberry Pi 5 PiOS images ship by default with a 16K PageSize Linux Kernel.
-This kernel causes incompatibilities with some software including Wine https://github.com/raspberrypi/bookworm-feedback/issues/107
-
-Would you like to automatically switch to a 4K PageSize Linux Kernel?"
-    userinput_func "$text" "No, keep 16K PageSize Kernel and Exit" "Yes, switch to 4K PageSize Kernel"
-    if [ "$output" == "No, keep 16K PageSize Kernel and Exit" ]; then
-      error "User error: Your current running kernel is built with 16K PageSize and is incompatible with Wine (x64) with Box64. You must switch to a 4K PageSize kernel (and chose to not do so automatically) before installing Wine (x64)."
-    fi
-    echo "" | sudo tee --append $boot_config >/dev/null
-    echo "[pi5]" | sudo tee --append $boot_config >/dev/null
-    echo "kernel=kernel8.img" | sudo tee --append $boot_config >/dev/null
-    echo -e "The 4K PageSize Kernel has been enabled by adding 'kernel=kernel8.img' to $boot_config\nPlease reboot now and install the Wine (x64) app again."
-    sleep infinity
-  else
-    error "User error (reporting allowed): Your current running kernel is built with 16K PageSize and is incompatible with Wine (x64) with Box64. Changing kernels automatically cannot be done since no /boot/config.txt or /boot/firmware/config.txt file was found."
-  fi
-fi
+#PAGE_SIZE="$(getconf PAGE_SIZE)"
+#if [[ "$PAGE_SIZE" == "16384" ]]; then
+#  #switch to 4K pagesize kernel
+#  if [ -f /boot/config.txt ] || [ -f /boot/firmware/config.txt ]; then
+#    if [ -f /boot/firmware/config.txt ]; then
+#      boot_config="/boot/firmware/config.txt"
+#    elif [ -f /boot/config.txt ]; then
+#      boot_config="/boot/config.txt"
+#    fi
+#    text="Raspberry Pi 5 PiOS images ship by default with a 16K PageSize Linux Kernel.
+#This kernel causes incompatibilities with some software including Wine https://github.com/raspberrypi/bookworm-feedback/issues/107
+#
+#Would you like to automatically switch to a 4K PageSize Linux Kernel?"
+#    userinput_func "$text" "No, keep 16K PageSize Kernel and Exit" "Yes, switch to 4K PageSize Kernel"
+#    if [ "$output" == "No, keep 16K PageSize Kernel and Exit" ]; then
+#      error "User error: Your current running kernel is built with 16K PageSize and is incompatible with Wine (x64) with Box64. You must switch to a 4K PageSize kernel (and chose to not do so automatically) before installing Wine (x64)."
+#    fi
+#    echo "" | sudo tee --append $boot_config >/dev/null
+#    echo "[pi5]" | sudo tee --append $boot_config >/dev/null
+#    echo "kernel=kernel8.img" | sudo tee --append $boot_config >/dev/null
+#    echo -e "The 4K PageSize Kernel has been enabled by adding 'kernel=kernel8.img' to $boot_config\nPlease reboot now and install the Wine (x64) app again."
+#    sleep infinity
+#  else
+#    error "User error (reporting allowed): Your current running kernel is built with 16K PageSize and is incompatible with Wine (x64) with Box64. Changing kernels automatically cannot be done since no /boot/config.txt or /boot/firmware/config.txt file was found."
+#  fi
+#fi
 
 # Wine conflicts with Hangover
 "${DIRECTORY}/manage" uninstall Hangover
@@ -65,7 +67,7 @@ less_tar() { #format tar verbose output to refresh same line with the next extra
 }
 
 # Download wine to /opt
-wget https://github.com/Pi-Apps-Coders/files/releases/download/large-files/wine-${version}.tar.gz -O /tmp/wine-${version}.tar.gz || error 'Failed to download wine!'
+wget https://github.com/pi-apps-go/files/releases/download/large-files/wine-${version}.tar.gz -O /tmp/wine-${version}.tar.gz || error 'Failed to download wine!'
 status "Extracting: /tmp/wine-${version}.tar.gz"
 sudo tar -xvf /tmp/wine-${version}.tar.gz -C /opt | less_tar
 [ ${PIPESTATUS[0]} != 0 ] && error 'Failed to extract wine!'
@@ -81,18 +83,18 @@ sudo mv /tmp/winetricks /opt/wine-${version}/bin/winetricks || error "Failed to 
 sudo chmod +x /opt/wine-${version}/bin/winetricks
 
 #download Mono to universal location (to be installed automatically in all wine prefixes)
-#according to https://wiki.winehq.org/Mono#Versions, use Mono 9.3.0 for Wine 9.17
+#according to https://gitlab.winehq.org/wine/wine/-/wikis/Wine-Mono, use Mono 11.0.0 for Wine 11.4
 #wine mono pacakge is called -x86 but contains both x86 and x86_64 binaries
 sudo mkdir -p /opt/wine-${version}/share/wine/mono
-wget -O "/tmp/wine-mono-9.3.0-x86.tar.xz" 'https://dl.winehq.org/wine/wine-mono/9.3.0/wine-mono-9.3.0-x86.tar.xz' || exit 1
-status "Extracting: /tmp/wine-mono-9.3.0-x86.tar.xz"
-sudo tar -xvf "/tmp/wine-mono-9.3.0-x86.tar.xz" -C "/opt/wine-${version}/share/wine/mono" | less_tar
+wget -O "/tmp/wine-mono-11.0.0-x86.tar.xz" 'https://dl.winehq.org/wine/wine-mono/11.0.0/wine-mono-11.0.0-x86.tar.xz' || exit 1
+status "Extracting: /tmp/wine-mono-11.0.0-x86.tar.xz"
+sudo tar -xvf "/tmp/wine-mono-11.0.0-x86.tar.xz" -C "/opt/wine-${version}/share/wine/mono" | less_tar
 [ ${PIPESTATUS[0]} != 0 ] && error 'Failed to extract wine-mono!'
-rm -f "/tmp/wine-mono-9.3.0-x86.tar.xz"
+rm -f "/tmp/wine-mono-11.0.0-x86.tar.xz"
 status_green Done
 
 #download Gecko to universal location (to be installed automatically in all wine prefixes)
-#according to https://wiki.winehq.org/Gecko, use Gecko 2.47.4 for Wine 8.6
+#according to https://gitlab.winehq.org/wine/wine/-/wikis/Gecko, use Gecko 2.47.4 for Wine 8.6+
 sudo mkdir -p /opt/wine-${version}/share/wine/gecko
 wget -O "/tmp/wine-gecko-2.47.4-x86_64.tar.xz" 'https://dl.winehq.org/wine/wine-gecko/2.47.4/wine-gecko-2.47.4-x86_64.tar.xz' || exit 1
 status "Extracting: /tmp/wine-gecko-2.47.4-x86_64.tar.xz"
