rename Minecraft Java to Minecraft Java Lunar (#2007)
* rename Minecraft Java to Minecraft Java Lunar

* correct category entry

* hide old minecraft java entry

* rename old minecraft java to minecraft java lunar

since the merge of PR: https://github.com/Botspot/pi-apps/pull/2021 this will run after updating in the current GUI. moving the old minecraft java to the new name of minecraft java lunar will trigger another update showing that minecraft java lunar needs to be updated on a users install

* update to lunarclient bruh release

* purge old minecraft java as part of the install

also remove old minecraft java from categories as the runonce removes the folder before the GUI reloads

diff --git a/apps/Minecraft Java Lunar/install-64 b/apps/Minecraft Java Lunar/install-64
--- a/apps/Minecraft Java Lunar/install-64
+++ b/apps/Minecraft Java Lunar/install-64
@@ -1,4 +1,8 @@
 #!/bin/bash
+# purge old Minecraft Java dummy deb
+apt_lock_wait
+sudo apt purge -y pi-apps-c6dfb753
+
 install_packages kmod zip unzip libfuse2 || exit 1
 
 # cleanup any remaing old lunar stuff
@@ -7,7 +11,7 @@ sudo rm -rf ~/lwjgl2arm32 ~/lwjgl3arm32 ~/lwjgl3arm64 ~/lwjgl2arm64 /opt/jdk/jdk
 #Download client and assorted java stuff
 echo "Downloading lunarclient.AppImage"
 mkdir -p ~/.local/bin || error "Could not make directory"
-wget -O ~/.local/bin/lunarclient.AppImage 'https://github.com/gl91306/lunar/releases/download/v2.10.1/lunarclient-2.10.1-armv7l.AppImage' || error 'Failed to download lunarclient.AppImage'
+wget -O ~/.local/bin/lunarclient.AppImage 'https://github.com/gl91306/lunar/releases/download/v2.10.1.bruh/lunarclient-2.10.1-arm64.AppImage' || error 'Failed to download lunarclient.AppImage'
 chmod +x ~/.local/bin/lunarclient.AppImage || error 'Failed to make lunarclient.AppImage executable!'
 
 enable_module fuse || exit 1
