Zoom app fixes and facelift

diff --git a/apps/Zoom/install-32 b/apps/Zoom/install-32
--- a/apps/Zoom/install-32
+++ b/apps/Zoom/install-32
@@ -57,7 +57,7 @@ sudo ldconfig
 if [ $dlzoom == 1 ];then
   echo "Downloading Zoom..."
   rm -rf "${HOME}/zoom" ~/zoom_i686.tar.xz
-  wget 'https://zoom.us/client/latest/zoom_i686.tar.xz' || error 'Failed to download Zoom i686!'
+  wget 'https://github.com/Botspot/zoom_686_mirror/raw/main/zoom_i686.tar.xz' || error 'Failed to download Zoom i686!'
   tar -xf ~/zoom_i686.tar.xz || error 'Failed to extract Zoom i686!'
   rm -f ~/zoom_i686.tar.xz #who cares if this fails
 fi
