Update install-64

diff --git a/apps/Zoom/install-64 b/apps/Zoom/install-64
--- a/apps/Zoom/install-64
+++ b/apps/Zoom/install-64
@@ -10,8 +10,14 @@ function error {
 cd $HOME
 
 # Get dependencies
-cd $HOME
-"${DIRECTORY}/pkg-install" "cmake:armhf pulseaudio-utils:armhf pulseaudio:armhf libxcb-shape0:armhf libxcb-randr0:armhf libxcb-image:armhf libxcb-image0:armhf libxcb-xtest0:armhf libxcb-keysyms1:armhf libxcb-xfixes0:armhf libturbojpeg0:armhf libdbus-1-3:armhf" "$(dirname "$0")" || exit 1
+DISTRO=$(lsb_release -is)
+if [[ "${DISTRO}" == "Debian" || "${DISTRO}" == "Raspbian" ]]; then
+  "${DIRECTORY}/pkg-install" "pulseaudio-utils:armhf pulseaudio:armhf libxcb-shape0:armhf libxcb-randr0:armhf libxcb-image0:armhf libxcb-xtest0:armhf libxcb-keysyms1:armhf libxcb-xfixes0:armhf libturbojpeg0:armhf libdbus-1-3:armhf" "$(dirname "$0")" || exit 1
+elif [[ "${DISTRO}" == "Ubuntu" ]]; then
+  "${DIRECTORY}/pkg-install" "pulseaudio-utils:armhf pulseaudio:armhf libxcb-shape0:armhf libxcb-randr0:armhf libxcb-image0:armhf libxcb-xtest0:armhf libxcb-keysyms1:armhf libxcb-xfixes0:armhf libturbojpeg:armhf libdbus-1-3:armhf" "$(dirname "$0")" || exit 1
+else 
+	error "This script can't run on your OS! It HAS to be Debian or Ubuntu"
+fi
 
 #refresh list of libraries
 sudo ldconfig
