add pulseaudio, launcher script

diff --git a/apps/Zoom/install b/apps/Zoom/install
--- a/apps/Zoom/install
+++ b/apps/Zoom/install
@@ -12,7 +12,7 @@ if [ -d box86 ];then
   echo -n "Box86 already exists on your system. Do you want it overwritten with the latest version? [Y/n] "
   read answer
   if [ ! -z "$answer" ] && [ "$answer" == 'n' ];then
-    echo "OK, using your pre-existing version of box86. Be warned though: It may be out of date and may not run Zoom successfully!"
+    echo -e "OK, using your pre-existing version of box86. Be warned though: It may be out of date and \e[1m\e[97mmay not run Zoom successfully!\e[0m"
     #don't do anything, don't download & compile box86
     compile=0
   else
@@ -24,8 +24,10 @@ else
   #box86 does not exist beforehand, so compile
 fi
 
+echo ''
+
 if [ -d "${HOME}/zoom" ];then
-  echo -n "${HOME}/zoom already exists on your system. Do you want it overwritten with the latest version? [Y/n] "
+  echo -ne "${HOME}/zoom already exists on your system. Do you want it overwritten with the latest version? [Y/n] "
   read answer
   if [ ! -z "$answer" ] && [ "$answer" == 'n' ];then
     dlzoom=0
@@ -38,7 +40,7 @@ fi
 
 # Get dependencies
 cd $HOME
-"${DIRECTORY}/pkg-install" "libxcb-xtest0 libxcb-xfixes0 cmake" "$(dirname "$0")" || exit 1
+"${DIRECTORY}/pkg-install" "libxcb-xtest0 libxcb-xfixes0 cmake pulseaudio-utils pulseaudio" "$(dirname "$0")" || exit 1
 
 if [ $dlzoom == 1 ];then
   echo "Downloading Zoom..."
@@ -47,6 +49,13 @@ if [ $dlzoom == 1 ];then
   tar -xf ~/zoom_i686.tar.xz || error 'Failed to extract Zoom i686!'
   rm -f ~/zoom_i686.tar.xz #who cares if this fails
 fi
+
+echo 'Creating launcher script'
+echo "#!/bin/bash
+pulseaudio &
+cd ${HOME}/zoom/
+box86 zoom" > "${HOME}/zoom/runzoom.sh"
+chmod +x "${HOME}/zoom/runzoom.sh"
 
 if [ $compile == 1 ];then
   gio trash ~/box86
@@ -65,19 +74,17 @@ if [ $compile == 1 ];then
 fi
 cd $HOME
 
-echo "Restarting systemd-binfmt service..."
-sudo systemctl restart systemd-binfmt #if this fails, no big deal.
-
 if [ ! -f /usr/local/bin/box86 ];then
   error "Box86 should be installed by now, but /usr/local/bin/box86 does not exist!"
 fi
 
-cd $HOME
+echo "Restarting systemd-binfmt service..."
+sudo systemctl restart systemd-binfmt #if this fails, no big deal.
 
 echo "Creating Application Menu button..."
 echo "[Desktop Entry]
 Name=Zoom
-Exec=lxterminal --title 'Close this window to exit Zoom' -e 'box86 zoom;read enter'
+Exec=lxterminal --title 'Close this window to exit Zoom' -e "\""$HOME/zoom/runzoom.sh"\""
 Icon=${DIRECTORY}/apps/Zoom/icon-64.png
 Path=${HOME}/zoom/
 Type=Application
@@ -85,7 +92,4 @@ Comment=i386 version of software platform used for teleconferencing using Box86
 Categories=Network;" > ~/.local/share/applications/zoom.desktop
 
 echo "Installation complete!"
-
-
-
 
