Remarkable app fix deps for 64bit

diff --git a/apps/Remarkable/uninstall b/apps/Remarkable/uninstall
--- a/apps/Remarkable/uninstall
+++ b/apps/Remarkable/uninstall
@@ -7,5 +7,15 @@ function error {
   exit 1
 }
 
-sudo apt purge remarkable -y || error "Failed to purge remarkable package!"
-sudo apt autoremove -y
+if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ];then
+  #COMMANDS TO UNINSTALL 64BIT
+  "${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1
+  
+elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ];then
+  #COMMANDS TO UNINSTALL 32BIT
+  sudo apt purge remarkable -y || error "Failed to purge remarkable package!"
+  sudo apt autoremove -y
+  
+else
+  error "Failed to detect OS CPU architecture! Something is very wrong."
+fi
