Update install

diff --git a/apps/Telegram/install b/apps/Telegram/install
--- a/apps/Telegram/install
+++ b/apps/Telegram/install
@@ -2,6 +2,8 @@
 
 DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
 
+echo $DIRECTORY 
+
 function error {
   echo -e "\\e[91m$1\\e[39m"
   exit 1
@@ -11,13 +13,20 @@ function error {
 "${DIRECTORY}/pkg-install" "flatpak" "$(dirname "$0")" || error "Failed installing Flatpak!"
 
 ( sudo flatpak install flathub org.telegram.desktop -y || flatpak install flathub org.telegram.desktop -y ) || error "Failed installing Telegram!"
+#~ sudo cp /var/lib/flatpak/app/org.telegram.desktop/current/active/export/share/applications/org.telegram.desktop.desktop ~/.local/share/applications/
 
 # Create menu shortcut
 echo "[Desktop Entry]
-Name=Telegram
-Exec=flatpak run org.telegram.desktop
-Icon=$(dirname "$0")/icon-64.png
+Version=1.0
+Name=Telegram 
+Comment=Official desktop version of Telegram messaging app
+Exec=/usr/bin/flatpak run --branch=stable --arch=arm --command=telegram-desktop --file-forwarding org.telegram.desktop -- @@u %u @@
+Icon=$DIRECTORY/apps/Telegram/icon-24.png
 Terminal=false
-StartupNotify=true
+StartupWMClass=TelegramDesktop
 Type=Application
-Categories=Network;" > ~/.local/share/applications/telegram.desktop || error "Failed to create menu shortcut!"
+Categories=Chat;Network;InstantMessaging;Qt;
+MimeType=x-scheme-handler/tg;
+Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
+X-GNOME-UsesNotifications=true
+X-Flatpak=org.telegram.desktop" > ~/.local/share/applications/telegram.desktop || error "Failed to create menu shortcut!"
