Add flatpak fixes, rm original menu launcher, better icon path

diff --git a/apps/Telegram/install b/apps/Telegram/install
--- a/apps/Telegram/install
+++ b/apps/Telegram/install
@@ -2,8 +2,6 @@
 
 DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
 
-echo $DIRECTORY 
-
 function error {
   echo -e "\\e[91m$1\\e[39m"
   exit 1
@@ -12,8 +10,10 @@ function error {
 # Install flatpak first 
 "${DIRECTORY}/pkg-install" "flatpak" "$(dirname "$0")" || error "Failed installing Flatpak!"
 
-( sudo flatpak install flathub org.telegram.desktop -y || flatpak install flathub org.telegram.desktop -y ) || error "Failed installing Telegram!"
-#~ sudo cp /var/lib/flatpak/app/org.telegram.desktop/current/active/export/share/applications/org.telegram.desktop.desktop ~/.local/share/applications/
+flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+
+sudo flatpak install flathub org.telegram.desktop -y || flatpak install flathub org.telegram.desktop -y || error "Flatpak failed to install org.telegram.desktop!"
+sudo rm -f /var/lib/flatpak/app/org.telegram.desktop/current/active/export/share/applications/org.telegram.desktop.desktop
 
 # Create menu shortcut
 echo "[Desktop Entry]
@@ -21,7 +21,7 @@ Version=1.0
 Name=Telegram 
 Comment=Official desktop version of Telegram messaging app
 Exec=/usr/bin/flatpak run --branch=stable --arch=arm --command=telegram-desktop --file-forwarding org.telegram.desktop -- @@u %u @@
-Icon=$DIRECTORY/apps/Telegram/icon-24.png
+Icon=$(dirname "$0")/icon-64.png
 Terminal=false
 StartupWMClass=TelegramDesktop
 Type=Application
