Updated new link and added alias

diff --git a/apps/All Is Well/install b/apps/All Is Well/install
--- a/apps/All Is Well/install
+++ b/apps/All Is Well/install
@@ -9,8 +9,9 @@ function error {
 
 mkdir AIW
 cd ~/AIW || error "Failed to enter directory!"
-wget 'https://raw.githubusercontent.com/spectrumgamer75/All-is-well/master/ALL%20IS%20WELL%20(V2.0)/aiwrpi.sh' || error "Failed to download!"
+wget 'https://raw.githubusercontent.com/spectrumgamer75/All-is-well/master/aiw/aiwrpi.sh' || error "Failed to download!"
 chmod +x 'aiwrpi.sh'
+echo "alias aiw=$HOME/AIW/aiwrpi.sh" >> ~/.bashrc
 echo "[Desktop Entry]
 Name=All Is Well
 GenericName=Update Helper and Fixer
