Updated username

diff --git a/apps/All Is Well/install b/apps/All Is Well/install
--- a/apps/All Is Well/install
+++ b/apps/All Is Well/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 rm -rf ~/All-is-well || error "Failed to first remove ~/All-is-well folder!"
-git_clone https://github.com/spectrumgamer75/All-is-well || error "Failed to download!"
+git_clone https://github.com/spectrum75/All-is-well || error "Failed to download!"
 cd $HOME/All-is-well/aiw
 chmod +x 'aiwrpi.sh'
 echo "alias aiw=$HOME/All-is-well/aiw/aiwrpi.sh" >> ~/.bashrc
