Node.js: install LTS node version
In the majority of cases the current version of nodejs should not be used as the majority of packages have not been updated for it.

"Major Node.js versions enter Current release status for six months, which gives library authors time to add support for them. After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months. Production applications should only use Active LTS or Maintenance LTS releases."

diff --git a/apps/Node.js/install b/apps/Node.js/install
--- a/apps/Node.js/install
+++ b/apps/Node.js/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-version=v22.4.0
+version=v20.15.1
 version2=v0.39.7
 
 #Checking if using armv6
@@ -43,5 +43,5 @@ echo ". ~/.node_bashrc" >> ~/.bashrc
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 
-# Install latest nodejs
-nvm install node || error "Failed to install node.js with nvm!"
+# Install LTS nodejs
+nvm install --lts || error "Failed to install node.js with nvm!"
