DO NOT MERGE: test installing specific nodejs version
https://github.com/nvm-sh/nvm/issues/3452

diff --git a/apps/Node.js/install b/apps/Node.js/install
--- a/apps/Node.js/install
+++ b/apps/Node.js/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-version=v22.11.0
+version=v20.18.0
 version2=v0.40.1
 
 #Checking if using armv6
@@ -43,5 +43,5 @@ echo ". ~/.node_bashrc" >> ~/.bashrc
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 
-# Install LTS nodejs
-nvm install --lts || error "Failed to install node.js with nvm!"
+# test installing specific version
+nvm install 20.18.0 || error "Failed to install node.js with nvm!"
