btop++: update version along with auto-updater

diff --git a/apps/btop++/install-32 b/apps/btop++/install-32
--- a/apps/btop++/install-32
+++ b/apps/btop++/install-32
@@ -1,15 +1,15 @@
 #!/bin/bash
-version=1.4.5
+version=1.4.6
 
 install_packages make || exit 1
 
 cd /tmp
 rm -rf btop
-wget https://github.com/aristocratos/btop/releases/download/v${version}/btop-armv7l-linux-musleabihf.tbz || error 'Failed to download "btop-armv7l-linux-musleabihf.tbz"!'
-tar -xjf btop-armv7l-linux-musleabihf.tbz || error 'Failed to decompress "btop-armv7l-linux-musleabihf.tbz"!'
+wget https://github.com/aristocratos/btop/releases/download/v${version}/btop-armv7-unknown-linux-musleabi.tbz || error 'Failed to download "btop-armv7-unknown-linux-musleabi.tbz"!'
+tar -xjf btop-armv7-unknown-linux-musleabi.tbz || error 'Failed to decompress "btop-armv7-unknown-linux-musleabi.tbz"!'
 cd btop || error 'Could not enter btop directory'
 sudo make -B install || error 'Failed to install btop with "sudo make install"!'
-rm -rf /tmp/btop /tmp/btop-armv7l-linux-musleabihf.tbz || sudo rm -rf /tmp/btop /tmp/btop-armv7l-linux-musleabihf.tbz || error 'Failed to remove install directory!'
+rm -rf /tmp/btop /tmp/btop-armv7-unknown-linux-musleabi.tbz || sudo rm -rf /tmp/btop /tmp/btop-armv7-unknown-linux-musleabi.tbz || error 'Failed to remove install directory!'
 
 echo "[Desktop Entry]
 Name=btop++
