teamviewer host many fixes. botspot-ifyed

diff --git a/apps/TeamViewer Host/install-32 b/apps/TeamViewer Host/install-32
--- a/apps/TeamViewer Host/install-32
+++ b/apps/TeamViewer Host/install-32
@@ -1,21 +1,17 @@
 #!/bin/bash
 
+DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
+
+function error {
+  echo -e "\\e[91m$1\\e[39m"
+  exit 1
+}
+
 # Download teamviewer installation file #
-wget https://download.teamviewer.com/download/linux/teamviewer-host_armhf.deb
+wget https://download.teamviewer.com/download/linux/teamviewer-host_armhf.deb || error "Failed to download teamviewer-host_armhf.deb"
 
-# Install it with dpkg # 
-sudo dpkg -i teamviewer-host_armhf.deb
+# Install it with dpkg 
+sudo apt install -y --fix-broken ~/teamviewer-host_armhf.deb || error "Failed to install teamviewer-host_armhf.deb"
 
-# Install it's dependencies #
-sudo apt --fix-broken install -y
-
-# Delete teamviewer installation file #
-rm teamviewer-host_armhf.deb
-
-# Credit #
-
-echo This is the teamviewer installer made by Benmac83#3821! \(Discord\)
-echo The packages and everything that this script downloads is NOT made by me and all credit for the package that is downloaded should go to Teamviewer! \(https://www.teamviewer.com/\)
-
-# Print out thanks #
-echo Thank you for using my script. I hope you have a great day!
+# Delete teamviewer installation file
+rm -f ~/teamviewer-host_armhf.deb
diff --git a/apps/TeamViewer Host/uninstall b/apps/TeamViewer Host/uninstall
--- a/apps/TeamViewer Host/uninstall
+++ b/apps/TeamViewer Host/uninstall
@@ -1,6 +1,10 @@
 #!/bin/bash
 
-echo Goodbye!
+DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
 
-sudo dpkg -r teamviewer-host
-sudo apt autoremove -y
+function error {
+  echo -e "\\e[91m$1\\e[39m"
+  exit 1
+}
+
+sudo apt purge -y teamviewer-host || error "APT failed to remove teamviewer-host package."
