Boxy SVG: use app files straight from dev and auto-update

diff --git a/apps/Boxy SVG/install b/apps/Boxy SVG/install
--- a/apps/Boxy SVG/install
+++ b/apps/Boxy SVG/install
@@ -1,64 +1,42 @@
 #!/bin/bash
-#wget -qO- https://raw.githubusercontent.com/Botspot/Boxy-SVG-RPi/main/install.sh | bash
 
-link="$(wget -qO- --header 'Snap-Device-Series: 16' http://api.snapcraft.io/v2/snaps/info/boxy-svg | sed 's/},{/}\n{/g' | grep arm64 | tr '{,}' '\n' | grep '"url":"' | sed 's/^"url":"//g' | sed 's/"$//g')"
+version=3.95.4.zip
 
-if [ -z "$link" ];then
-  error "Failed to find a link to download the Boxy SVG snap from! Be sure you are connected to the Internet."
-fi
+"${DIRECTORY}/manage" install-if-not-installed Node.js || error "Failed to install Node.js! This is necessary to compile Boxy SVG on your 32-bit OS."
 
-status "Downloading the Boxy SVG snap package..."
-wget "$link" -O /tmp/boxy.snap || exit 1
+#install asar and electron-packager
+export NVM_DIR="$HOME/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
 
-status "Mounting the snap package to copy files out..."
-mkdir -p /tmp/boxy-mount
-sudo umount -q /tmp/boxy-mount
-sudo mount -t squashfs -o ro /tmp/boxy.snap /tmp/boxy-mount || error "Failed to mount boxy.snap to copy files out!"
+wget -O /tmp/boxy-svg.zip "https://firebasestorage.googleapis.com/v0/b/boxy-svg.appspot.com/o/linux%2Fapp-${version}?alt=media" || exit 1
 
-status -n "Copying files... "
-sudo rm -rf /opt/boxy-svg
-sudo cp -a /tmp/boxy-mount/opt/boxy-svg /opt || error "Failed to copy files from mounted snap to /opt!"
-sudo cp /tmp/boxy-mount/meta/gui/boxy-svg.svg /opt/boxy-svg
-sudo cp "$(dirname "$0")/icon-64.png" /opt/boxy-svg
-sudo umount /tmp/boxy-mount
-sudo rm -rf /tmp/boxy.snap /tmp/boxy-mount
-status_green "Done"
+rm -rf /tmp/app
+cd /tmp
+unzip -q /tmp/boxy-svg.zip || error "Failed to extract!"
+rm -f /tmp/boxy-svg.zip
 
-#recompile electron app on armhf
+cd /tmp/app
+npm install || error "Failed to install npm dependencies!"
+npm --prefix ./electron install || error "Failed to install npm dependencies in electron folder!"
+
 if [ $arch == 32 ];then
-  
-  "${DIRECTORY}/manage" install-if-not-installed Node.js || error "Failed to install Node.js! This is necessary to recompile Boxy SVG on your 32-bit OS."
-  
-  #load nvm now
-  export NVM_DIR="$HOME/.nvm"
-  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
-  
-  npm install -g electron/asar electron-packager
-  
-  if [ $? != 0 ];then
-    #fixes npm bug where asar is already installed but it tries to install electron/asar on top of it
-    rm -f ~/.nvm/versions/node/*/bin/asar
-    npm install -g electron/asar electron-packager || error "NPM failed to install asar and electron-packager!"
-  fi
-  
-  rm -rf /tmp/boxy-sourcecode || exit 1
-  asar extract /opt/boxy-svg/resources/app.asar /tmp/boxy-sourcecode || error "Failed to extract boxy svg source code!"
-  
-  cd /tmp/boxy-sourcecode
-  npm install
-  #npm install -g electron-packager
-  electron-packager ./ --electron-version=21.3.4 --arch=armv7l --executable-name=boxy-svg --icon=boxy-svg.svg || error "Failed to package boxysvg electron app!"
-  
-  #copy new armhf files
-  sudo cp -a '/tmp/boxy-sourcecode/Boxy SVG-linux-armv7l'/. /opt/boxy-svg || error "Failed to copy new armv7l packages to /opt/boxy-svg"
-  rm -rf '/tmp/boxy-sourcecode/Boxy SVG-linux-armv7l'
-  
-  #Use armhf linux-fonts-manager
-  rm -rf /tmp/node_modules /tmp/boxy-sourcecode
-  cd /tmp && npm install local-fonts-manager || exit 1
-  sudo mv -f /tmp/node_modules/local-fonts-manager/build/Release/LinuxFontsManager.node /opt/boxy-svg/resources/app.asar.unpacked/node_modules/local-fonts-manager/build/Release
-  rm -rf /tmp/node_modules
+  ./node_modules/.bin/electron-builder --armv7l
+elif [ $arch == 64 ];then
+  ./node_modules/.bin/electron-builder --arm64
+else
+  error "Failed to detect OS CPU architecture! Something is very wrong."
 fi
+
+#move to permanent folder
+sudo rm -rf /opt/boxy-svg
+sudo mv ./dist/linux-*-unpacked /opt/boxy-svg || error "Failed to move app files to /opt/boxy-svg!"
+
+sudo mkdir -p /usr/local/share/icons
+sudo cp ./metadata/com.boxy_svg.BoxySVG.svg /usr/local/share/icons
+sudo cp ./metadata/com.boxy_svg.BoxySVG.png /usr/local/share/icons
+
+cd
+rm -rf /tmp/app
 
 #compile xseticon to set the program's window icon
 if ! command -v xseticon >/dev/null ;then
@@ -83,7 +61,7 @@ cat << "EOF" | sudo tee /usr/local/bin/boxy-svg >/dev/null
 numwindows="$(xwininfo -tree -root | grep '^        .*("boxy.svg" "Boxy.SVG")' -i | wc -l)"
 
 #run boxy-svg in background
-/opt/boxy-svg/boxy-svg "$@" &
+/opt/boxy-svg/boxy-svg --no-sandbox "$@" &
 pid=$!
 #if this script is terminated, also kill boxy svg
 trap "kill $pid &>/dev/null" EXIT
@@ -91,10 +69,10 @@ trap "kill $pid &>/dev/null" EXIT
 #run a loop in the background to always check for new boxy svg windows and set the window icon
 IFS=$'\n'
 if [ $numwindows == 0 ];then #only run one instance of the daemon
-  while true;do 
+  while true;do
     if [ "$numwindows" != "$(xwininfo -tree -root | grep '^        .*("boxy.svg" "Boxy.SVG")' -i | wc -l)" ];then
       for windowid in $(xwininfo -tree -root | grep '^        .*("boxy.svg" "Boxy.SVG")' -i | awk '{print $1}') ;do
-        xseticon -id $windowid "/opt/boxy-svg/icon-64.png"
+        xseticon -id $windowid "/usr/local/share/icons/com.boxy_svg.BoxySVG.png"
       done
       numwindows="$(xwininfo -tree -root | grep '^        .*("boxy.svg" "Boxy.SVG")' -i | wc -l)"
     fi
@@ -115,14 +93,14 @@ sudo chmod +x /usr/local/bin/boxy-svg
 
 if [ -z "$(cat ~/.config/mimeapps.list | grep 'boxy-svg.desktop')" ];then
   echo "Associating the SVG mimetype with Boxy SVG..."
-  echo "image/svg+xml=boxy-svg.desktop;" >> ~/.config/mimeapps.list
+  echo "image/svg+xml;application/illustrator=boxy-svg.desktop;" >> ~/.config/mimeapps.list
 fi
 
 echo "[Desktop Entry]
 Name=Boxy SVG
 Comment=Scalable Vector Graphics (SVG) editor
-Exec=boxy-svg %f
-Icon=/opt/boxy-svg/boxy-svg.svg
+Exec=boxy-svg %u
+Icon=com.boxy_svg.BoxySVG
 Type=Application
 Terminal=false
 Categories=Graphics
