add fsnotifier to Intellij IDEA
uses the same zip as pycharm to build the source from

diff --git a/apps/Intellij IDEA/install b/apps/Intellij IDEA/install
--- a/apps/Intellij IDEA/install
+++ b/apps/Intellij IDEA/install
@@ -15,6 +15,18 @@ cd /opt/ideaIC
 sudo tar xf /tmp/ideaIC.tar.gz --strip-components=1 || error "Failed to extract ideaIC.tar.gz!"
 rm -f /tmp/ideaIC.tar.gz
 
+cd $HOME
+status "Compiling file watcher ..."
+wget https://github.com/Pi-Apps-Coders/files/raw/main/fsnotifier-pycharm-rpi.zip || exit 1
+unzip fsnotifier-pycharm-rpi.zip || error "Failed to unzip fsnotifier-pycharm-rpi.zip."
+cd $HOME/fsnotifier-pycharm-rpi/
+bash ./make.sh || error "Failed to compile file watcher."
+mkdir -p "$HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/options"
+mv -f "$HOME/fsnotifier-pycharm-rpi/fsnotifier" "$HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/" || error "Failed to move fsnotifier binary to $HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/."
+[ -a "$HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties" ] && echo "$(cat $HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties | grep -v idea.filewatcher.executable.path)" > "$HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties"
+echo "idea.filewatcher.executable.path = $HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/fsnotifier" >> "$HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties" || error "Failed to add file watcher executable path to $HOME/.config/JetBrains/IdeaIC$(echo "$version" | sed 's/\.[^.]*//2g')/idea.properties."
+
+
 echo "[Desktop Entry]
 Type=Application
 Version=${version}
@@ -25,3 +37,6 @@ Comment=A fast and lightweight IDE using GTK+
 Icon=/opt/ideaIC/bin/idea.png
 Categories=Development;IDE;
 StartupNotify=true" | sudo tee /usr/share/applications/intellijidea.desktop >/dev/null
+
+#cleanup
+rm -rf $HOME/fsnotifier-pycharm-rpi  $HOME/fsnotifier-pycharm-rpi.zip
