Revamp downgrade chromium to work in more situations
Now it works for newer chromium versions that have boomworm/trixie
versions, newer chromium versions named chromium instead of
chromium-browser, and versions that require the chromium-common package

diff --git a/apps/Downgrade Chromium/install b/apps/Downgrade Chromium/install
--- a/apps/Downgrade Chromium/install
+++ b/apps/Downgrade Chromium/install
@@ -2,7 +2,9 @@
 
 #Automatically determine available Chromium versions from Raspberry Pi Archive website
 url_list="$(wget -O- https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/ | \
-  tr '<>' '\n' | grep '^a href="chromium' | tr '"' '\n' | grep '\.deb$')"
+  tr '<>' '\n' | grep '^a href="chromium' | tr '"' '\n' | grep '\.deb$' | sed 's#^#https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/#g')
+$(wget -O- https://archive.raspberrypi.org/debian/pool/main/c/chromium/ | \
+  tr '<>' '\n' | grep '^a href="chromium' | tr '"' '\n' | grep '\.deb$' | sed 's#^#https://archive.raspberrypi.org/debian/pool/main/c/chromium/#g')"
 # $url_list is a list of lines like this: "chromium-*-rpt1_arm[hf,64].deb"
 
 #make sure $url_list contains a list
@@ -19,64 +21,74 @@ if [ -z "$url_list" ];then
 fi
 
 #determine the available versions of Chromium
-version_list="$(echo "$url_list" | grep '^chromium-browser-l10n_' | sed 's/\..*//' | sed 's/.*_//' | sort | list_intersect "$(echo "$url_list" | grep '^chromium-browser_' | sed 's/\..*//' | sed 's/.*_//' | sort)" | sort -V | uniq)"
-
+version_list="$(echo "$url_list" | grep '/chromium-browser-l10n_\|/chromium-l10n_' | sed 's+.*/++g ; s/\..*//' | sed 's/.*_//' | sort | list_intersect "$(echo "$url_list" | grep '/chromium-browser_\|/chromium_' | sed 's+.*/++g ; s/\..*//' | sed 's/.*_//' | sort)" | sort -V | uniq)"
+echo "$version_list"
 #determine the main package names available. (chromium-browser, chromium-codecs-ffmpeg, etc.)
-package_names="$(echo "$url_list" | sed 's/_.*//' | sort | uniq)"
+package_names="$(echo "$url_list" | sed 's+.*/++g ; s/_.*//' | sort | uniq)"
+echo "$package_names"
 
-#Some versions of Chromium have been recompiled by Raspbian multiple times. (rpt1_armhf.deb, rpt4_armhf.deb, rpt5_armhf.deb, rpt6_armhf.deb)
-#Only show the last rpt* versions
-IFS=$'\n'
-url_list_2=''
-for version in $version_list ;do
-  #determine the last rpt release of every url for the given version
-  for package_name in $package_names ;do
-    url_list_2+="$(echo "$url_list" | grep "^${package_name}_" | grep "_${version}\." | sort -Vr | head -n1)"$'\n'
-  done
-done
-url_list="$(grep . <<<"$url_list_2")" #set url_list to url_list_2, while removing any empty lines.
-unset url_list_2
+yad_list="$(echo "$version_list" | sed 's/^/false\nChromium version /g')"
 
-#chromium version can be specified by $1
+#you can run this script with a chromium version as an argument:
 #usage: /path/to/this-script 78
-
-if [ -z "$1" ] || [ "$1" == update ];then
-  yad_list="$(echo "$version_list" | sed 's/^/false\nChromium version /g')"
-  
-  version=''
-  while [ -z "$version" ];do
-    version="$(echo "$yad_list" | yad --center --title="Choose Chromium version" --height=290 --no-headers \
-      --text="  Which Chromium version to install today?  " \
-      --radiolist --list --column=Tick --column=version --separator='\n' --print-column=2 \
-      --window-icon="$(dirname "$0")/icon-64.png" \
-      --button=!${DIRECTORY}/icons/check.png!OK:0)"
-    button=$?
-    
-    [ $button != 0 ] && error "User error: exited chromium version selection list"
-  done
-  #get just chromium version NUMBER
-  version="$(echo "$version" | awk '{print $3}')"
-else
+if [ "$1" != update ];then
   version="$1"
 fi
 
-#Set url variables based on selected version number
-cb_url="$(echo "$url_list" | grep "^chromium-browser_${version}\.")"
-l10n_url="$(echo "$url_list" | grep "^chromium-browser-l10n_${version}\.")"
-ffmpeg_extra_url="$(echo "$url_list" | grep "^chromium-codecs-ffmpeg-extra_${version}\.")"
+while [ -z "$version" ];do
+  version="$(echo "$yad_list" | yad --center --title="Choose Chromium version" --height=290 --no-headers \
+    --text="  Which Chromium version to install today?  " \
+    --radiolist --list --column=Tick --column=version --separator='\n' --print-column=2 \
+    --window-icon="$(dirname "$0")/icon-64.png" \
+    --button=!${DIRECTORY}/icons/check.png!OK:0)"
+  button=$?
+  
+  [ $button != 0 ] && error "User error: exited chromium version selection list"
+  
+  #get just chromium version NUMBER
+  version="$(echo "$version" | awk '{print $3}')"
+done
 
-if [ -z "$cb_url" ];then
-  error "Failed to determine the url for chromium-browser!\nChosen version was '$version'\nurl_list was: '$url_list'"
-elif [ -z "$l10n_url" ];then
-  error "Failed to determine the url for chromium-browser-l10n!\nChosen version was '$version'\nurl_list was: '$url_list'"
-elif [ -z "$ffmpeg_extra_url" ];then
-  error "Failed to determine the url for chromium-codecs-ffmpeg-extra!\nChosen version was '$version'\nurl_list was: '$url_list'"
+#geterate a list of urls to download based on the version number
+ #chromium-browser was renamed to chromium in newer versions
+  #ffmpeg-extra package is no longer needed in newer versions
+   #chromium-common is needed in newer versions
+package_names='chromium
+chromium-l10n
+chromium-common
+chromium-browser
+chromium-browser-l10n
+chromium-codecs-ffmpeg-extra'
+for package in $package_names; do
+  if echo "$url_list" | grep -q "/${package}_${version}\." ;then
+    if [ "$package" == chromium-browser ] && [[ "${download_urls[*]}" == *'/chromium_'* ]];then
+      true #avoid downloading chromium-browser dummy package if chromium package is the real one
+    elif [ "$package" == chromium-browser-l10n ] && [[ "${download_urls[*]}" == *'/chromium-l10n_'* ]];then
+      true #avoid downloading chromium-browser dummy package if chromium package is the real one
+    else
+      #if the debs are built for both bookworm and trixie, get the appropriate one
+      url="$(echo "$url_list" | grep "/${package}_${version}\.")" #has multiple lines
+      echo "$url"
+      if [[ "$url" == *deb12* ]] && [[ "$url" == *deb13* ]];then
+        if [ "$(get_codename)" == trixie ];then
+          url="$(echo "$url" | grep deb13)"
+        else
+          url="$(echo "$url" | grep deb12)"
+        fi
+      fi
+      #now version-sort to get the last rpt build of this chromium package version
+      download_urls+=("$(echo "$url" | sort -Vr | head -n1)")
+      status "$(echo "$url" | sort -Vr | head -n1)"
+    fi
+  fi
+done
+
+if ! echo "${download_urls[*]}" | grep -q '/chromium_\|/chromium-browser_' ;then
+  error "Failed to determine the url for chromium-browser!\nChosen version was '$version'\nurl_list was:\n'$url_list'"
 fi
 
 echo "Debs to install:
-$cb_url
-$l10n_url
-$ffmpeg_extra_url"
+${download_urls[*]}"
 
 #wait until chromium is not running
 if [ ! -z "$(ps aux | grep chromium | grep -v 'grep' )" ];then
@@ -94,7 +106,7 @@ if [ ! -z "$(ps aux | grep chromium | grep -v 'grep' )" ];then
 fi
 
 #back up chromium config directory
-if [ ! -d ~/.config/chromium.bak ];then
+if [ ! -d ~/.config/chromium.bak ] && [ -d ~/.config/chromium ];then
   echo "Backing up existing Chromium profile directory..."
   rm -rf ~/.config/chromium.bak
   
@@ -103,23 +115,25 @@ fi
 
 #download the files
 status "Downloading the packages..."
-rm -f cb.deb l10n.deb ffmpeg_extra.deb || error "Failed to remove cb.deb l10n.deb ffmpeg_extra.deb"
-wget -O cb.deb "https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/$cb_url" || error "Failed to download $cb_url"
-wget -O l10n.deb "https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/$l10n_url" || error "Failed to download $l10n_url"
-wget -O ffmpeg_extra.deb "https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/$ffmpeg_extra_url" || error "Failed to download $ffmpeg_extra_url"
+for download_url in ${download_urls[*]} ;do
+  filename="/tmp/$(basename "$download_url")"
+  rm -f "$filename" || error "Failed to first remove $filename"
+  wget -O "$filename" "$download_url" || exit 1
+  filenames+=("$filename")
+done
 
 status "Installing the packages..."
 apt_lock_wait
-sudo apt install -fy --allow-downgrades --allow-change-held-packages "$(pwd)/cb.deb" "$(pwd)/l10n.deb" "$(pwd)/ffmpeg_extra.deb" || error "APT failed to install the packages"
-rm -f cb.deb l10n.deb ffmpeg_extra.deb || error "Failed to remove cb.deb l10n.deb ffmpeg_extra.deb"
+sudo apt install -fy --allow-downgrades --allow-change-held-packages "${filenames[@]}" || error "APT failed to install the packages: ${filenames[*]}"
+rm -f "${filenames[@]}" || error "Failed to remove packages after installation"
 
 status "Holding Chromium version so it won't upgrade..."
-apt_lock_wait
-echo "chromium-browser hold" | sudo dpkg --set-selections
-apt_lock_wait
-echo "chromium-browser-l10n hold" | sudo dpkg --set-selections
-apt_lock_wait
-echo "chromium-codecs-ffmpeg-extra hold" | sudo dpkg --set-selections
+
+for filename in ${filenames[*]} ;do
+  package_name="$(basename "$filename" | sed 's/_.*//g')"
+  apt_lock_wait
+  echo "$package_name hold" | sudo dpkg --set-selections
+done
 
 if [ "$version" -le 88 ] && [ "$(get_codename)" == 'bullseye' ];then
   status "Fixing seccomp errors for Chromium $version on Bullseye."
