Fix StackEdit install-32

diff --git a/apps/StackEdit/install-32 b/apps/StackEdit/install-32
--- a/apps/StackEdit/install-32
+++ b/apps/StackEdit/install-32
@@ -9,7 +9,7 @@ function error {
 
 cd $HOME
 echo "Downloading..."
-wget https://github.com/Itai-Nelken/Nativefier-WebApps/releases/download/v3.0/StackEdit-nativefier_20210518_armv7l.deb || error 'Failed to Download!'
+wget https://github.com/Itai-Nelken/Nativefier-WebApps/releases/download/v3.0/StackEdit-linux-armv7l.tar.xz || error 'Failed to Download!'
 echo "extracting..."
 tar -xf StackEdit-linux-armv7l.tar.xz || error "Failed to extract!"
 echo "Renaming folder..."
