Fix bugs

diff --git a/apps/Xtreme Download Manager/install b/apps/Xtreme Download Manager/install
--- a/apps/Xtreme Download Manager/install
+++ b/apps/Xtreme Download Manager/install
@@ -1,13 +1,6 @@
 #!/bin/bash
 
-DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
-
-function error {
-  echo -e "\\e[91m$1\\e[39m"
-  exit 1
-}
-
-"${DIRECTORY}/pkg-install" "openjdk-11-jdk" "$(dirname "$0")" || error "Failed installing openjdk!"
+"${DIRECTORY}/pkg-install" "openjdk-11-jdk ffmpeg" "$(dirname "$0")" || error "Failed installing openjdk!"
 
 cd $HOME
 mkdir -p xdm 
@@ -20,12 +13,9 @@ sudo ./install.sh | grep -v "Installation completed" || error "Failed to execute
 sudo sed -i s=/opt/xdman/jre/bin/java=java=g /opt/xdman/xdman || error "Failed to change to system Java runtime!"
 
 # Fix 'Download failed. Failed to append/convert file parts, please check if the drive is full or write protected'
-wget -O ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-armhf-static.tar.xz || error "Failed to download ffmpeg!"
-tar -xf ffmpeg.tar.xz || error "Failed to extract ffmpeg!"
-sudo mv -f ./ffmpeg-git-20211009-armhf-static/ffmpeg /opt/xdman/ || error "Failed to move ffmpeg binary file to /opt/xdman/xdman/ !"
+sudo cp $(command -v ffmpeg) /opt/xdman || error "Failed to copy ffmpeg binary! Most likely ffmpeg is not installed. Please run \e[4msudo apt install ffmpeg\e[24m and install XDM again."
 
 # Delete unwanted files after installation
-cd $HOME
 rm -rf $HOME/xdm || error "Failed to remove installation leftovers!"
 
 # Reminder for users to install browser extensiom
