Github actions - update_apps.yaml workflow (#1330)
* add updater scripting function to github actions

validate new urls before making changes

add discord and btop++ update scripts

create update_github_script.sh
(designed to be sourced by other update scripts)
source update_github_script.sh

support install and add some preliminary documentation

check if install/install-32/install-64 exists before executing

* add btop++ and Discord update scripts

* update xdm to use version variables

* add xdm update script using array functionality

* add array functionality

allows for script writers to supply multiple webVer, pi_apps_ver, and url in array form

* set pi_app_ver to default if not supplied

* add a couple of apps

* add more apps

* add sed -z option (only operate on first match)

* only return first match and only replace first match

* use the default fallback unless necessary (to avoid code duplication)

* simplify validate_url and don't use wget api function

* create PR instead of pushing to repo

* remove author

* update PR info

* update github-actions email and remove duplicates from UPDATED_APPS

* change sort code

* add cron automation once daily

this will trigger the workflow once a day
if a previous PR has not been merged yet, it will force push to that PRs branch (this is a branch named auto-app-updates as defined in the yml)

* output updated apps a list

diff --git a/apps/Xtreme Download Manager/install b/apps/Xtreme Download Manager/install
--- a/apps/Xtreme Download Manager/install
+++ b/apps/Xtreme Download Manager/install
@@ -1,12 +1,16 @@
 #!/bin/bash
+
+version=7.2.11
+version2=2021.06.06
+
 cd $HOME
 mkdir -p xdm 
 cd xdm
 
 install_packages openjdk-11-jdk ffmpeg || exit 1
 
-wget -O xdm.tar.xz https://github.com/subhra74/xdm/releases/download/7.2.11/xdm-setup-7.2.11.tar.xz || error "Failed to download XDM setup tar file!"
-wget https://github.com/ytdl-org/youtube-dl/releases/download/2021.06.06/youtube-dl || error "Failed to download youtube-dl binary!"
+wget -O xdm.tar.xz https://github.com/subhra74/xdm/releases/download/${version}/xdm-setup-${version}.tar.xz || error "Failed to download XDM setup tar file!"
+wget https://github.com/ytdl-org/youtube-dl/releases/download/${version2}/youtube-dl || error "Failed to download youtube-dl binary!"
 tar -xf xdm.tar.xz || error "Failed to extract XDM setup tar file!"
 echo "Executing XDM setup script..."
 sudo ./install.sh &>/dev/null || error "Failed to execute XDM setup script!"
