remove custom dir feature

diff --git a/apps/Minecraft Java Server/install b/apps/Minecraft Java Server/install
--- a/apps/Minecraft Java Server/install
+++ b/apps/Minecraft Java Server/install
@@ -15,23 +15,8 @@ fi
 # add jq to use in script
 install_packages jq || exit 1
 
-# using the mcserdir.txt file or creating  it
-mkdir -p "$HOME/Documents"
-cd "$HOME/Documents" || error "Could not enter Documents folder."
-if [ -f "mcserdir.txt" ];then
-  # read mcserdir.txt
-  directory=$(cat "mcserdir.txt")
-  # make sure the user wants to install the server in the saved directory, as mcserdir.txt persists on uninstall
-  text="Using the $directory directory.\nIf you would like to use a different directory,\nexit the script and delete the $HOME/Documents/mcserdir.txt file."
-  userinput_func "$text" "Continue with the $directory directory"
-else
-  # allow user to select directory
-  directory=$(yad --center --wrap --text "Choose directory:\nDefault is $directory.\nMake sure it ends with Minecraft-Java-Server if you don't want it to fail." --entry --entry-text="$directory" --button="Submit":0)
-  # store directory in $HOME/Documents so it can be used later
-  echo "$directory" > mcserdir.txt
-fi
-mkdir -p "$directory" || error "$directory is invalid or privileged."
-cd "$directory" || error "Could not enter $directory folder."
+mkdir -p "$HOME/Minecraft-Java-Server"
+cd "$HOME/Minecraft-Java-Server" || error "Could not enter Minecraft-Java-Server folder."
 
 description="What type of Minecraft server\ndo you want to run?"
 table=("Vanilla" "Fabric" "Forge" "Paper" "Folia" "Purpur")
@@ -120,7 +105,7 @@ esac
 
 while [[ ! -a $(echo ${server_jar}) ]]; do
   description="Please use the website which has opened to download your chosen version of the Minecraft Java Server.\
-  \nAdd your ${server_jar} file to the folder opened $directory and press OK.\
+  \nAdd your ${server_jar} file to the folder opened $HOME/Minecraft-Java-Server and press OK.\
   \n\nYou have not added a ${server_jar}."
   table=("OK")
   userinput_func "$description" "${table[@]}"
@@ -252,7 +237,7 @@ done
 if [[ "$server_category" == "Forge" ]]; then
   # run the server installer
   rm -f start-server.sh
-  $java_location -jar $directory/${server_jar} --installServer || error "Failed to install forge server"
+  $java_location -jar $HOME/Minecraft-Java-Server/${server_jar} --installServer || error "Failed to install forge server"
   rm -f ${server_jar}
 
   # forge has MANY ways to launch depending on the version
@@ -282,10 +267,10 @@ if [[ "$server_category" == "Forge" ]]; then
 fi
 
 if [ -n "$server_jar" ]; then
-  sh -c "cat > $directory/start-server.sh << _EOF_
+  sh -c "cat > $HOME/Minecraft-Java-Server/start-server.sh << _EOF_
 #!/bin/bash
 echo 'Minecraft Server starting'
-$java_location $jvm_args -jar $directory/${server_jar} nogui || (echo -e '\e[91mMinecraft Server has crashed or could not start\e[0m'; sleep 10)
+$java_location $jvm_args -jar $HOME/Minecraft-Java-Server/${server_jar} nogui || (echo -e '\e[91mMinecraft Server has crashed or could not start\e[0m'; sleep 10)
 echo 'Minecraft Server has stopped'
 sleep 3
 _EOF_"
@@ -303,7 +288,7 @@ tee "$HOME/.local/share/applications/Minecraft-Java-Server.desktop" <<EOF
 [Desktop Entry]
 Name=Minecraft Java Server
 Exec=bash -c "sudo systemctl start minecraft-server; sleep 3; screen -r Minecraft_Server; if [ \$? == 1 ]; then echo 'The minecraft server has exited without the service stopping, restarting the service for you'; sudo systemctl restart minecraft-server; sleep 5; screen -r Minecraft_Server; fi"
-Path=$directory
+Path=$HOME/Minecraft-Java-Server
 Icon=${DIRECTORY}/apps/Minecraft Java Server/icon-64.png
 Type=Application
 Categories=Game
@@ -317,10 +302,10 @@ sleep_location=$(which sleep)
 sudo systemctl edit --stdin --full --force minecraft-server <<EOF
 [Service]
 RemainAfterExit=yes
-WorkingDirectory=$directory
+WorkingDirectory=$HOME/Minecraft-Java-Server
 User=$USER
 # Start Screen, Java, and Minecraft
-ExecStart=$screen_location -S Minecraft_Server -U -d -m $directory/start-server.sh
+ExecStart=$screen_location -S Minecraft_Server -U -d -m $HOME/Minecraft-Java-Server/start-server.sh
 # Tell Minecraft to gracefully stop.
 # Ending Minecraft will terminate Java
 # systemd will kill Screen after the 10-second delay. No explicit kill for Screen needed
