Update install

diff --git a/apps/PiKISS GUI/install b/apps/PiKISS GUI/install
--- a/apps/PiKISS GUI/install
+++ b/apps/PiKISS GUI/install
@@ -5,10 +5,11 @@ git_clone https://github.com/Jai-JAP/pikiss-gui || error 'Failed to clone PiKISS
 install_packages ninja-build gobject-introspection libgee-0.8-dev libgirepository1.0-dev libgtk-3-dev valac libgnome-menu-3-dev || exit 1
 
 if package_installed meson; then
-  sudo apt-get purge -y meson || error 'Failed to uninstall older version of meson'
+  sudo pip3 install --upgrade meson || error 'Failed to upgrade older version of meson from pip'
+else
+  sudo pip3 install meson || error 'Failed to install meson from pip'
 fi
 
-sudo pip3 install meson || error 'Failed to install meson from pip'
 "${DIRECTORY}/manage" install-if-not-installed piKiss || error "piKiss failed to install somehow!"
 
 cd pikiss-gui || error 'Failed to cd into pikiss-gui folder'
