mc java lunar launcher

diff --git a/apps/Minecraft Java/install-32 b/apps/Minecraft Java/install-32
--- a/apps/Minecraft Java/install-32
+++ b/apps/Minecraft Java/install-32
@@ -7,51 +7,100 @@ function error {
   exit 1
 }
 
-#use the error function often!
-#If a certain command is necessary for installation to continue, then add this to the end of it:
-# || error 'reason'
-#example below:
+#install modprobe if not already installed
+if ! command -v modprobe >/dev/null;then
+  
+  if [ -f /usr/bin/apt ];then
+    sudo apt update
+    sudo apt install -y modprobe || echo "Failed to install modprobe."
+  else
+    error "Failed to find any package manager to install modprobe."
+  fi
+fi
 
-#Run modified setupMC.sh
-mkdir ~/Minecraft && cd ~/Minecraft && wget https://github.com/chunky-milk/Minecraft/raw/main/setupMC.sh && chmod +x setupMC.sh && ./setupMC.sh || error 'Failed to install the launcher!'
+#Run modprobe fuse
+sudo modprobe fuse
 
-#Move launcher to /usr/share/
-sudo mkdir /usr/share/minecraftjava && sudo mv launcher.jar /usr/share/minecraftjava/launcher.jar
+cd ~
 
-#Create desktop shortcut
-cd ~/.local/share/applications/
+#Download client
+wget https://github.com/gl91306/lunar/raw/master/lunarclient-2.7.3b-armv7l.AppImage
+mkdir -p ~/.minecraft
+mv lunarclient-2.7.3b-armv7l.AppImage ~/.minecraft
+
+if [ ! -d ~/lwjgl3arm32 ]; then
+    mkdir ~/lwjgl3arm32
+fi
+if [ ! -d ~/lwjgl2arm32 ]; then
+    mkdir ~/lwjgl2arm32
+fi
+if [ ! -f jdk-8u251-linux-arm32-vfp-hflt.tar.gz ]; then
+    wget https://github.com/mikehooper/Minecraft/raw/main/jdk-8u251-linux-arm32-vfp-hflt.tar.gz
+fi
+if [ ! -f jdk-16.0.1+9-jre.tar.gz ]; then
+    wget https://github.com/gl91306/lunar/raw/master/jdk-16.0.1%2B9-jre.tar.gz
+fi
+if [ ! -f lwjgl3arm32.tar.gz ]; then
+    wget https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm32.tar.gz
+fi
+if [ ! -f lwjgl2arm32.tar.gz ]; then
+    wget https://github.com/mikehooper/Minecraft/raw/main/lwjgl2arm32.tar.gz
+fi
+if [ ! -d /opt/jdk ]; then
+    sudo mkdir /opt/jdk
+fi
+sudo tar -zxf jdk-8u251-linux-arm32-vfp-hflt.tar.gz -C /opt/jdk
+sudo tar -zxf jdk-16.0.1+9-jre.tar.gz -C /opt/jdk
+tar -zxf lwjgl3arm32.tar.gz -C ~/lwjgl3arm32
+tar -zxf lwjgl2arm32.tar.gz -C ~/lwjgl2arm32
+sudo update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_251/bin/java 0
+sudo update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_251/bin/javac 0
+sudo update-alternatives --set java /opt/jdk/jdk1.8.0_251/bin/java
+sudo update-alternatives --set javac /opt/jdk/jdk1.8.0_251/bin/javac
+cd lwjgl2arm32
+wget https://github.com/gl91306/lunar/raw/master/libwebp-imageio32.so
+cd
+cd lwjgl3arm32
+wget https://github.com/gl91306/lunar/raw/master/libwebp-imageio32.so
+cd
+cd /opt/jdk/opt/jdk
+sudo cp -r jdk-16.0.1+9-jre /opt/jdk
+cd /opt/jdk
+sudo rm -rf opt
+cd
+cd /opt/jdk/jdk1.8.0_251
+sudo rm -rf jre
+echo please wait a bit, as this step takes a bit
+sudo apt-get install subversion
+sudo svn checkout https://github.com/gl91306/lunar/trunk/jre
+cd
+sudo apt-get install unzip
+wget https://github.com/gl91306/lunar/raw/master/javafx-sdk-17.zip
+unzip javafx-sdk-17.zip -d /home/pi/Desktop
+cd
+#Change perms of Launcher
+sudo chmod +x $HOME/lunarclient-2.7.3b-armv7l.AppImage
+
+#Cleanup
+cd
+rm -rf jdk-8u251-linux-arm32-vfp-hflt.tar.gz
+rm -rf jdk-16.0.1+9-jre.tar.gz
+rm -rf javafx-sdk-17.zip
+rm -rf lwjgl2arm32.tar.gz
+rm -rf lwjgl3arm32.tar.gz
+
+
+#Then make menu shortcut
+
 echo "[Desktop Entry]
 Version=1.0
 Type=Application
 Name=Minecraft Launcher
 Comment=3D block based sandbox game
 Icon=$(dirname "$0")/icon-64.png
-Exec=env MESA_GL_VERSION_OVERRIDE=3.3 java -jar /usr/share/minecraftjava/launcher.jar
-Categories=Game;" > minecraft.desktop
-chmod +x minecraft.desktop
-cd
+Exec=env MESA_GL_VERSION_OVERRIDE=3.3 $HOME/.minecraft/lunarclient-2.7.3b-armv7l.AppImage 
+Categories=Game;" > ~/.local/share/applications/minecraftjava.desktop
+chmod +x ~/.local/share/applications/minecraftjava.desktop
+cp ~/.local/share/applications/minecraftjava.desktop ~/Desktop/
 
-mkdir -p ~/.minecraft
-echo -e '{
-  "profiles": {
-    "(Default)": {
-      "name": "(Default)",
-      "javaDir": "/opt/jdk-16.0.1+4/bin/java",
-      "javaArgs": "-Dorg.lwjgl.librarypath='$HOME'/lwjgl3arm32 -Xmx1G -XX:-UseAdaptiveSizePolicy -Xmn128M"
-    }
-  },
-  "selectedProfile": "(Default)",
-  "clientToken": "c4a6f915-4d47-47bf-a8f4-746090e7e576",
-  "authenticationDatabase": {},
-  "launcherVersion": {
-    "name": "1.6.93",
-    "format": 21,
-    "profilesFormat": 1
-  }
-}' > $HOME/.minecraft/launcher_profiles.json
-
-sudo rm -rf ~/Minecraft
-
-echo 'Installation is now done! You can open the launcher by going to Menu > Games > Minecraft Launcher'
-echo -e "\e[21m\e[5mWARNING:\e[0m\e[97mYou can only play Minecraft versions \e[1m1.13\e[0m and higher with your current configuration! To use lower versions, please follow the instructions at \e[96mhttps://www.noxxtech.tk/minecraft-install#h.fpnon3xvmuoz\e[39m to play versions \e[1m1.12\e[0m and under!"
-read -p "Press [Enter] to continue after you've read the above message"
+echo 'Installation is now done! You can open the launcher by going to Menu > Games > Minecraft Launcher or with the new shortcut on your desktop!'
