Update install

diff --git a/apps/Minecraft Java/install b/apps/Minecraft Java/install
--- a/apps/Minecraft Java/install
+++ b/apps/Minecraft Java/install
@@ -12,24 +12,20 @@ function error {
 # || error 'reason'
 #example below:
 
-#Download java and launcher
-rm -rf ~/Minecraft
+echo 'WARNING: This install script is only compatiable with 32-bit OSes for the time being. Please press [Enter] to continue.'
+read -p
 
-mkdir ~/Minecraft || error "Failed to create the directory!"
-cd ~/Minecraft || error "Failed to enter the directory!"
-wget https://www.dropbox.com/s/2602i5d0h4kteex/setupMC.sh  || error 'Failed to download launcher!'
-chmod +x setupMC.sh || error "failed to mark as executable!"
-./setupMC.sh
+#Download java and launcher
+mkdir ~/Minecraft && cd ~/Minecraft && wget https://www.dropbox.com/s/2602i5d0h4kteex/setupMC.sh && chmod +x setupMC.sh && ./setupMC.sh || error 'Failed to install the launcher!'
 
 #Move launcher to /usr/share/
-sudo mkdir /usr/share/minecraftjava && sudo mv launcher.jar /usr/share/minecraftjava/launcher.jar 
+sudo mkdir /usr/share/minecraftjava && sudo mv launcher.jar /usr/share/minecraftjava/launcher.jar
 
 #Create desktop shortcut
 cd ~/.local/share/applications/
 wget https://raw.githubusercontent.com/mobilegmYT/pi-apps-resources/main/Minecraft/minecraft.desktop
+chmod +x minecraft.desktop
 cd
-
-sudo chmod +x ~/.local/share/applications/minecraft.desktop
 
 mkdir -p ~/.minecraft
 echo '{
@@ -49,6 +45,5 @@ echo '{
   }
 }' > /home/pi/.minecraft/launcher_profiles.json
 
-#sudo update-java-alternatives -s java-1.11.0-openjdk-armhf
-
-java -jar /usr/share/minecraftjava/launcher.jar
+echo 'Installation is now done! You can open the launcher by going to Menu > Games > Minecraft Launcher'
+echo 'NOTE: You can only play versions 1.13 and higher with your current config. To use lower versions, please follow the instructions at https://www.noxxtech.tk/minecraft-install#h.fpnon3xvmuoz'
