Add to run and merge install-32 and install-64 into install

diff --git a/apps/DroidCam/install b/apps/DroidCam/install
--- a/apps/DroidCam/install
+++ b/apps/DroidCam/install
@@ -1,12 +1,17 @@
 #!/bin/bash
 
 libjpegturbo_version=2.1.3
+case $arch in
+    32) package_arch=armhf ;;
+    64) package_arch=arm64 ;;
+    *) error "Failed to detect architecture. Something is very wrong." ;;
+esac
 
 git_clone https://github.com/open-sorcerer64/Droid-Cam-RPi || exit 1
 git_clone https://github.com/dev47apps/droidcam || exit 1
 
 # Get dependencies
-install_packages $HOME/Droid-Cam-RPi/libjpeg-turbo_${libjpegturbo_version}_arm64.deb raspberrypi-kernel-headers libplist-dev libavutil-dev libswscale-dev libswscale-dev libspeex-dev libusbmuxd-dev libasound2-dev libappindicator3-dev make gcc pkg-config libgtk-3-dev libappindicator3-1 adb || exit 1
+install_packages $HOME/Droid-Cam-RPi/libjpeg-turbo_${libjpegturbo_version}_${package_arch}.deb raspberrypi-kernel-headers libplist-dev libavutil-dev libswscale-dev libswscale-dev libspeex-dev libusbmuxd-dev libasound2-dev libappindicator3-dev make gcc pkg-config libgtk-3-dev libappindicator3-1 adb || exit 1
 
 cd $HOME/droidcam
 make droidcam-cli || sudo make droidcam-cli || error "Failed to make droidcam-cli!"
@@ -16,4 +21,4 @@ sudo ./install-video || error "Failed to run install-video!"
 sudo ./install-sound || error "Failed to run install-sound!"
 
 #cleanup
-rm -rf $HOME/Droid-Cam-RPi || sudo rm -rf $HOME/Droid-Cam-RPi 
+rm -rf $HOME/Droid-Cam-RPi $HOME/droidcam || sudo rm -rf $HOME/Droid-Cam-RPi $HOME/droidcam
