Update MC Bedrock to final version v1.1.1-802 (#2815)

diff --git a/apps/Minecraft Bedrock/install-64 b/apps/Minecraft Bedrock/install-64
--- a/apps/Minecraft Bedrock/install-64
+++ b/apps/Minecraft Bedrock/install-64
@@ -16,16 +16,16 @@ else
   warning "Your system is only capable of running the ARM64 versions of Minecraft Bedrock. You will be unable to run older ARM32 versions of Minecraft Bedrock that you may find in this launcher."
 fi
 
+enable_module fuse || exit 1
+
 #Download file
 mkdir -p ~/.local/bin || error "Could not make directory"
 if package_is_new_enough libc6 2.36 ;then
-  wget -O ~/.local/bin/MCBedrock.AppImage 'https://github.com/minecraft-linux/appimage-builder/releases/download/v0.14.2-792/Minecraft_Bedrock_Launcher-bookworm-arm64-v0.14.2.792.AppImage' || error "failed to download Minecraft Bedrock Launcher"
+  wget -O ~/.local/bin/MCBedrock.AppImage 'https://github.com/minecraft-linux/appimage-builder/releases/download/v1.1.1-802/Minecraft_Bedrock_Launcher-bookworm-arm64-v1.1.1.802.AppImage' || error "failed to download Minecraft Bedrock Launcher"
 else
-  wget -O ~/.local/bin/MCBedrock.AppImage 'https://github.com/minecraft-linux/appimage-builder/releases/download/v0.14.2-792/Minecraft_Bedrock_Launcher-arm64-v0.14.2.792.AppImage' || error "failed to download Minecraft Bedrock Launcher"
+  wget -O ~/.local/bin/MCBedrock.AppImage 'https://github.com/minecraft-linux/appimage-builder/releases/download/v1.1.1-802/Minecraft_Bedrock_Launcher-arm64-v1.1.1.802.AppImage' || error "failed to download Minecraft Bedrock Launcher"
 fi
 chmod +x ~/.local/bin/MCBedrock.AppImage
-
-enable_module fuse || exit 1
 
 #Make Desktop file
 mkdir -p ~/.local/share/applications
