fix Minecraft Bedrock Launcher auto-updating
store appimage in ~/.local/bin instead of the root only /opt folder

also fix 64 install script to match 32 install script icon setting

replaces PR: https://github.com/Botspot/pi-apps/pull/1474

diff --git a/apps/Minecraft Bedrock/install-64 b/apps/Minecraft Bedrock/install-64
--- a/apps/Minecraft Bedrock/install-64
+++ b/apps/Minecraft Bedrock/install-64
@@ -5,20 +5,20 @@ sudo dpkg --add-architecture armhf
 install_packages curl libx11-6:armhf libxext6:armhf libegl1-mesa:armhf zlib1g:armhf libstdc++6:armhf libgl1-mesa-dri:armhf libasound2:armhf libpulse0:armhf libcom-err2:armhf libgmp10:armhf libp11-kit0:armhf libsystemd0:armhf libllvm9:armhf || exit 1
 
 #Download file
-wget -O ~/MCBedrock.AppImage 'https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/v0.3.2-682/Minecraft_Bedrock_Launcher-arm_aarch64-0.0.682.AppImage'
-chmod +x ~/MCBedrock.AppImage
-sudo mv -f ~/MCBedrock.AppImage /opt/MCBedrock.AppImage
+mkdir -p ~/.local/bin || error "Could not make directory"
+wget -O ~/.local/bin/MCBedrock.AppImage 'https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/v0.3.2-682/Minecraft_Bedrock_Launcher-arm_aarch64-0.0.682.AppImage' || error "failed to download Minecraft Bedrock Launcher"
+chmod +x ~/.local/bin/MCBedrock.AppImage
 
 enable_module fuse || exit 1
 
 #Make Desktop file
-echo '[Desktop Entry]
+echo "[Desktop Entry]
 Version=1.1
 Type=Application
 Name=Minecraft Bedrock Launcher
 Comment=A Minecraft: Bedrock Edition
-Icon='"$(dirname "$0")/icon-64.png"'
-Exec=bash -c "GALLIUM_HUD=simple,fps /opt/MCBedrock.AppImage"
+Icon=$(dirname "$0")/icon-64.png
+Exec=env GALLIUM_HUD=simple,fps $HOME/.local/bin/MCBedrock.AppImage
 Categories=Game;
 Terminal=false
-StartupNotify=true' > ~/.local/share/applications/minecraftbedrock.desktop
+StartupNotify=true" > ~/.local/share/applications/minecraftbedrock.desktop
