Remove binfmt restarting from deb before installing it

diff --git a/apps/Box86/install-64 b/apps/Box86/install-64
--- a/apps/Box86/install-64
+++ b/apps/Box86/install-64
@@ -43,5 +43,16 @@ echo "adding key..."
 wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add - || error "Failed to add key to box86 repo!"
 echo "running 'sudo apt update'..."
 sudo apt update || error "Failed to run sudo apt update"
+
 echo "installing box86..."
-sudo apt install box86 -y || error "Failed to install the box86 package"
+apt download box86:armhf || error "Failed to download box86 package!"
+DEB="$(basename box86*.deb)"
+DEBDIR="$(echo $DEB | sed 's/.deb//')"
+
+dpkg-deb -R $DEB $DEBDIR
+rm $DEBDIR/DEBIAN/postinst || error "Failed to remove '$DEBDIR/DEBIAN/postinst' file!"
+rm $DEB # doesn't matter if fails
+dpkg-deb -b $DEBDIR $DEB
+"${DIRECTORY}/pkg-install" "$(pwd)/$DEB" "$(dirname "$0")" || exit 1
+echo 'restarting systemd-binfmt...'
+sudo systemctl restart systemd-binfmt || error "Failed to restart systemd-binfmt!"
