fix key not found error

diff --git a/apps/Box86/install-32 b/apps/Box86/install-32
--- a/apps/Box86/install-32
+++ b/apps/Box86/install-32
@@ -5,7 +5,7 @@ fi
 
 sudo rm -f /etc/apt/sources.list.d/box86.list
 echo "Adding box86 repo..."
-sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list || error "Failed to download /etc/apt/sources.list.d/box86.list"
+echo "deb [signed-by=/usr/share/keyrings/box86-archive-keyring.gpg] https://itai-nelken.github.io/weekly-box86-debs/debian/ /" | sudo tee /etc/apt/sources.list.d/box86.list >/dev/null || error "Failed to download /etc/apt/sources.list.d/box86.list"
 echo "Adding key..."
 curl -fsSL https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/box86-archive-keyring.gpg || error "Failed to add key to box86 repo!"
 echo "Installing box86..."
diff --git a/apps/Box86/install-64 b/apps/Box86/install-64
--- a/apps/Box86/install-64
+++ b/apps/Box86/install-64
@@ -34,7 +34,7 @@ fi
 
 sudo rm /etc/apt/sources.list.d/box86.list &>/dev/null
 echo "Adding box86 repo..."
-wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -qO- | sed -r 's/deb /deb [arch=armhf] /' | sudo tee /etc/apt/sources.list.d/box86.list >/dev/null|| error "Failed to download /etc/apt/sources.list.d/box86.list"
+echo "deb [arch=armhf] [signed-by=/usr/share/keyrings/box86-archive-keyring.gpg] https://itai-nelken.github.io/weekly-box86-debs/debian/ /" | sudo tee /etc/apt/sources.list.d/box86.list >/dev/null || error "Failed to download /etc/apt/sources.list.d/box86.list"
 echo "Adding key..."
 curl -fsSL https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/box86-archive-keyring.gpg || error "Failed to add key to box86 repo!"
 echo "Installing box86..."
