Box86 and Box64: switch to `add_external_repo` and `rm_external_repo`

diff --git a/apps/Box86/install-32 b/apps/Box86/install-32
--- a/apps/Box86/install-32
+++ b/apps/Box86/install-32
@@ -9,19 +9,12 @@ if dpkg -l box86 &>/dev/null ;then
   sudo apt purge -y --allow-change-held-packages box86*
 fi
 
-sudo wget https://pi-apps-coders.github.io/box86-debs/box86.list -O /etc/apt/sources.list.d/box86.list
-if [ $? != 0 ];then
-  sudo rm -f /etc/apt/sources.list.d/box86.list
-  error "Failed to add box86.list file!"
-fi
+add_external_repo "box86" "https://Pi-Apps-Coders.github.io/box86-debs/debian ./" "https://pi-apps-coders.github.io/box86-debs/KEY.gpg" || exit 1
 
-sudo rm -f /usr/share/keyrings/box86-debs-archive-keyring.gpg /etc/apt/trusted.gpg.d/box86-debs-archive-keyring.gpg
-sudo mkdir -p /etc/apt/trusted.gpg.d
-wget -qO- https://pi-apps-coders.github.io/box86-debs/KEY.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/box86-debs-archive-keyring.gpg > /dev/null
-
-if [ $? != 0 ];then
-  sudo rm -f /etc/apt/sources.list.d/box86.list
-  error "Failed to add KEY.gpg to APT keyring!"
+apt_update
+if [ $? != 0 ]; then
+  rm_external_repo "box86"
+  error "Failed to perform apt update after adding box86 repository."
 fi
 
 # obtain SOC_ID
