box86: uninstall: skip apt if box86 command not found

diff --git a/apps/Box86/uninstall b/apps/Box86/uninstall
--- a/apps/Box86/uninstall
+++ b/apps/Box86/uninstall
@@ -15,8 +15,11 @@ function check-armhf() {
   ARMHF="$(dpkg --print-foreign-architectures | grep "armhf")"
 }
 
-echo "uninstalling box86..."
-sudo apt purge box86 -y || error "Failed to uninstall box86!"
+if command -v box86 >/dev/null;then
+  echo "uninstalling box86..."
+  sudo apt purge box86 -y || error "Failed to uninstall box86!"
+fi
+
 echo "removing box86 repo..."
 sudo rm -f /etc/apt/sources.list.d/box86.list || error "Failed to remove repo!"
 echo "removing box86 repo key..."
