total rework of persepolis script

diff --git a/apps/Persepolis Download Manager/install b/apps/Persepolis Download Manager/install
--- a/apps/Persepolis Download Manager/install
+++ b/apps/Persepolis Download Manager/install
@@ -1,13 +1,33 @@
 #!/bin/bash
 
-cd $HOME
-wget -O adwaita-qt.deb http://mirror.datamossa.io/raspbian/pool/main/a/adwaita-qt/adwaita-qt_1.0-2_armhf.deb
-wget -O youtube-dl.deb http://ftp.us.debian.org/debian/pool/main/y/youtube-dl/youtube-dl_2021.06.06-1_all.deb
-wget -O python3-setproctitle.deb http://mirror.rise.ph/raspbian/raspbian/pool/main/p/python-setproctitle/python3-setproctitle_1.1.10-1+b2_armhf.deb
-wget -O persepolis.deb https://github.com/persepolisdm/persepolis/releases/download/3.2.0/persepolis_3.2.0.2_all.deb 
-"${DIRECTORY}/pkg-install" "$(pwd)/persepolis.deb $(pwd)/youtube-dl.deb $(pwd)/python3-setproctitle.deb $(pwd)/adwaita-qt.deb aria2 python3 sound-theme-freedesktop libnotify-bin python3-pyqt5 libqt5svg5 python3-requests python3-setuptools python3-psutil ffmpeg python3-pyqt5.qtsvg" "$(dirname "$0")" || error "Failed installing Persepolis Download Manager!"
+install_packages lsb-release software-properties-common || error "Failed to install dependencies"
 
-rm -f persepolis.deb adwaita-qt.deb python3-setproctitle.deb youtube-dl.deb || error "Failed to cleanup!"
+# get debian version
+mapfile -t os < <(lsb_release -s -i -d -r -c)
+__os_id="${os[0]}"
+__os_desc="${os[1]}"
+__os_release="${os[2]}"
+__os_codename="${os[3]}"
+
+case "$__os_codename" in
+    buster)
+        sudo add-apt-repository "deb http://deb.debian.org/debian buster-backports main"
+        # add pin priority for youtube-dl so it will download from the backports repo
+        # this is not necessary for bullseye
+        # this will not interfere if the user has pinned the backports repo themselves
+        sudo sh -c "cat > /etc/apt/preferences.d/youtube-dl-backports << _EOF_
+Package: youtube-dl
+Pin: release a=buster-backports
+Pin-Priority: 500
+_EOF_"
+        sudo apt update
+        ;;
+esac
+
+# install some dependencies (these could be skipped as the .deb requires them, but it is good to check if they will install first)
+install_packages adwaita-qt python3-setproctitle python3 youtube-dl || error "Failed to install dependencies"
+
+install_packages "https://github.com/persepolisdm/persepolis/releases/download/3.2.0/persepolis_3.2.0.2_all.deb" || error "Failed to install persepolis"
 
 echo -e "\nYou may want to install Persepolis Download Manager Integration on your browser. For more info, see here: \e[4mhttps://github.com/persepolisdm/persepolis/wiki/Home-en#extensions\e[0m"
 
