tldr: only use armv6 binary on armv6 systems
default to armv7 binary on any other ARM32 OS system

workarounds upstream bug https://github.com/tealdeer-rs/tealdeer/issues/419

diff --git a/apps/tldr/install-32 b/apps/tldr/install-32
--- a/apps/tldr/install-32
+++ b/apps/tldr/install-32
@@ -1,6 +1,12 @@
 #!/bin/bash
 version=1.7.1
-wget -O /tmp/tldr https://github.com/tealdeer-rs/tealdeer/releases/download/v${version}/tealdeer-linux-arm-musleabihf || error "Failed to download tldr!"
+
+arm_arch=$(cat /proc/cpuinfo | grep "CPU architecture: " | head -n1 |  awk -F": "  '{print $2}' | cut -c 1)
+if [[ -n "$arm_arch" ]] && [[ "$arm_arch" == "6" ]]; then
+  wget -O /tmp/tldr https://github.com/tealdeer-rs/tealdeer/releases/download/v${version}/tealdeer-linux-arm-musleabihf || error "Failed to download tldr!"
+else
+  wget -O /tmp/tldr https://github.com/tealdeer-rs/tealdeer/releases/download/v${version}/tealdeer-linux-armv7-musleabihf || error "Failed to download tldr!"
+fi
 sudo mv /tmp/tldr /usr/bin/ || error "Failed to move binary to /usr/bin/"
 sudo chmod +x /usr/bin/tldr
 tldr --update
