many changes to app update checker

diff --git a/.github/workflows/update_apps.yml b/.github/workflows/update_apps.yml
--- a/.github/workflows/update_apps.yml
+++ b/.github/workflows/update_apps.yml
@@ -88,8 +88,8 @@ jobs:
         with:
           # this is a buster armhf image
           base_image: https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-09-26/2022-09-22-raspios-buster-armhf.img.xz
-          # the action by default copies the repository already instead of mounting it
-          # changes are not saved after the chroot is exited so it is safe to operate within the pi-apps directory
+          # bind mount the directory so any changes propogate to outside the chroot
+          bind_mount_repository: yes
 
           # give the image more space
           image_additional_mb: 5000
@@ -99,6 +99,9 @@ jobs:
 
           # user runner name as default path
           copy_repository_path: /home/runner/pi-apps
+
+          # export github env back to outside the chroot
+          export_github_env: yes
 
           import_github_env: true
           commands: |
@@ -118,14 +121,21 @@ jobs:
             # store apps changed from last commit to working directory in varaible
             changed_apps="$(git diff --name-only | grep ^apps/ | awk -F '/' '{print $2}' | sort -u)"
 
-            # debugging, set changed_apps to Arduino as a test app
-            changed_apps="Arduino"
+            # debugging, set changed_apps to Fake-app as a test app
+            changed_apps="Fake-app"
+            echo "test" > ./app/test.txt
 
             # attempt to install updated apps using manage script loop
-            # if any app fails, checkout the previous version and add it to the FAILED_APPS variable
+            # if any app fails, checkout the previous version and add it to the /tmp/failed_update_apps file
             for app in $changed_apps; do
-              ./manage install "$app" || ( git checkout -- "apps/$app"; echo "Failed to install $app, reverting to previous version" )
+              ./manage install "$app" || ( git checkout -- "apps/$app"; echo "**Failed to install $app, reverting to previous version.**" >> /tmp/failed_update_apps )
             done
+
+            if test -f /tmp/failed_update_apps; then
+              echo "FAILED_UPDATE_APPS<<EOF" >> $GITHUB_ENV
+              cat /tmp/failed_update_apps | sed '0~1 a\\' >> $GITHUB_ENV
+              echo "EOF" >> $GITHUB_ENV
+            fi
 
 
       - name: Create Pull Request
@@ -146,3 +156,4 @@ jobs:
             ${{ env.UPDATED_APPS }}
             ```
             ${{ env.FAILED_APPS }}
+            ${{ env.FAILED_UPDATE_APPS }}
