update cmake from theofficialgman ppa in github actions workflow
to fix https://gitlab.kitware.com/cmake/cmake/-/issues/20568 seen in https://github.com/Botspot/pi-apps/actions/runs/3889206669/jobs/6637275479#step:4:1246

diff --git a/.github/workflows/update_apps.yml b/.github/workflows/update_apps.yml
--- a/.github/workflows/update_apps.yml
+++ b/.github/workflows/update_apps.yml
@@ -129,6 +129,19 @@ jobs:
             sudo apt update
             sudo apt install -y yad curl wget aria2 lsb-release software-properties-common apt-utils imagemagick bc librsvg2-bin locales shellcheck git wmctrl xdotool x11-utils rsync
 
+            # upgrade cmake to 3.20+ from theofficialgman ppa to fix QEMU only issue https://gitlab.kitware.com/cmake/cmake/-/issues/20568
+
+            echo "Adding cmake PPA repository..."
+            echo "deb [arch=$(dpkg --print-architecture)] https://ppa.launchpadcontent.net/theofficialgman/cmake-bionic/ubuntu bionic main " | sudo tee /etc/apt/sources.list.d/theofficialgman-ubuntu-cmake-bionic-bionic.list || error "Failed to add repository to sources.list!"
+
+            # Add cmake ppa keyring
+            echo "Signing cmake PPA repository..."
+            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0ACACB5D1E74E484
+            if [ $? != 0 ];then
+              sudo rm -f /etc/apt/sources.list.d/theofficialgman-ubuntu-cmake-bionic-bionic.list
+              error "Failed to sign the cmake PPA!"
+            fi
+
             # store apps changed from last commit to working directory in varaible
             mapfile -t changed_apps < <(git diff --name-only | grep ^apps/ | awk -F '/' '{print $2}' | sort -u)
 
@@ -190,6 +203,19 @@ jobs:
             # install pi-apps dependencies
             sudo apt update
             sudo apt install -y yad curl wget aria2 lsb-release software-properties-common apt-utils imagemagick bc librsvg2-bin locales shellcheck git wmctrl xdotool x11-utils rsync
+
+            # upgrade cmake to 3.20+ from theofficialgman ppa to fix QEMU only issue https://gitlab.kitware.com/cmake/cmake/-/issues/20568
+
+            echo "Adding cmake PPA repository..."
+            echo "deb [arch=$(dpkg --print-architecture)] https://ppa.launchpadcontent.net/theofficialgman/cmake-bionic/ubuntu bionic main " | sudo tee /etc/apt/sources.list.d/theofficialgman-ubuntu-cmake-bionic-bionic.list || error "Failed to add repository to sources.list!"
+
+            # Add cmake ppa keyring
+            echo "Signing cmake PPA repository..."
+            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0ACACB5D1E74E484
+            if [ $? != 0 ];then
+              sudo rm -f /etc/apt/sources.list.d/theofficialgman-ubuntu-cmake-bionic-bionic.list
+              error "Failed to sign the cmake PPA!"
+            fi
 
             # store apps changed from last commit to working directory in varaible
             mapfile -t changed_apps < <(git diff --name-only | grep ^apps/ | awk -F '/' '{print $2}' | sort -u)
