ubuntu jammy (22.04) has removed openjdk-16, only install if available
openjdk-17 works for running minecraft 1.17.X+ but 16 should be installed if available (because thats what mojang uses)

diff --git a/apps/Minecraft Java MultiMC5/install b/apps/Minecraft Java MultiMC5/install
--- a/apps/Minecraft Java MultiMC5/install
+++ b/apps/Minecraft Java MultiMC5/install
@@ -137,7 +137,12 @@ case "$__os_id" in
                 ;;
         esac
         # install dependencies
-        install_packages build-essential libopenal1 x11-xserver-utils git clang cmake curl zlib1g-dev openjdk-8-jre openjdk-17-jre openjdk-11-jdk openjdk-16-jre qtbase5-dev || error "Failed to install dependencies"
+        java_16=""
+        package_available openjdk-16-jre
+        if [[ $? == "0" ]]; then
+            java_16="openjdk-16-jre"
+        fi
+        install_packages build-essential libopenal1 x11-xserver-utils git clang cmake curl zlib1g-dev openjdk-8-jre openjdk-11-jdk openjdk-17-jre $java_16 qtbase5-dev || error "Failed to install dependencies"
         hash -r
         ;;
     *)
