allow installation on buster using backports python 3.8 repo

diff --git a/apps/Minecraft Java MultiMC5/install b/apps/Minecraft Java MultiMC5/install
--- a/apps/Minecraft Java MultiMC5/install
+++ b/apps/Minecraft Java MultiMC5/install
@@ -180,6 +180,7 @@ case "$__os_id" in
     Raspbian|Debian)
         case "$__os_codename" in
             bullseye) modmanager="1"; python_version="python3";;
+            buster) modmanager="1"; python_version="python3.8";;
         esac
         ;;
     LinuxMint|Linuxmint|Ubuntu|[Nn]eon|Pop|Zorin|[eE]lementary|[jJ]ing[Oo][sS])
@@ -204,23 +205,59 @@ if [[ $modmanager == 1 ]]; then
     --button="NO, do NOT add the mod script":1
     case "$?" in
         "0")
-            # install modmanager python script
-            install_packages $python_version python3-pip jq || error "Failed to install mod installer script dependencies"
-            hash -r
-            $python_version -m pip install --upgrade pip minecraft-mod-manager
-            unset python_version
+            case "$__os_codename" in
+                buster)
+                    status "Adding deb-pascalroeleven repository for python3.8 backport:"
 
-            # creating mod updater script
-            wget -O scripts/pre-launch.sh "https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/assets/MultiMC/pre-launch.sh"
-            chmod +x scripts/pre-launch.sh
+                    echo "- public key -> keyring"
 
-            # fabric mods installed by default
-            # mods are disabled by default until the user uses the "Install Fabric" button in MultiMC
-            echo "Setting list of mods installed by the megascript by default"
-            echo "Make sure to click the Install Fabric button within MultiMC to enable these mods"
-            echo ""
-            wget -O scripts/megascript-mods.txt "https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/assets/MultiMC/megascript-mods.txt"
-            status "Mod script installed."
+                    rm -f /tmp/deb-pascalroeleven-public-key /tmp/deb-pascalroeleven-archive-keyring.gpg
+                    wget -O /tmp/deb-pascalroeleven-public-key https://pascalroeleven.nl/deb-pascalroeleven.gpg
+                    gpg --no-default-keyring --keyring /tmp/deb-pascalroeleven-keyring.gpg --import /tmp/deb-pascalroeleven-public-key
+                    rm -f /tmp/deb-pascalroeleven-public-key
+
+                    echo " - keyring -> GPG key"
+                    gpg --no-default-keyring --keyring /tmp/deb-pascalroeleven-keyring.gpg --export --output /tmp/deb-pascalroeleven-archive-keyring.gpg 
+                    rm -f /tmp/deb-pascalroeleven-keyring.gpg
+
+                    echo " - Moving GPG key to /usr/share/keyrings"
+                    sudo mv -f /tmp/deb-pascalroeleven-archive-keyring.gpg /usr/share/keyrings
+
+                    echo " - Creating /etc/apt/sources.list.d/deb-pascalroeleven.list"
+                    echo "deb [signed-by=/usr/share/keyrings/deb-pascalroeleven-archive-keyring.gpg] http://deb.pascalroeleven.nl/python3.8 buster-backports main" | sudo tee /etc/apt/sources.list.d/deb-pascalroeleven.list >/dev/null
+
+                    (install_packages python3.8)
+                    if [ $? != 0 ]; then
+                        anything_installed_from_repo "http://deb.pascalroeleven.nl/python3.8"
+                        if [ $? != 0 ]; then
+                            # nothing installed from repo, this check is to prevent removing repos which other pi-apps scripts or the user have used successfully
+                            # safe to remove
+                            sudo rm -f /etc/apt/sources.list.d/deb-pascalroeleven.list /usr/share/keyrings/deb-pascalroeleven-archive-keyring.gpg
+                        fi
+                        warning "Failed to install python3.8 packages. deb-pascalroeleven repository has been removed."  && warning "Forcefully skipping installing the mod installer script." && echo "" && warning "Continuing the MultiMC5 Install without automatic mod installer."
+                        modmanager="0"
+                    fi
+            esac
+            # check again if modmanager is still 1 incase python3.8 failed to install on buster
+            if [[ $modmanager == 1 ]]; then
+                # install modmanager python script
+                install_packages $python_version python3-pip jq || error "Failed to install mod installer script dependencies"
+                hash -r
+                $python_version -m pip install --upgrade pip minecraft-mod-manager
+                unset python_version
+
+                # creating mod updater script
+                wget -O scripts/pre-launch.sh "https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/assets/MultiMC/pre-launch.sh"
+                chmod +x scripts/pre-launch.sh
+
+                # fabric mods installed by default
+                # mods are disabled by default until the user uses the "Install Fabric" button in MultiMC
+                echo "Setting list of mods installed by the megascript by default"
+                echo "Make sure to click the Install Fabric button within MultiMC to enable these mods"
+                echo ""
+                wget -O scripts/megascript-mods.txt "https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/assets/MultiMC/megascript-mods.txt"
+                status "Mod script installed."
+            fi
             ;;
         *)
             modmanager="0"
